(function(){'use strict';var g,aa="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},ba;if("function"==typeof Object.setPrototypeOf)ba=Object.setPrototypeOf;else{var ca;a:{var da={K:!0},ea={};try{ea.__proto__=da;ca=ea.K;break a}catch(a){}ca=!1}ba=ca?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var fa=ba;
function ha(a,b){a.prototype=aa(b.prototype);a.prototype.constructor=a;if(fa)fa(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.u=b.prototype}var ia="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this,ja="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};
function l(a,b){if(b){var c=ia;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&ja(c,a,{configurable:!0,writable:!0,value:b})}}function ka(a,b,c){if(null==a)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(b instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return a+""}
l("String.prototype.startsWith",function(a){return a?a:function(b,c){var d=ka(this,b,"startsWith"),e=d.length,f=b.length;c=Math.max(0,Math.min(c|0,d.length));for(var h=0;h<f&&c<e;)if(d[c++]!=b[h++])return!1;return h>=f}});l("Object.setPrototypeOf",function(a){return a||fa});
var la=function(){function a(){function c(){}new c;Reflect.construct(c,[],function(){});return new c instanceof c}if("undefined"!=typeof Reflect&&Reflect.construct){if(a())return Reflect.construct;var b=Reflect.construct;return function(c,d,e){c=b(c,d);e&&Reflect.setPrototypeOf(c,e.prototype);return c}}return function(c,d,e){void 0===e&&(e=c);e=aa(e.prototype||Object.prototype);return Function.prototype.apply.call(c,e,d)||e}}();l("Reflect.construct",function(){return la});
l("String.prototype.includes",function(a){return a?a:function(b,c){return-1!==ka(this,b,"includes").indexOf(b,c||0)}});var m=this||self;function n(a){return void 0!==a}function p(a){return"string"==typeof a}function q(a){return"number"==typeof a}function ma(){}
function r(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function t(a){return"array"==r(a)}function u(a){var b=r(a);return"array"==b||"object"==b&&"number"==typeof a.length}function v(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}function na(a,b,c){return a.call.apply(a.bind,arguments)}
function oa(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,d);return a.apply(b,e)}}return function(){return a.apply(b,arguments)}}function pa(a,b,c){Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?pa=na:pa=oa;return pa.apply(null,arguments)}
function qa(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var d=c.slice();d.push.apply(d,arguments);return a.apply(this,d)}}function w(a,b){function c(){}c.prototype=b.prototype;a.u=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.ba=function(d,e,f){for(var h=Array(arguments.length-2),k=2;k<arguments.length;k++)h[k-2]=arguments[k];return b.prototype[e].apply(d,h)}};var ra;var sa=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if(p(a))return p(b)&&1==b.length?a.indexOf(b,0):-1;for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},x=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=p(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},ta=Array.prototype.filter?function(a,b){return Array.prototype.filter.call(a,b,void 0)}:function(a,b){for(var c=
a.length,d=[],e=0,f=p(a)?a.split(""):a,h=0;h<c;h++)if(h in f){var k=f[h];b.call(void 0,k,h,a)&&(d[e++]=k)}return d};function ua(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};function va(a,b,c){for(var d in a)b.call(c,a[d],d,a)}function wa(a,b){for(var c in a)if(b.call(void 0,a[c],c,a))return!0;return!1}var xa="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function ya(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<xa.length;f++)c=xa[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};function y(){this.a="";this.c=null;this.b=za}g=y.prototype;g.s=!0;g.m=function(){return this.a.toString()};g.B=!0;g.i=function(){return 1};g.ca=function(a,b){var c=Aa.exec(Ba(this).toString()),d=c[3]||"";a=c[1]+Ca("?",c[2]||"",a)+Ca("#",d,b);b=new y;b.a=a;return b};function Ba(a){return a instanceof y&&a.constructor===y&&a.b===za?a.a:"type_error:TrustedResourceUrl"}var Aa=/^([^?#]*)(\?[^#]*)?(#[\s\S]*)?/,za={};
function Ca(a,b,c){if(null==c)return b;if(p(c))return c?a+encodeURIComponent(c):"";for(var d in c){var e=c[d];e=t(e)?e:[e];for(var f=0;f<e.length;f++){var h=e[f];null!=h&&(b||(b=a),b+=(b.length>a.length?"&":"")+encodeURIComponent(d)+"="+encodeURIComponent(String(h)))}}return b};var Da=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]};
function Ea(a,b){if(b)a=a.replace(Fa,"&amp;").replace(Ga,"&lt;").replace(Ha,"&gt;").replace(Ia,"&quot;").replace(Ja,"&#39;").replace(Ka,"&#0;");else{if(!La.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(Fa,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(Ga,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(Ha,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(Ia,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(Ja,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(Ka,"&#0;"))}return a}
var Fa=/&/g,Ga=/</g,Ha=/>/g,Ia=/"/g,Ja=/'/g,Ka=/\x00/g,La=/[\x00&<>"']/;function Ma(a,b){return a<b?-1:a>b?1:0};function z(){this.a="";this.b=Na}z.prototype.s=!0;z.prototype.m=function(){return this.a.toString()};z.prototype.B=!0;z.prototype.i=function(){return 1};var Na={};function Oa(a){var b=new z;b.a=a;return b}Oa("about:blank");var A;a:{var Pa=m.navigator;if(Pa){var Qa=Pa.userAgent;if(Qa){A=Qa;break a}}A=""};function B(){this.a="";this.c=Ra;this.b=null}B.prototype.B=!0;B.prototype.i=function(){return this.b};B.prototype.s=!0;B.prototype.m=function(){return this.a.toString()};function C(a){return a instanceof B&&a.constructor===B&&a.c===Ra?a.a:"type_error:SafeHtml"}function D(a){if(a instanceof B)return a;var b="object"==typeof a,c=null;b&&a.B&&(c=a.i());a=Ea(b&&a.s?a.m():String(a));return E(a,c)}
function Sa(a){function b(f){t(f)?x(f,b):(f=D(f),e.push(C(f).toString()),f=f.i(),0==d?d=f:0!=f&&d!=f&&(d=null))}var c=D(Ta),d=c.i(),e=[];x(a,b);return E(e.join(C(c).toString()),d)}function Ua(a){return Sa(Array.prototype.slice.call(arguments))}var Ra={};function E(a,b){var c=new B;c.a=a;c.b=b;return c}E("<!DOCTYPE html>",0);var Ta=E("",0),Va=E("<br>",0);var Wa=function(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}}(function(){var a=document.createElement("div"),b=document.createElement("div");b.appendChild(document.createElement("div"));a.appendChild(b);b=a.firstChild.firstChild;a.innerHTML=C(Ta);return!b.parentElement});function Xa(a,b){if(Wa())for(;a.lastChild;)a.removeChild(a.lastChild);a.innerHTML=C(b)};function Ya(a){return a=Ea(a,void 0)};var F="StopIteration"in m?m.StopIteration:{message:"StopIteration",stack:""};function G(){}G.prototype.a=function(){throw F;};G.prototype.j=function(){return this};function Za(a){if(a instanceof G)return a;if("function"==typeof a.j)return a.j(!1);if(u(a)){var b=0,c=new G;c.a=function(){for(;;){if(b>=a.length)throw F;if(b in a)return a[b++];b++}};return c}throw Error("Not implemented");}
function $a(a,b){if(u(a))try{x(a,b,void 0)}catch(c){if(c!==F)throw c;}else{a=Za(a);try{for(;;)b.call(void 0,a.a(),void 0,a)}catch(c){if(c!==F)throw c;}}}function ab(a){if(u(a))return ua(a);a=Za(a);var b=[];$a(a,function(c){b.push(c)});return b};var bb={},cb={},db={},eb={};function H(){throw Error("Do not instantiate directly");}H.prototype.w=null;H.prototype.toString=function(){return this.D};H.prototype.a=function(){if(this.f!==cb)throw Error("Sanitized content was not of kind URI.");return Oa(this.toString())};function fb(){H.call(this)}w(fb,H);fb.prototype.f=bb;function gb(a){gb[" "](a);return a}gb[" "]=ma;function hb(a,b){var c=ib;return Object.prototype.hasOwnProperty.call(c,a)?c[a]:c[a]=b(a)};var jb=-1!=A.indexOf("Opera"),I=-1!=A.indexOf("Trident")||-1!=A.indexOf("MSIE"),kb=-1!=A.indexOf("Edge"),lb=-1!=A.indexOf("Gecko")&&!(-1!=A.toLowerCase().indexOf("webkit")&&-1==A.indexOf("Edge"))&&!(-1!=A.indexOf("Trident")||-1!=A.indexOf("MSIE"))&&-1==A.indexOf("Edge"),J=-1!=A.toLowerCase().indexOf("webkit")&&-1==A.indexOf("Edge"),mb=-1!=A.indexOf("Macintosh");function nb(){var a=m.document;return a?a.documentMode:void 0}var ob;
a:{var pb="",qb=function(){var a=A;if(lb)return/rv:([^\);]+)(\)|;)/.exec(a);if(kb)return/Edge\/([\d\.]+)/.exec(a);if(I)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(J)return/WebKit\/(\S+)/.exec(a);if(jb)return/(?:Version)[ \/]?(\S+)/.exec(a)}();qb&&(pb=qb?qb[1]:"");if(I){var rb=nb();if(null!=rb&&rb>parseFloat(pb)){ob=String(rb);break a}}ob=pb}var sb=ob,ib={};
function K(a){return hb(a,function(){for(var b=0,c=Da(String(sb)).split("."),d=Da(String(a)).split("."),e=Math.max(c.length,d.length),f=0;0==b&&f<e;f++){var h=c[f]||"",k=d[f]||"";do{h=/(\d*)(\D*)(.*)/.exec(h)||["","","",""];k=/(\d*)(\D*)(.*)/.exec(k)||["","","",""];if(0==h[0].length&&0==k[0].length)break;b=Ma(0==h[1].length?0:parseInt(h[1],10),0==k[1].length?0:parseInt(k[1],10))||Ma(0==h[2].length,0==k[2].length)||Ma(h[2],k[2]);h=h[3];k=k[3]}while(0==b)}return 0<=b})}var L;var tb=m.document;
L=tb&&I?nb()||("CSS1Compat"==tb.compatMode?parseInt(sb,10):5):void 0;function ub(a){if(null!=a)switch(a.w){case 1:return 1;case -1:return-1;case 0:return 0}return null}function vb(a){return null!=a&&a.f===bb?a:a instanceof B?M(C(a).toString(),a.i()):M(Ya(String(String(a))),ub(a))}var M=function(a){function b(c){this.D=c}b.prototype=a.prototype;return function(c,d){c=new b(String(c));void 0!==d&&(c.w=d);return c}}(fb);function wb(a){return null!=a&&a.f===bb?String(String(a.D).replace(xb,"").replace(yb,"&lt;")).replace(zb,Ab):Ya(String(a))}
function Bb(a){null!=a&&a.f===cb||null!=a&&a.f===db?a=String(a).replace(Cb,Db):a instanceof z?a=String((a instanceof z&&a.constructor===z&&a.b===Na?a.a:"type_error:SafeUrl").toString()).replace(Cb,Db):a instanceof y?a=String(Ba(a).toString()).replace(Cb,Db):(a=String(a),a=Eb.test(a)?a.replace(Cb,Db):"about:invalid#zSoyz");return a}
var Fb={"\x00":"&#0;","\t":"&#9;","\n":"&#10;","\x0B":"&#11;","\f":"&#12;","\r":"&#13;"," ":"&#32;",'"':"&quot;","&":"&amp;","'":"&#39;","-":"&#45;","/":"&#47;","<":"&lt;","=":"&#61;",">":"&gt;","`":"&#96;","\u0085":"&#133;","\u00a0":"&#160;","\u2028":"&#8232;","\u2029":"&#8233;"};function Ab(a){return Fb[a]}
var Gb={"\x00":"%00","\u0001":"%01","\u0002":"%02","\u0003":"%03","\u0004":"%04","\u0005":"%05","\u0006":"%06","\u0007":"%07","\b":"%08","\t":"%09","\n":"%0A","\x0B":"%0B","\f":"%0C","\r":"%0D","\u000e":"%0E","\u000f":"%0F","\u0010":"%10","\u0011":"%11","\u0012":"%12","\u0013":"%13","\u0014":"%14","\u0015":"%15","\u0016":"%16","\u0017":"%17","\u0018":"%18","\u0019":"%19","\u001a":"%1A","\u001b":"%1B","\u001c":"%1C","\u001d":"%1D","\u001e":"%1E","\u001f":"%1F"," ":"%20",'"':"%22","'":"%27","(":"%28",
")":"%29","<":"%3C",">":"%3E","\\":"%5C","{":"%7B","}":"%7D","\u007f":"%7F","\u0085":"%C2%85","\u00a0":"%C2%A0","\u2028":"%E2%80%A8","\u2029":"%E2%80%A9","\uff01":"%EF%BC%81","\uff03":"%EF%BC%83","\uff04":"%EF%BC%84","\uff06":"%EF%BC%86","\uff07":"%EF%BC%87","\uff08":"%EF%BC%88","\uff09":"%EF%BC%89","\uff0a":"%EF%BC%8A","\uff0b":"%EF%BC%8B","\uff0c":"%EF%BC%8C","\uff0f":"%EF%BC%8F","\uff1a":"%EF%BC%9A","\uff1b":"%EF%BC%9B","\uff1d":"%EF%BC%9D","\uff1f":"%EF%BC%9F","\uff20":"%EF%BC%A0","\uff3b":"%EF%BC%BB",
"\uff3d":"%EF%BC%BD"};function Db(a){return Gb[a]}var zb=/[\x00\x22\x27\x3c\x3e]/g,Cb=/[\x00- \x22\x27-\x29\x3c\x3e\\\x7b\x7d\x7f\x85\xa0\u2028\u2029\uff01\uff03\uff04\uff06-\uff0c\uff0f\uff1a\uff1b\uff1d\uff1f\uff20\uff3b\uff3d]/g,Eb=/^(?![^#?]*\/(?:\.|%2E){2}(?:[\/?#]|$))(?:(?:https?|mailto):|[^&:\/?#]*(?:[\/?#]|$))/i,xb=/<(?:!|\/?([a-zA-Z][a-zA-Z0-9:\-]*))(?:[^>'"]|"[^"]*"|'[^']*')*>/g,yb=/</g;function Hb(){return M('<div class="devsite-snackbar-snack" type="loading"><div class="devsite-snackbar-inner"><div class="devsite-snackbar-message">Loading</div><div class="devsite-snackbar-action"><devsite-spinner single-color="#ffffff"></devsite-spinner></div></div></div>')}
function Ib(){return M('<div class="devsite-snackbar-snack" type="refresh"><div class="devsite-snackbar-inner"><div class="devsite-snackbar-message">A new version is available</div><button class="devsite-snackbar-action">Refresh</button></div></div>')}
function Jb(){return M('<div class="devsite-snackbar-snack" type="error"><div class="devsite-snackbar-inner"><div class="devsite-snackbar-message">Something went wrong. Please try again.</div><button class="devsite-snackbar-action">Retry</button></div></div>')}function Kb(){return M('<div class="devsite-snackbar-snack" type="copied-to-clipboard"><div class="devsite-snackbar-inner"><div class="devsite-snackbar-message">Copied to clipboard</div></div></div>')}
function Lb(a){a=a||{};a=a.L;a='<div class="devsite-snackbar-snack" type="cookie-notification"><div class="devsite-snackbar-inner"><div class="devsite-snackbar-message">We serve cookies on this site to analyse traffic, remember your preferences, and optimise your experience.'+('</div><a href="'+(a?wb(Bb(a)):"//policies.google.com/technologies/cookies")+'" class="devsite-snackbar-link button">');return M(a+'More details</a><button class="devsite-snackbar-action">OK</button></div></div>')}
function Mb(){return M('<div class="devsite-snackbar-snack" type="support-attachment-error"><div class="devsite-snackbar-inner"><div class="devsite-snackbar-message">Unsupported file type.</div><button class="devsite-snackbar-action">OK</button></div></div>')}
function Nb(a){var b=a.message,c=a.link,d=a.U;a='<div class="devsite-snackbar-snack" type="'+wb(a.X)+'"><div class="devsite-snackbar-inner"><div class="devsite-snackbar-message">'+vb(b)+'</div><button class="devsite-snackbar-action">';a=a+"No, thanks"+('</button><a href="'+wb(Bb(c))+'" class="devsite-snackbar-link button" target="_blank">');a=d?a+vb(d):a+"OK";return M(a+"</a></div></div>")}
function Ob(a){var b=a.W;a='<div class="devsite-snackbar-snack" type="custom"><div class="devsite-snackbar-inner"><div class="devsite-snackbar-message">'+vb(a.message)+"</div>";b&&(a+='<button class="devsite-snackbar-action">OK</button>');return M(a+"</div></div>")};/*
 Copyright (c) Microsoft Corporation. All rights reserved.
 Licensed under the Apache License, Version 2.0 (the "License"); you may not use
 this file except in compliance with the License. You may obtain a copy of the
 License at http://www.apache.org/licenses/LICENSE-2.0

 THIS CODE IS PROVIDED ON AN *AS IS* BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION ANY IMPLIED
 WARRANTIES OR CONDITIONS OF TITLE, FITNESS FOR A PARTICULAR PURPOSE,
 MERCHANTABLITY OR NON-INFRINGEMENT.

 See the Apache Version 2.0 License for specific language governing permissions
 and limitations under the License.
*/
var Pb=!/^\s*class\s*\{\s*\}\s*$/.test(function(){}.toString());/*

 Copyright (c) 2016 The Polymer Project Authors. All rights reserved.
 This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
 The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
 The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
 Code distributed by Google as part of the polymer project is also
 subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
(function(){if(Pb&&!HTMLElement.es5Shimmed&&void 0!==window.Reflect&&void 0!==window.customElements&&!window.customElements.polyfillWrapFlushCallback){var a=HTMLElement;window.HTMLElement=function(){return Reflect.construct(a,[],this.constructor)};HTMLElement.prototype=a.prototype;HTMLElement.prototype.constructor=HTMLElement;HTMLElement.es5Shimmed=!0;Object.setPrototypeOf(HTMLElement,a)}})();function O(a){var b=HTMLElement.call(this)||this;a&&(p(a)&&(a=[a]),document.body.dispatchEvent(new CustomEvent("devsite-load-custom-elements",{bubbles:!0,detail:a})));return b}ha(O,HTMLElement);O.prototype.J=function(){console.warn(this.tagName,"has not implemented update")};O.prototype.F=function(a){a=void 0===a?"":a;return document.createRange().createContextualFragment(a||"")};
O.prototype.I=function(a,b){a&&b?a.parentNode.replaceChild(document.importNode(b,!0),a):!b&&a?a.parentNode.removeChild(a):!a&&b&&this.appendChild(document.importNode(b,!0))};var Qb=!I||9<=Number(L),Rb=!lb&&!I||I&&9<=Number(L)||lb&&K("1.9.1"),Sb=I&&!K("9"),Tb=I||jb||J;function P(a,b){this.a=n(a)?a:0;this.b=n(b)?b:0}g=P.prototype;g.ib=function(){return new P(this.a,this.b)};g.fa=function(a){return a instanceof P&&(this==a?!0:this&&a?this.a==a.a&&this.b==a.b:!1)};g.ceil=function(){this.a=Math.ceil(this.a);this.b=Math.ceil(this.b);return this};g.floor=function(){this.a=Math.floor(this.a);this.b=Math.floor(this.b);return this};g.round=function(){this.a=Math.round(this.a);this.b=Math.round(this.b);return this};
g.kb=function(a,b){a instanceof P?(this.a+=a.a,this.b+=a.b):(this.a+=Number(a),q(b)&&(this.b+=b));return this};g.jb=function(a,b){b=q(b)?b:a;this.a*=a;this.b*=b;return this};g.Hb=function(a,b){a=a*Math.PI/180;b=b||new P(0,0);var c=this.a,d=this.b,e=Math.cos(a);a=Math.sin(a);this.a=(c-b.a)*e-(d-b.b)*a+b.a;this.b=(c-b.a)*a+(d-b.b)*e+b.b};function Ub(a,b){this.width=a;this.height=b}g=Ub.prototype;g.lb=function(){return new Ub(this.width,this.height)};g.Fa=function(){return Math.max(this.width,this.height)};g.Sa=function(){return Math.min(this.width,this.height)};g.Db=function(){return 2*(this.width+this.height)};g.aspectRatio=function(){return this.width/this.height};g.tb=function(){return!(this.width*this.height)};g.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};
g.ja=function(a){return this.width<=a.width&&this.height<=a.height};g.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};g.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};function Vb(a,b){var c=q(void 0)?void 0:b;a.width*=b;a.height*=c;return a}g.Jb=function(a){a=this.aspectRatio()<=a.aspectRatio()?a.width/this.width:a.height/this.height;return Vb(this,a)};
g.Kb=function(a){a=this.aspectRatio()>a.aspectRatio()?a.width/this.width:a.height/this.height;return Vb(this,a)};function Wb(a){return a?new Q(R(a)):ra||(ra=new Q)}function Xb(a,b){var c=b||document,d=null;c.getElementsByClassName?d=c.getElementsByClassName(a)[0]:d=Yb(document,"*",a,b);return d||null}
function Zb(a,b,c,d){a=d||a;var e=b&&"*"!=b?String(b).toUpperCase():"";if(a.querySelectorAll&&a.querySelector&&(e||c))return a.querySelectorAll(e+(c?"."+c:""));if(c&&a.getElementsByClassName){b=a.getElementsByClassName(c);if(e){a={};for(var f=d=0,h;h=b[f];f++)e==h.nodeName&&(a[d++]=h);a.length=d;return a}return b}b=a.getElementsByTagName(e||"*");if(c){a={};for(f=d=0;h=b[f];f++){e=h.className;var k;if(k="function"==typeof e.split)k=0<=sa(e.split(/\s+/),c);k&&(a[d++]=h)}a.length=d;return a}return b}
function Yb(a,b,c,d){var e=d||a,f=b&&"*"!=b?String(b).toUpperCase():"";return e.querySelectorAll&&e.querySelector&&(f||c)?e.querySelector(f+(c?"."+c:"")):Zb(a,b,c,d)[0]||null}function $b(a,b){va(b,function(c,d){c&&"object"==typeof c&&c.s&&(c=c.m());"style"==d?a.style.cssText=c:"class"==d?a.className=c:"for"==d?a.htmlFor=c:ac.hasOwnProperty(d)?a.setAttribute(ac[d],c):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,c):a[d]=c})}
var ac={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};function bc(a){a=a.document;a=cc(a)?a.documentElement:a.body;return new Ub(a.clientWidth,a.clientHeight)}function dc(a){return a.scrollingElement?a.scrollingElement:!J&&cc(a)?a.documentElement:a.body||a.documentElement}
function ec(a){return a.parentWindow||a.defaultView}function gc(a,b,c,d){function e(h){h&&b.appendChild(p(h)?a.createTextNode(h):h)}for(;d<c.length;d++){var f=c[d];u(f)&&!hc(f)?x(ic(f)?ua(f):f,e):e(f)}}function cc(a){return"CSS1Compat"==a.compatMode}function jc(a){for(var b;b=a.firstChild;)a.removeChild(b)}function kc(a){return a&&a.parentNode?a.parentNode.removeChild(a):null}function lc(a,b){for(;a&&1!=a.nodeType;)a=b?a.nextSibling:a.previousSibling;return a}
function hc(a){return v(a)&&0<a.nodeType}function mc(a){return v(a)&&1==a.nodeType}function nc(a,b){if(!a||!b)return!1;if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a}function oc(a,b){var c=a.parentNode;if(c==b)return-1;for(;b.parentNode!=c;)b=b.parentNode;return pc(b,a)}function pc(a,b){for(;b=b.previousSibling;)if(b==a)return-1;return 1}
function R(a){return 9==a.nodeType?a:a.ownerDocument||a.document}function qc(a,b){if("textContent"in a)a.textContent=b;else if(3==a.nodeType)a.data=String(b);else if(a.firstChild&&3==a.firstChild.nodeType){for(;a.lastChild!=a.firstChild;)a.removeChild(a.lastChild);a.firstChild.data=String(b)}else jc(a),a.appendChild(R(a).createTextNode(String(b)))}function rc(a,b,c,d){if(null!=a)for(a=a.firstChild;a;){if(b(a)&&(c.push(a),d)||rc(a,b,c,d))return!0;a=a.nextSibling}return!1}
var sc={SCRIPT:1,STYLE:1,HEAD:1,IFRAME:1,OBJECT:1},tc={IMG:" ",BR:"\n"};function uc(a){return vc(a)&&wc(a)}function vc(a){return I&&!K("9")?(a=a.getAttributeNode("tabindex"),null!=a&&a.specified):a.hasAttribute("tabindex")}function wc(a){a=a.tabIndex;return q(a)&&0<=a&&32768>a}
function xc(a){if(Sb&&null!==a&&"innerText"in a)a=a.innerText.replace(/(\r\n|\r|\n)/g,"\n");else{var b=[];yc(a,b,!0);a=b.join("")}a=a.replace(/ \xAD /g," ").replace(/\xAD/g,"");a=a.replace(/\u200B/g,"");Sb||(a=a.replace(/ +/g," "));" "!=a&&(a=a.replace(/^\s*/,""));return a}
function yc(a,b,c){if(!(a.nodeName in sc))if(3==a.nodeType)c?b.push(String(a.nodeValue).replace(/(\r\n|\r|\n)/g,"")):b.push(a.nodeValue);else if(a.nodeName in tc)b.push(tc[a.nodeName]);else for(a=a.firstChild;a;)yc(a,b,c),a=a.nextSibling}function ic(a){if(a&&"number"==typeof a.length){if(v(a))return"function"==typeof a.item||"string"==typeof a.item;if("function"==r(a))return"function"==typeof a.item}return!1}
function zc(a,b,c,d){if(!b&&!c)return null;var e=b?String(b).toUpperCase():null;return Ac(a,function(f){var h;(h=!e||f.nodeName==e)&&!(h=!c)&&(h=p(f.className))&&(h=0<=sa(f.className.split(/\s+/),c));return h},!0,d)}function Ac(a,b,c,d){a&&!c&&(a=a.parentNode);for(c=0;a&&(null==d||c<=d);){if(b(a))return a;a=a.parentNode;c++}return null}function Q(a){this.a=a||m.document||document}g=Q.prototype;g.wa=Wb;g.Lb=function(a){this.a=a};g.sa=function(){return this.a};
g.O=function(a){return p(a)?this.a.getElementById(a):a};g.Qa=function(a){return p(a)?this.a.getElementById(a):a};g.Z=Q.prototype.O;g.Za=function(a,b){return(b||this.a).getElementsByTagName(String(a))};g.P=function(a,b,c){return Zb(this.a,a,b,c)};g.ya=function(a,b,c){return Yb(this.a,a,b,c)};g.za=function(a,b){var c=(b=b||this.a)||document;return c.querySelectorAll&&c.querySelector?c.querySelectorAll("."+a):Zb(document,"*",a,b)};g.xa=function(a,b){return Xb(a,b||this.a)};
g.Ra=function(a,b){return Xb(a,b||this.a)};g.$=Q.prototype.P;g.Nb=$b;g.Ua=function(a){return bc(a||ec(this.a)||window)};g.ta=function(){var a=ec(this.a),b=a.document;var c=0;if(b){c=b.body;var d=b.documentElement;if(d&&c)if(a=bc(a).height,cc(b)&&d.scrollHeight)c=d.scrollHeight!=a?d.scrollHeight:d.offsetHeight;else{b=d.scrollHeight;var e=d.offsetHeight;d.clientHeight!=e&&(b=c.scrollHeight,e=c.offsetHeight);c=b>a?b>e?b:e:b<e?b:e}else c=0}return c};
g.M=function(a,b,c){var d=this.a,e=arguments,f=String(e[0]),h=e[1];if(!Qb&&h&&(h.name||h.type)){f=["<",f];h.name&&f.push(' name="',Ya(h.name),'"');if(h.type){f.push(' type="',Ya(h.type),'"');var k={};ya(k,h);delete k.type;h=k}f.push(">");f=f.join("")}f=d.createElement(f);h&&(p(h)?f.className=h:t(h)?f.className=h.join(" "):$b(f,h));2<e.length&&gc(d,f,e,2);return f};g.aa=Q.prototype.M;g.Ya=function(a){return this.a.createTextNode(String(a))};
g.ea=function(a,b,c){var d=this.a;c=!!c;for(var e=d.createElement("TABLE"),f=e.appendChild(d.createElement("TBODY")),h=0;h<a;h++){for(var k=d.createElement("TR"),N=0;N<b;N++){var fc=d.createElement("TD");c&&qc(fc,"\u00a0");k.appendChild(fc)}f.appendChild(k)}return e};
g.Ib=function(a){var b=this.a;var c=b.createElement("DIV");I?(a=Ua(Va,a),Xa(c,a),c.removeChild(c.firstChild)):Xa(c,a);if(1==c.childNodes.length)c=c.removeChild(c.firstChild);else{for(b=b.createDocumentFragment();c.firstChild;)b.appendChild(c.firstChild);c=b}return c};g.rb=function(){return cc(this.a)};g.va=function(){return dc(this.a)};
g.ua=function(){var a=this.a,b=dc(a);a=ec(a);return I&&K("10")&&a.pageYOffset!=b.scrollTop?new P(b.scrollLeft,b.scrollTop):new P(a.pageXOffset||b.scrollLeft,a.pageYOffset||b.scrollTop)};g.la=function(a){a=a||this.a;try{var b=a&&a.activeElement;var c=b&&b.nodeName?b:null}catch(d){c=null}return c};g.Wa=function(a,b){a.appendChild(b)};g.Va=function(a,b){gc(R(a),a,arguments,1)};g.Xa=function(a){if(1!=a.nodeType)return!1;switch(a.tagName){case "APPLET":case "AREA":case "BASE":case "BR":case "COL":case "COMMAND":case "EMBED":case "FRAME":case "HR":case "IMG":case "INPUT":case "IFRAME":case "ISINDEX":case "KEYGEN":case "LINK":case "NOFRAMES":case "NOSCRIPT":case "META":case "OBJECT":case "PARAM":case "SCRIPT":case "SOURCE":case "STYLE":case "TRACK":case "WBR":return!1}return!0};
g.Gb=jc;g.pb=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b)};g.ob=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b.nextSibling)};g.nb=function(a,b,c){a.insertBefore(b,a.childNodes[c]||null)};g.$a=kc;g.ab=function(a,b){var c=b.parentNode;c&&c.replaceChild(a,b)};g.ka=function(a){var b,c=a.parentNode;if(c&&11!=c.nodeType){if(a.removeNode)return a.removeNode(!1);for(;b=a.firstChild;)c.insertBefore(b,a);return kc(a)}};
g.qa=function(a){return Rb&&void 0!=a.children?a.children:ta(a.childNodes,function(b){return 1==b.nodeType})};g.Aa=function(a){return n(a.firstElementChild)?a.firstElementChild:lc(a.firstChild,!0)};g.Da=function(a){return n(a.lastElementChild)?a.lastElementChild:lc(a.lastChild,!1)};g.Ga=function(a){return n(a.nextElementSibling)?a.nextElementSibling:lc(a.nextSibling,!0)};g.Oa=function(a){return n(a.previousElementSibling)?a.previousElementSibling:lc(a.previousSibling,!1)};
g.Ha=function(a){if(!a)return null;if(a.firstChild)return a.firstChild;for(;a&&!a.nextSibling;)a=a.parentNode;return a?a.nextSibling:null};g.Pa=function(a){if(!a)return null;if(!a.previousSibling)return a.parentNode;for(a=a.previousSibling;a&&a.lastChild;)a=a.lastChild;return a};g.wb=hc;g.sb=mc;g.yb=function(a){return v(a)&&a.window==a};g.Na=function(a){var b;if(Tb&&!(I&&K("9")&&!K("10")&&m.SVGElement&&a instanceof m.SVGElement)&&(b=a.parentElement))return b;b=a.parentNode;return mc(b)?b:null};
g.contains=nc;
g.da=function(a,b){if(a==b)return 0;if(a.compareDocumentPosition)return a.compareDocumentPosition(b)&2?1:-1;if(I&&!(9<=Number(L))){if(9==a.nodeType)return-1;if(9==b.nodeType)return 1}if("sourceIndex"in a||a.parentNode&&"sourceIndex"in a.parentNode){var c=1==a.nodeType,d=1==b.nodeType;if(c&&d)return a.sourceIndex-b.sourceIndex;var e=a.parentNode,f=b.parentNode;return e==f?pc(a,b):!c&&nc(e,b)?-1*oc(a,b):!d&&nc(f,a)?oc(b,a):(c?a.sourceIndex:e.sourceIndex)-(d?b.sourceIndex:f.sourceIndex)}d=R(a);c=d.createRange();
c.selectNode(a);c.collapse(!0);a=d.createRange();a.selectNode(b);a.collapse(!0);return c.compareBoundaryPoints(m.Range.START_TO_END,a)};g.ga=function(a){var b,c=arguments.length;if(!c)return null;if(1==c)return arguments[0];var d=[],e=Infinity;for(b=0;b<c;b++){for(var f=[],h=arguments[b];h;)f.unshift(h),h=h.parentNode;d.push(f);e=Math.min(e,f.length)}f=null;for(b=0;b<e;b++){h=d[0][b];for(var k=1;k<c;k++)if(h!=d[k][b])return f;f=h}return f};g.Ma=R;g.Ba=function(a){return a.contentDocument||a.contentWindow.document};
g.Ca=function(a){try{var b;if(!(b=a.contentWindow)){if(a.contentDocument){var c=a.contentDocument;var d=c?ec(c):window}else d=null;b=d}return b}catch(e){}return null};g.Ob=qc;g.La=function(a){if("outerHTML"in a)return a.outerHTML;var b=R(a).createElement("DIV");b.appendChild(a.cloneNode(!0));return b.innerHTML};g.ha=function(a,b){var c=[];return rc(a,b,c,!0)?c[0]:void 0};g.ia=function(a,b){var c=[];rc(a,b,c,!1);return c};g.vb=uc;g.Mb=function(a,b){b?a.tabIndex=0:(a.tabIndex=-1,a.removeAttribute("tabIndex"))};
g.ub=function(a){var b;if((b="A"==a.tagName&&a.hasAttribute("href")||"INPUT"==a.tagName||"TEXTAREA"==a.tagName||"SELECT"==a.tagName||"BUTTON"==a.tagName?!a.disabled&&(!vc(a)||wc(a)):uc(a))&&I){var c;"function"!=r(a.getBoundingClientRect)||I&&null==a.parentElement?c={height:a.offsetHeight,width:a.offsetWidth}:c=a.getBoundingClientRect();a=null!=c&&0<c.height&&0<c.width}else a=b;return a};g.Ta=xc;g.Ja=function(a){return xc(a).length};
g.Ka=function(a,b){b=b||R(a).body;for(var c=[];a&&a!=b;){for(var d=a;d=d.previousSibling;)c.unshift(xc(d));a=a.parentNode}return c.join("").replace(/^[\s\xa0]+/,"").replace(/ +/g," ").length};
g.Ia=function(a,b,c){a=[a];for(var d=0,e=null;0<a.length&&d<b;)if(e=a.pop(),!(e.nodeName in sc))if(3==e.nodeType){var f=e.nodeValue.replace(/(\r\n|\r|\n)/g,"").replace(/ +/g," ");d+=f.length}else if(e.nodeName in tc)d+=tc[e.nodeName].length;else for(f=e.childNodes.length-1;0<=f;f--)a.push(e.childNodes[f]);v(c)&&(c.Fb=e?e.nodeValue.length+b-d-1:0,c.node=e);return e};g.xb=ic;g.oa=zc;g.na=function(a,b,c){return zc(a,null,b,c)};g.ma=Ac;g.pa=function(a){return a.getContext("2d")};function Bc(){this.g=this.g;this.b=this.b}g=Bc.prototype;g.g=!1;g.T=function(){return this.g};g.ra=Bc.prototype.T;g.C=function(){this.g||(this.g=!0,this.A())};g.Eb=function(a){a=qa(Cc,a);this.g?n(void 0)?a.call(void 0):a():(this.b||(this.b=[]),this.b.push(n(void 0)?pa(a,void 0):a))};g.A=function(){if(this.b)for(;this.b.length;)this.b.shift()()};function Cc(a){a&&"function"==typeof a.C&&a.C()};var Dc=!I||9<=Number(L),Ec=!I||9<=Number(L),Fc=I&&!K("9"),Gc=function(){if(!m.addEventListener||!Object.defineProperty)return!1;var a=!1,b=Object.defineProperty({},"passive",{get:function(){a=!0}});try{m.addEventListener("test",ma,b),m.removeEventListener("test",ma,b)}catch(c){}return a}();function Hc(a,b){this.type=a;this.b=this.target=b;this.J=this.h=!1;this.Y=!0}Hc.prototype.stopPropagation=function(){this.h=!0};Hc.prototype.c=function(){this.J=!0;this.Y=!1};var Ic;Ic=J?"webkitTransitionEnd":jb?"otransitionend":"transitionend";function S(a,b){Hc.call(this,a?a.type:"");this.relatedTarget=this.b=this.target=null;this.button=this.screenY=this.screenX=this.clientY=this.clientX=this.H=this.G=0;this.key="";this.o=this.F=0;this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.I=null;this.V=!1;this.pointerId=0;this.pointerType="";this.a=null;if(a){var c=this.type=a.type,d=a.changedTouches&&a.changedTouches.length?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.b=b;if(b=a.relatedTarget){if(lb){a:{try{gb(b.nodeName);
var e=!0;break a}catch(f){}e=!1}e||(b=null)}}else"mouseover"==c?b=a.fromElement:"mouseout"==c&&(b=a.toElement);this.relatedTarget=b;d?(this.clientX=void 0!==d.clientX?d.clientX:d.pageX,this.clientY=void 0!==d.clientY?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=d.screenY||0):(this.G=J||void 0!==a.offsetX?a.offsetX:a.layerX,this.H=J||void 0!==a.offsetY?a.offsetY:a.layerY,this.clientX=void 0!==a.clientX?a.clientX:a.pageX,this.clientY=void 0!==a.clientY?a.clientY:a.pageY,this.screenX=a.screenX||
0,this.screenY=a.screenY||0);this.button=a.button;this.F=a.keyCode||0;this.key=a.key||"";this.o=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.V=mb?a.metaKey:a.ctrlKey;this.pointerId=a.pointerId||0;this.pointerType=p(a.pointerType)?a.pointerType:Jc[a.pointerType]||"";this.I=a.state;this.a=a;a.defaultPrevented&&this.c()}}w(S,Hc);var Kc=[1,4,2],Jc={2:"touch",3:"pen",4:"mouse"};
S.prototype.Qb=function(){return(Dc?0==this.a.button:"click"==this.type?!0:!!(this.a.button&Kc[0]))&&!(J&&mb&&this.ctrlKey)};S.prototype.stopPropagation=function(){S.u.stopPropagation.call(this);this.a.stopPropagation?this.a.stopPropagation():this.a.cancelBubble=!0};S.prototype.c=function(){S.u.c.call(this);var a=this.a;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,Fc)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};var Lc="closure_listenable_"+(1E6*Math.random()|0),Mc=0;function Nc(a,b,c,d,e){this.listener=a;this.a=null;this.src=b;this.type=c;this.capture=!!d;this.b=e;this.key=++Mc;this.l=this.v=!1}function Oc(a){a.l=!0;a.listener=null;a.a=null;a.src=null;a.b=null};function Pc(a){this.src=a;this.a={};this.b=0}g=Pc.prototype;g.eb=function(){var a=0,b;for(b in this.a)a+=this.a[b].length;return a};g.add=function(a,b,c,d,e){var f=a.toString();a=this.a[f];a||(a=this.a[f]=[],this.b++);var h=Qc(a,b,d,e);-1<h?(b=a[h],c||(b.v=!1)):(b=new Nc(b,this.src,f,!!d,e),b.v=c,a.push(b));return b};
g.gb=function(a,b,c,d){a=a.toString();if(!(a in this.a))return!1;var e=this.a[a];b=Qc(e,b,c,d);return-1<b?(Oc(e[b]),Array.prototype.splice.call(e,b,1),0==e.length&&(delete this.a[a],this.b--),!0):!1};g.hb=function(a){a=a&&a.toString();var b=0,c;for(c in this.a)if(!a||c==a){for(var d=this.a[c],e=0;e<d.length;e++)++b,Oc(d[e]);delete this.a[c];this.b--}return b};g.Ea=function(a,b){a=this.a[a.toString()];var c=[];if(a)for(var d=0;d<a.length;++d){var e=a[d];e.capture==b&&c.push(e)}return c};
g.fb=function(a,b){var c=n(a),d=c?a.toString():"",e=n(b);return wa(this.a,function(f){for(var h=0;h<f.length;++h)if(!(c&&f[h].type!=d||e&&f[h].capture!=b))return!0;return!1})};function Qc(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.l&&f.listener==b&&f.capture==!!c&&f.b==d)return e}return-1};var Rc="closure_lm_"+(1E6*Math.random()|0),Sc={},Tc=0;function Uc(a,b,c,d,e){if(d&&d.once)return T(a,b,c,d,e);if(t(b)){for(var f=0;f<b.length;f++)Uc(a,b[f],c,d,e);return null}c=Vc(c);return a&&a[Lc]?U(a,b,c,v(d)?!!d.capture:!!d,e):Wc(a,b,c,!1,d,e)}
function Wc(a,b,c,d,e,f){if(!b)throw Error("Invalid event type");var h=v(e)?!!e.capture:!!e,k=Xc(a);k||(a[Rc]=k=new Pc(a));c=k.add(b,c,d,h,f);if(c.a)return c;d=Yc();c.a=d;d.src=a;d.listener=c;if(a.addEventListener)Gc||(e=h),void 0===e&&(e=!1),a.addEventListener(b.toString(),d,e);else if(a.attachEvent)a.attachEvent(Zc(b.toString()),d);else if(a.addListener&&a.removeListener)a.addListener(d);else throw Error("addEventListener and attachEvent are unavailable.");Tc++;return c}
function Yc(){var a=$c,b=Ec?function(c){return a.call(b.src,b.listener,c)}:function(c){c=a.call(b.src,b.listener,c);if(!c)return c};return b}function T(a,b,c,d,e){if(t(b)){for(var f=0;f<b.length;f++)T(a,b[f],c,d,e);return null}c=Vc(c);return a&&a[Lc]?a.H(b,c,v(d)?!!d.capture:!!d,e):Wc(a,b,c,!0,d,e)}
function ad(a){if(!q(a)&&a&&!a.l){var b=a.src;if(b&&b[Lc])b.a(a);else{var c=a.type,d=a.a;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent?b.detachEvent(Zc(c),d):b.addListener&&b.removeListener&&b.removeListener(d);Tc--;if(c=Xc(b)){d=a.type;if(d in c.a){var e=c.a[d],f=sa(e,a),h;(h=0<=f)&&Array.prototype.splice.call(e,f,1);h&&(Oc(a),0==c.a[d].length&&(delete c.a[d],c.b--))}0==c.b&&(c.src=null,b[Rc]=null)}else Oc(a)}}}function Zc(a){return a in Sc?Sc[a]:Sc[a]="on"+a}
function bd(a,b,c,d){var e=!0;if(a=Xc(a))if(b=a.a[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.capture==c&&!f.l&&(f=cd(f,d),e=e&&!1!==f)}return e}function cd(a,b){var c=a.listener,d=a.b||a.src;a.v&&ad(a);return c.call(d,b)}
function $c(a,b){if(a.l)return!0;if(!Ec){if(!b)a:{b=["window","event"];for(var c=m,d=0;d<b.length;d++)if(c=c[b[d]],null==c){b=null;break a}b=c}d=b;b=new S(d,this);c=!0;if(!(0>d.keyCode||void 0!=d.returnValue)){a:{var e=!1;if(0==d.keyCode)try{d.keyCode=-1;break a}catch(h){e=!0}if(e||void 0==d.returnValue)d.returnValue=!0}d=[];for(e=b.b;e;e=e.parentNode)d.push(e);a=a.type;for(e=d.length-1;!b.h&&0<=e;e--){b.b=d[e];var f=bd(d[e],a,!0,b);c=c&&f}for(e=0;!b.h&&e<d.length;e++)b.b=d[e],f=bd(d[e],a,!1,b),c=
c&&f}return c}return cd(a,new S(b,this))}function Xc(a){a=a[Rc];return a instanceof Pc?a:null}var dd="__closure_events_fn_"+(1E9*Math.random()>>>0);function Vc(a){if("function"==r(a))return a;a[dd]||(a[dd]=function(b){return a.handleEvent(b)});return a[dd]};function V(a){Bc.call(this);this.c=a;this.a={}}w(V,Bc);var ed=[];function fd(a,b,c){U(a,b,"click",c,void 0)}g=V.prototype;g.Ab=function(a,b,c,d,e){return U(this,a,b,c,d,e)};function U(a,b,c,d,e,f){t(c)||(c&&(ed[0]=c.toString()),c=ed);for(var h=0;h<c.length;h++){var k=Uc(b,c[h],d||a.handleEvent,e||!1,f||a.c||a);if(!k)break;a.a[k.key]=k}return a}g.cb=function(a,b,c,d){return gd(this,a,b,c,d)};g.zb=function(a,b,c,d,e){return gd(this,a,b,c,d,e)};
function gd(a,b,c,d,e,f){if(t(c))for(var h=0;h<c.length;h++)gd(a,b,c[h],d,e,f);else{b=T(b,c,d||a.handleEvent,e,f||a.c||a);if(!b)return a;a.a[b.key]=b}return a}g.Bb=function(a,b,c,d){U(b,a,c,d,this.c||this);return this};g.Cb=function(a,b,c,d,e){U(b,a,c,d,e||this.c||this);return this};g.bb=function(){var a=0,b;for(b in this.a)Object.prototype.hasOwnProperty.call(this.a,b)&&a++;return a};
function hd(a,b,c,d,e,f){if(t(c))for(var h=0;h<c.length;h++)hd(a,b,c[h],d,e,f);else d=d||a.handleEvent,e=v(e)?!!e.capture:!!e,f=f||a.c||a,d=Vc(d),e=!!e,b&&b[Lc]?c=b.G(c,d,e,f):b?(b=Xc(b))?(c=b.a[c.toString()],b=-1,c&&(b=Qc(c,d,e,f)),c=-1<b?c[b]:null):c=null:c=null,c&&(ad(c),delete a.a[c.key])}g.Pb=function(a,b,c,d,e){hd(b,a,c,d,e||this.c||this,this);return this};function id(a){va(a.a,function(b,c){this.a.hasOwnProperty(c)&&ad(b)},a);a.a={}}g.A=function(){V.u.A.call(this);id(this)};
g.handleEvent=function(){throw Error("EventHandler.handleEvent not implemented");};function W(a,b){b=a(b||jd,void 0,void 0);a=Wb().a.createElement("DIV");if(v(b))if(b instanceof H)if(b.f===eb)b=D(b.toString());else{if(b.f!==bb)throw Error("Sanitized content was not of kind TEXT or HTML.");b=E(b.toString(),b.w||null)}else b=D("zSoyz");else b=D(String(b));Xa(a,b);1==a.childNodes.length&&(b=a.firstChild,1==b.nodeType&&(a=b));return a}var jd={};function kd(){};function ld(){}w(ld,kd);ld.prototype.N=function(){var a=0;$a(this.j(!0),function(){a++});return a};ld.prototype.R=function(){var a=ab(this.j(!0)),b=this;x(a,function(c){b.a.removeItem(c)})};function md(a){this.a=a}w(md,ld);g=md.prototype;g.qb=function(){if(!this.a)return!1;try{return this.a.setItem("__sak","1"),this.a.removeItem("__sak"),!0}catch(a){return!1}};g.set=function(a,b){try{this.a.setItem(a,b)}catch(c){if(0==this.a.length)throw"Storage mechanism: Storage disabled";throw"Storage mechanism: Quota exceeded";}};g.get=function(a){a=this.a.getItem(a);if(!p(a)&&null!==a)throw"Storage mechanism: Invalid value was encountered";return a};g.N=function(){return this.a.length};
g.j=function(a){var b=0,c=this.a,d=new G;d.a=function(){if(b>=c.length)throw F;var e=c.key(b++);if(a)return e;e=c.getItem(e);if(!p(e))throw"Storage mechanism: Invalid value was encountered";return e};return d};g.R=function(){this.a.clear()};g.key=function(a){return this.a.key(a)};function nd(){var a=null;try{a=window.localStorage||null}catch(b){}this.a=a}w(nd,md);function X(){var a=O.call(this)||this;a.h=-1;a.o=new V(a);a.b=new nd;a.a=[];return a}ha(X,O);g=X.prototype;g.connectedCallback=function(){U(this.o,document.body,"devsite-show-custom-snackbar-msg",this.S,void 0)};g.disconnectedCallback=function(){id(this.o)};g.S=function(a){var b=this;this.setAttribute("type","custom");if(a=a.a.detail){var c=!!a.showClose,d=W(Ob,{message:a.msg,W:c});c&&T(d.querySelector(".devsite-snackbar-action"),"click",function(){Y(b,d)});Z(this,d,!c)}};
g.attributeChangedCallback=function(a,b,c){if("type"==a){switch(b){case "loading":Y(this,this.querySelector('*[type^="loading"]'));break;case "refresh":Y(this,this.querySelector('*[type^="refresh"]'));break;case "error":Y(this,this.querySelector('*[type^="error"]'));break;case "copied-to-clipboard":Y(this,this.querySelector('*[type^="copied-to-clipboard"]'));break;case "cookie-notification":od(this);break;case "support-attachment-error":pd(this);break;case "custom":pd(this)}null!=b&&b.startsWith("notification-")&&
qd(this);c&&(c.includes(",")&&(this.a=c.split(","),c=this.a.shift()),rd(this,c))}};function rd(a,b){switch(b){case "loading":if(!a.querySelector('*[type^="loading"]')){var c=W(Hb);Z(a,c)}break;case "refresh":sd(a);break;case "error":td(a);break;case "copied-to-clipboard":c=W(Kb);Z(a,c,!0);break;case "cookie-notification":ud(a);break;case "support-attachment-error":vd(a)}b.startsWith("notification-")&&wd(a,b)}g.mb=function(){Y(this,this.querySelector('*[type^="custom"]'))};
function Z(a,b,c){c=void 0===c?!1:c;a.appendChild(b);window.requestAnimationFrame(function(){xd(a,b,c)})}function xd(a,b,c){c=void 0===c?!1:c;window.clearTimeout(a.h);a.c?Y(a,a.c,b,c):(a.c=b,window.requestAnimationFrame(function(){b.setAttribute("show","")}),c&&(a.h=window.setTimeout(function(){a.removeAttribute("type");Y(a,b)},5E3)))}function sd(a){var b=W(Ib);Uc(b.querySelector(".devsite-snackbar-action"),"click",function(){window.location.reload()});Z(a,b)}
function td(a){var b=W(Jb);Uc(b.querySelector(".devsite-snackbar-action"),"click",function(){window.location.reload()});Z(a,b)}function Y(a,b,c,d){c=void 0===c?null:c;d=void 0===d?!1:d;b&&(T(b,Ic,function(){kc(b);a.c=null;if(c)xd(a,c,d);else{var e=a.a.length?a.a.shift():null;null!==e&&rd(a,e)}}),b.removeAttribute("show"))}
function ud(a){if(a.b.get("devsite-eu-cookie")){var b=a.a.length?a.a.shift():null;null!==b&&rd(a,b)}else a.hasAttribute("data-cookie-policy")?(b=a.getAttribute("data-cookie-policy"),b=W(Lb,{L:b})):b=W(Lb),T(b.querySelector(".devsite-snackbar-action"),"click",function(){a.b.set("devsite-eu-cookie","1");od(a)}),Z(a,b)}function od(a){Y(a,a.querySelector('*[type^="cookie-notification"]'))}function vd(a){var b=W(Mb);Z(a,b);T(b.querySelector(".devsite-snackbar-action"),"click",function(){pd(a)})}
function pd(a){Y(a,a.querySelector('*[type^="support-attachment-error"]'))}
function wd(a,b){var c=a.getAttribute(b+"-message"),d=a.getAttribute(b+"-link"),e=a.getAttribute(b+"-link-txt"),f=a.hasAttribute(b+"-store-key");if(c&&d){var h="devsite-notification"+d;if(!f||!a.b.get(h)){b=W(Nb,{X:b,message:c,link:d,U:e});Z(a,b);var k=new V(b);fd(k,b,function(N){N.stopPropagation();if(N.target.classList.contains("devsite-snackbar-link")||N.target.classList.contains("devsite-snackbar-action"))f&&a.b.set(h,"1"),qd(a),id(k)})}}}
function qd(a){Y(a,a.querySelector('*[type^="notification"]'))}ia.Object.defineProperties(X,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return["type"]}}});X.prototype.attributeChangedCallback=X.prototype.attributeChangedCallback;X.prototype.disconnectedCallback=X.prototype.disconnectedCallback;X.prototype.connectedCallback=X.prototype.connectedCallback;try{window.customElements.define("devsite-snackbar",X)}catch(a){console.warn("devsite.app.customElement.DevsiteSnackBar",a)};}).call(this);
