(function(){'use strict';var g;function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function ba(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:aa(a)}}function ca(a){for(var b,c=[];!(b=a.next()).done;)c.push(b.value);return c}var da="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},l;
if("function"==typeof Object.setPrototypeOf)l=Object.setPrototypeOf;else{var ea;a:{var fa={F:!0},ha={};try{ha.__proto__=fa;ea=ha.F;break a}catch(a){}ea=!1}l=ea?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var ia=l;
function ja(a,b){a.prototype=da(b.prototype);a.prototype.constructor=a;if(ia)ia(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.i=b.prototype}var ka="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this,la="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};
function ma(a,b){if(b){var c=ka;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&la(c,a,{configurable:!0,writable:!0,value:b})}}ma("Object.setPrototypeOf",function(a){return a||ia});
var na=function(){function a(){function c(){}new c;Reflect.construct(c,[],function(){});return new c instanceof c}if("undefined"!=typeof Reflect&&Reflect.construct){if(a())return Reflect.construct;var b=Reflect.construct;return function(c,d,e){c=b(c,d);e&&Reflect.setPrototypeOf(c,e.prototype);return c}}return function(c,d,e){void 0===e&&(e=c);e=da(e.prototype||Object.prototype);return Function.prototype.apply.call(c,e,d)||e}}();ma("Reflect.construct",function(){return na});
ma("Array.from",function(a){return a?a:function(b,c,d){c=null!=c?c:function(k){return k};var e=[],f="undefined"!=typeof Symbol&&Symbol.iterator&&b[Symbol.iterator];if("function"==typeof f){b=f.call(b);for(var h=0;!(f=b.next()).done;)e.push(c.call(d,f.value,h++))}else for(f=b.length,h=0;h<f;h++)e.push(c.call(d,b[h],h));return e}});var m=this||self;function n(a){return void 0!==a}function p(a){return"string"==typeof a}function q(a){return"number"==typeof a}function oa(){}
function r(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function t(a){return"array"==r(a)}function pa(a){var b=r(a);return"array"==b||"object"==b&&"number"==typeof a.length}function u(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}function qa(a,b,c){return a.call.apply(a.bind,arguments)}
function ra(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,d);return a.apply(b,e)}}return function(){return a.apply(b,arguments)}}function v(a,b,c){Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?v=qa:v=ra;return v.apply(null,arguments)}
function sa(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var d=c.slice();d.push.apply(d,arguments);return a.apply(this,d)}}function ta(a,b){function c(){}c.prototype=b.prototype;a.i=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.U=function(d,e,f){for(var h=Array(arguments.length-2),k=2;k<arguments.length;k++)h[k-2]=arguments[k];return b.prototype[e].apply(d,h)}};var ua;var va=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if(p(a))return p(b)&&1==b.length?a.indexOf(b,0):-1;for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},wa=Array.prototype.forEach?function(a,b){Array.prototype.forEach.call(a,b,void 0)}:function(a,b){for(var c=a.length,d=p(a)?a.split(""):a,e=0;e<c;e++)e in d&&b.call(void 0,d[e],e,a)},xa=Array.prototype.filter?function(a,b){return Array.prototype.filter.call(a,b,void 0)}:function(a,
b){for(var c=a.length,d=[],e=0,f=p(a)?a.split(""):a,h=0;h<c;h++)if(h in f){var k=f[h];b.call(void 0,k,h,a)&&(d[e++]=k)}return d};function ya(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};var za=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]};
function Aa(a,b){if(b)a=a.replace(Ba,"&amp;").replace(Ca,"&lt;").replace(Da,"&gt;").replace(Ea,"&quot;").replace(Fa,"&#39;").replace(Ga,"&#0;");else{if(!Ha.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(Ba,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(Ca,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(Da,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(Ea,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(Fa,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(Ga,"&#0;"))}return a}
var Ba=/&/g,Ca=/</g,Da=/>/g,Ea=/"/g,Fa=/'/g,Ga=/\x00/g,Ha=/[\x00&<>"']/;function Ia(a,b){return a<b?-1:a>b?1:0};var w;a:{var Ja=m.navigator;if(Ja){var Ka=Ja.userAgent;if(Ka){w=Ka;break a}}w=""};function La(a,b,c){for(var d in a)b.call(c,a[d],d,a)}function Ma(a,b){for(var c in a)if(b.call(void 0,a[c],c,a))return!0;return!1}var Na="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function Oa(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<Na.length;f++)c=Na[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};function x(){this.b="";this.c=Pa}x.prototype.u=!0;x.prototype.o=function(){return this.b.toString()};x.prototype.B=!0;x.prototype.a=function(){return 1};var Pa={};function Qa(a){var b=new x;b.b=a;return b}Qa("about:blank");function y(){this.b="";this.g=Ra;this.c=null}y.prototype.B=!0;y.prototype.a=function(){return this.c};y.prototype.u=!0;y.prototype.o=function(){return this.b.toString()};function z(a){return a instanceof y&&a.constructor===y&&a.g===Ra?a.b:"type_error:SafeHtml"}function A(a){if(a instanceof y)return a;var b="object"==typeof a,c=null;b&&a.B&&(c=a.a());a=Aa(b&&a.u?a.o():String(a));return B(a,c)}
function Sa(a){function b(f){t(f)?wa(f,b):(f=A(f),e.push(z(f).toString()),f=f.a(),0==d?d=f:0!=f&&d!=f&&(d=null))}var c=A(Ta),d=c.a(),e=[];wa(a,b);return B(e.join(z(c).toString()),d)}function Ua(a){return Sa(Array.prototype.slice.call(arguments))}var Ra={};function B(a,b){var c=new y;c.b=a;c.c=b;return c}B("<!DOCTYPE html>",0);var Ta=B("",0),Va=B("<br>",0);var Wa=function(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}}(function(){var a=document.createElement("div"),b=document.createElement("div");b.appendChild(document.createElement("div"));a.appendChild(b);b=a.firstChild.firstChild;a.innerHTML=z(Ta);return!b.parentElement});function Xa(a,b){if(Wa())for(;a.lastChild;)a.removeChild(a.lastChild);a.innerHTML=z(b)};function Ya(a){return a=Aa(a,void 0)};function Za(a){Za[" "](a);return a}Za[" "]=oa;function $a(a,b){var c=ab;return Object.prototype.hasOwnProperty.call(c,a)?c[a]:c[a]=b(a)};var bb=-1!=w.indexOf("Opera"),C=-1!=w.indexOf("Trident")||-1!=w.indexOf("MSIE"),cb=-1!=w.indexOf("Edge"),D=-1!=w.indexOf("Gecko")&&!(-1!=w.toLowerCase().indexOf("webkit")&&-1==w.indexOf("Edge"))&&!(-1!=w.indexOf("Trident")||-1!=w.indexOf("MSIE"))&&-1==w.indexOf("Edge"),E=-1!=w.toLowerCase().indexOf("webkit")&&-1==w.indexOf("Edge"),db=-1!=w.indexOf("Macintosh");function eb(){var a=m.document;return a?a.documentMode:void 0}var fb;
a:{var gb="",hb=function(){var a=w;if(D)return/rv:([^\);]+)(\)|;)/.exec(a);if(cb)return/Edge\/([\d\.]+)/.exec(a);if(C)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(E)return/WebKit\/(\S+)/.exec(a);if(bb)return/(?:Version)[ \/]?(\S+)/.exec(a)}();hb&&(gb=hb?hb[1]:"");if(C){var ib=eb();if(null!=ib&&ib>parseFloat(gb)){fb=String(ib);break a}}fb=gb}var jb=fb,ab={};
function F(a){return $a(a,function(){for(var b=0,c=za(String(jb)).split("."),d=za(String(a)).split("."),e=Math.max(c.length,d.length),f=0;0==b&&f<e;f++){var h=c[f]||"",k=d[f]||"";do{h=/(\d*)(\D*)(.*)/.exec(h)||["","","",""];k=/(\d*)(\D*)(.*)/.exec(k)||["","","",""];if(0==h[0].length&&0==k[0].length)break;b=Ia(0==h[1].length?0:parseInt(h[1],10),0==k[1].length?0:parseInt(k[1],10))||Ia(0==h[2].length,0==k[2].length)||Ia(h[2],k[2]);h=h[3];k=k[3]}while(0==b)}return 0<=b})}var G;var kb=m.document;
G=kb&&C?eb()||("CSS1Compat"==kb.compatMode?parseInt(jb,10):5):void 0;var lb={},mb={},nb={};function H(){throw Error("Do not instantiate directly");}H.prototype.v=null;H.prototype.b=function(){return this.a};H.prototype.toString=function(){return this.a};H.prototype.c=function(){if(this.l!==mb)throw Error("Sanitized content was not of kind URI.");return Qa(this.toString())};function ob(){H.call(this)}ta(ob,H);ob.prototype.l=lb;var pb=function(a){function b(c){this.a=c}b.prototype=a.prototype;return function(c,d){c=new b(String(c));void 0!==d&&(c.v=d);return c}}(ob),qb={"\x00":"&#0;","\t":"&#9;","\n":"&#10;","\x0B":"&#11;","\f":"&#12;","\r":"&#13;"," ":"&#32;",'"':"&quot;","&":"&amp;","'":"&#39;","-":"&#45;","/":"&#47;","<":"&lt;","=":"&#61;",">":"&gt;","`":"&#96;","\u0085":"&#133;","\u00a0":"&#160;","\u2028":"&#8232;","\u2029":"&#8233;"};function rb(a){return qb[a]}var sb=/[\x00\x22\x27\x3c\x3e]/g;function tb(){var a='<button role="button" class="devsite-heading-link button-flat material-icons" title="'+"Copy link to this section".replace(sb,rb);return pb(a+'"></button>')}function ub(){var a='<a href="#top_of_page" class="devsite-back-to-top-link material-icons" title="'+"Back to top".replace(sb,rb);return pb(a+'"></a>')};var vb=!C||9<=Number(G),wb=!D&&!C||C&&9<=Number(G)||D&&F("1.9.1"),xb=C&&!F("9"),yb=C||bb||E;function I(a,b){this.x=n(a)?a:0;this.a=n(b)?b:0}g=I.prototype;g.Za=function(){return new I(this.x,this.a)};g.X=function(a){return a instanceof I&&(this==a?!0:this&&a?this.x==a.x&&this.a==a.a:!1)};g.ceil=function(){this.x=Math.ceil(this.x);this.a=Math.ceil(this.a);return this};g.floor=function(){this.x=Math.floor(this.x);this.a=Math.floor(this.a);return this};g.round=function(){this.x=Math.round(this.x);this.a=Math.round(this.a);return this};
g.ab=function(a,b){a instanceof I?(this.x+=a.x,this.a+=a.a):(this.x+=Number(a),q(b)&&(this.a+=b));return this};g.$a=function(a,b){b=q(b)?b:a;this.x*=a;this.a*=b;return this};g.wb=function(a,b){a=a*Math.PI/180;b=b||new I(0,0);var c=this.x,d=this.a,e=Math.cos(a);a=Math.sin(a);this.x=(c-b.x)*e-(d-b.a)*a+b.x;this.a=(c-b.x)*a+(d-b.a)*e+b.a};function zb(a,b){this.width=a;this.height=b}g=zb.prototype;g.bb=function(){return new zb(this.width,this.height)};g.wa=function(){return Math.max(this.width,this.height)};g.Ja=function(){return Math.min(this.width,this.height)};g.sb=function(){return 2*(this.width+this.height)};g.aspectRatio=function(){return this.width/this.height};g.ib=function(){return!(this.width*this.height)};g.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};
g.aa=function(a){return this.width<=a.width&&this.height<=a.height};g.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};g.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};function Ab(a,b){var c=q(void 0)?void 0:b;a.width*=b;a.height*=c;return a}g.yb=function(a){a=this.aspectRatio()<=a.aspectRatio()?a.width/this.width:a.height/this.height;return Ab(this,a)};
g.zb=function(a){a=this.aspectRatio()>a.aspectRatio()?a.width/this.width:a.height/this.height;return Ab(this,a)};function Bb(a){return a?new J(K(a)):ua||(ua=new J)}function Cb(a,b){var c=b||document,d=null;c.getElementsByClassName?d=c.getElementsByClassName(a)[0]:d=Db(document,"*",a,b);return d||null}
function Eb(a,b,c,d){a=d||a;var e=b&&"*"!=b?String(b).toUpperCase():"";if(a.querySelectorAll&&a.querySelector&&(e||c))return a.querySelectorAll(e+(c?"."+c:""));if(c&&a.getElementsByClassName){b=a.getElementsByClassName(c);if(e){a={};for(var f=d=0,h;h=b[f];f++)e==h.nodeName&&(a[d++]=h);a.length=d;return a}return b}b=a.getElementsByTagName(e||"*");if(c){a={};for(f=d=0;h=b[f];f++){e=h.className;var k;if(k="function"==typeof e.split)k=0<=va(e.split(/\s+/),c);k&&(a[d++]=h)}a.length=d;return a}return b}
function Db(a,b,c,d){var e=d||a,f=b&&"*"!=b?String(b).toUpperCase():"";return e.querySelectorAll&&e.querySelector&&(f||c)?e.querySelector(f+(c?"."+c:"")):Eb(a,b,c,d)[0]||null}function Fb(a,b){La(b,function(c,d){c&&"object"==typeof c&&c.u&&(c=c.o());"style"==d?a.style.cssText=c:"class"==d?a.className=c:"for"==d?a.htmlFor=c:Ib.hasOwnProperty(d)?a.setAttribute(Ib[d],c):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,c):a[d]=c})}
var Ib={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};function Jb(a){a=a.document;a=L(a)?a.documentElement:a.body;return new zb(a.clientWidth,a.clientHeight)}function Kb(a){return a.scrollingElement?a.scrollingElement:!E&&L(a)?a.documentElement:a.body||a.documentElement}
function M(a){return a.parentWindow||a.defaultView}function Lb(a,b,c,d){function e(h){h&&b.appendChild(p(h)?a.createTextNode(h):h)}for(;d<c.length;d++){var f=c[d];pa(f)&&!Mb(f)?wa(Nb(f)?ya(f):f,e):e(f)}}function L(a){return"CSS1Compat"==a.compatMode}function Ob(a){for(var b;b=a.firstChild;)a.removeChild(b)}function N(a){return a&&a.parentNode?a.parentNode.removeChild(a):null}function O(a,b){for(;a&&1!=a.nodeType;)a=b?a.nextSibling:a.previousSibling;return a}
function Mb(a){return u(a)&&0<a.nodeType}function Pb(a){return u(a)&&1==a.nodeType}function Qb(a,b){if(!a||!b)return!1;if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a}function Rb(a,b){var c=a.parentNode;if(c==b)return-1;for(;b.parentNode!=c;)b=b.parentNode;return Sb(b,a)}function Sb(a,b){for(;b=b.previousSibling;)if(b==a)return-1;return 1}
function K(a){return 9==a.nodeType?a:a.ownerDocument||a.document}function Tb(a,b){if("textContent"in a)a.textContent=b;else if(3==a.nodeType)a.data=String(b);else if(a.firstChild&&3==a.firstChild.nodeType){for(;a.lastChild!=a.firstChild;)a.removeChild(a.lastChild);a.firstChild.data=String(b)}else Ob(a),a.appendChild(K(a).createTextNode(String(b)))}function Ub(a,b,c,d){if(null!=a)for(a=a.firstChild;a;){if(b(a)&&(c.push(a),d)||Ub(a,b,c,d))return!0;a=a.nextSibling}return!1}
var Vb={SCRIPT:1,STYLE:1,HEAD:1,IFRAME:1,OBJECT:1},P={IMG:" ",BR:"\n"};function Wb(a){return Xb(a)&&Yb(a)}function Xb(a){return C&&!F("9")?(a=a.getAttributeNode("tabindex"),null!=a&&a.specified):a.hasAttribute("tabindex")}function Yb(a){a=a.tabIndex;return q(a)&&0<=a&&32768>a}
function Zb(a){if(xb&&null!==a&&"innerText"in a)a=a.innerText.replace(/(\r\n|\r|\n)/g,"\n");else{var b=[];$b(a,b,!0);a=b.join("")}a=a.replace(/ \xAD /g," ").replace(/\xAD/g,"");a=a.replace(/\u200B/g,"");xb||(a=a.replace(/ +/g," "));" "!=a&&(a=a.replace(/^\s*/,""));return a}
function $b(a,b,c){if(!(a.nodeName in Vb))if(3==a.nodeType)c?b.push(String(a.nodeValue).replace(/(\r\n|\r|\n)/g,"")):b.push(a.nodeValue);else if(a.nodeName in P)b.push(P[a.nodeName]);else for(a=a.firstChild;a;)$b(a,b,c),a=a.nextSibling}function Nb(a){if(a&&"number"==typeof a.length){if(u(a))return"function"==typeof a.item||"string"==typeof a.item;if("function"==r(a))return"function"==typeof a.item}return!1}
function ac(a,b,c,d){if(!b&&!c)return null;var e=b?String(b).toUpperCase():null;return bc(a,function(f){var h;(h=!e||f.nodeName==e)&&!(h=!c)&&(h=p(f.className))&&(h=0<=va(f.className.split(/\s+/),c));return h},!0,d)}function bc(a,b,c,d){a&&!c&&(a=a.parentNode);for(c=0;a&&(null==d||c<=d);){if(b(a))return a;a=a.parentNode;c++}return null}function J(a){this.a=a||m.document||document}g=J.prototype;g.na=Bb;g.Ab=function(a){this.a=a};g.ja=function(){return this.a};
g.H=function(a){return p(a)?this.a.getElementById(a):a};g.Ha=function(a){return p(a)?this.a.getElementById(a):a};g.P=J.prototype.H;g.Qa=function(a,b){return(b||this.a).getElementsByTagName(String(a))};g.I=function(a,b,c){return Eb(this.a,a,b,c)};g.pa=function(a,b,c){return Db(this.a,a,b,c)};g.qa=function(a,b){var c=(b=b||this.a)||document;return c.querySelectorAll&&c.querySelector?c.querySelectorAll("."+a):Eb(document,"*",a,b)};g.oa=function(a,b){return Cb(a,b||this.a)};
g.Ia=function(a,b){return Cb(a,b||this.a)};g.R=J.prototype.I;g.Cb=Fb;g.La=function(a){return Jb(a||M(this.a)||window)};g.ka=function(){var a=M(this.a),b=a.document;var c=0;if(b){c=b.body;var d=b.documentElement;if(d&&c)if(a=Jb(a).height,L(b)&&d.scrollHeight)c=d.scrollHeight!=a?d.scrollHeight:d.offsetHeight;else{b=d.scrollHeight;var e=d.offsetHeight;d.clientHeight!=e&&(b=c.scrollHeight,e=c.offsetHeight);c=b>a?b>e?b:e:b<e?b:e}else c=0}return c};
g.G=function(a,b,c){var d=this.a,e=arguments,f=String(e[0]),h=e[1];if(!vb&&h&&(h.name||h.type)){f=["<",f];h.name&&f.push(' name="',Ya(h.name),'"');if(h.type){f.push(' type="',Ya(h.type),'"');var k={};Oa(k,h);delete k.type;h=k}f.push(">");f=f.join("")}f=d.createElement(f);h&&(p(h)?f.className=h:t(h)?f.className=h.join(" "):Fb(f,h));2<e.length&&Lb(d,f,e,2);return f};g.S=J.prototype.G;g.Pa=function(a){return this.a.createTextNode(String(a))};
g.W=function(a,b,c){var d=this.a;c=!!c;for(var e=d.createElement("TABLE"),f=e.appendChild(d.createElement("TBODY")),h=0;h<a;h++){for(var k=d.createElement("TR"),Gb=0;Gb<b;Gb++){var Hb=d.createElement("TD");c&&Tb(Hb,"\u00a0");k.appendChild(Hb)}f.appendChild(k)}return e};
g.xb=function(a){var b=this.a;var c=b.createElement("DIV");C?(a=Ua(Va,a),Xa(c,a),c.removeChild(c.firstChild)):Xa(c,a);if(1==c.childNodes.length)c=c.removeChild(c.firstChild);else{for(b=b.createDocumentFragment();c.firstChild;)b.appendChild(c.firstChild);c=b}return c};g.gb=function(){return L(this.a)};g.ma=function(){return Kb(this.a)};
g.la=function(){var a=this.a,b=Kb(a);a=M(a);return C&&F("10")&&a.pageYOffset!=b.scrollTop?new I(b.scrollLeft,b.scrollTop):new I(a.pageXOffset||b.scrollLeft,a.pageYOffset||b.scrollTop)};g.ca=function(a){a=a||this.a;try{var b=a&&a.activeElement;var c=b&&b.nodeName?b:null}catch(d){c=null}return c};g.Na=function(a,b){a.appendChild(b)};g.Ma=function(a,b){Lb(K(a),a,arguments,1)};g.Oa=function(a){if(1!=a.nodeType)return!1;switch(a.tagName){case "APPLET":case "AREA":case "BASE":case "BR":case "COL":case "COMMAND":case "EMBED":case "FRAME":case "HR":case "IMG":case "INPUT":case "IFRAME":case "ISINDEX":case "KEYGEN":case "LINK":case "NOFRAMES":case "NOSCRIPT":case "META":case "OBJECT":case "PARAM":case "SCRIPT":case "SOURCE":case "STYLE":case "TRACK":case "WBR":return!1}return!0};
g.vb=Ob;g.fb=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b)};g.eb=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b.nextSibling)};g.cb=function(a,b,c){a.insertBefore(b,a.childNodes[c]||null)};g.Ra=N;g.Sa=function(a,b){var c=b.parentNode;c&&c.replaceChild(a,b)};g.ba=function(a){var b,c=a.parentNode;if(c&&11!=c.nodeType){if(a.removeNode)return a.removeNode(!1);for(;b=a.firstChild;)c.insertBefore(b,a);return N(a)}};
g.ha=function(a){return wb&&void 0!=a.children?a.children:xa(a.childNodes,function(b){return 1==b.nodeType})};g.ra=function(a){return n(a.firstElementChild)?a.firstElementChild:O(a.firstChild,!0)};g.ua=function(a){return n(a.lastElementChild)?a.lastElementChild:O(a.lastChild,!1)};g.xa=function(a){return n(a.nextElementSibling)?a.nextElementSibling:O(a.nextSibling,!0)};g.Fa=function(a){return n(a.previousElementSibling)?a.previousElementSibling:O(a.previousSibling,!1)};
g.ya=function(a){if(!a)return null;if(a.firstChild)return a.firstChild;for(;a&&!a.nextSibling;)a=a.parentNode;return a?a.nextSibling:null};g.Ga=function(a){if(!a)return null;if(!a.previousSibling)return a.parentNode;for(a=a.previousSibling;a&&a.lastChild;)a=a.lastChild;return a};g.lb=Mb;g.hb=Pb;g.nb=function(a){return u(a)&&a.window==a};g.Ea=function(a){var b;if(yb&&!(C&&F("9")&&!F("10")&&m.SVGElement&&a instanceof m.SVGElement)&&(b=a.parentElement))return b;b=a.parentNode;return Pb(b)?b:null};
g.contains=Qb;
g.V=function(a,b){if(a==b)return 0;if(a.compareDocumentPosition)return a.compareDocumentPosition(b)&2?1:-1;if(C&&!(9<=Number(G))){if(9==a.nodeType)return-1;if(9==b.nodeType)return 1}if("sourceIndex"in a||a.parentNode&&"sourceIndex"in a.parentNode){var c=1==a.nodeType,d=1==b.nodeType;if(c&&d)return a.sourceIndex-b.sourceIndex;var e=a.parentNode,f=b.parentNode;return e==f?Sb(a,b):!c&&Qb(e,b)?-1*Rb(a,b):!d&&Qb(f,a)?Rb(b,a):(c?a.sourceIndex:e.sourceIndex)-(d?b.sourceIndex:f.sourceIndex)}d=K(a);c=d.createRange();
c.selectNode(a);c.collapse(!0);a=d.createRange();a.selectNode(b);a.collapse(!0);return c.compareBoundaryPoints(m.Range.START_TO_END,a)};g.Y=function(a){var b,c=arguments.length;if(!c)return null;if(1==c)return arguments[0];var d=[],e=Infinity;for(b=0;b<c;b++){for(var f=[],h=arguments[b];h;)f.unshift(h),h=h.parentNode;d.push(f);e=Math.min(e,f.length)}f=null;for(b=0;b<e;b++){h=d[0][b];for(var k=1;k<c;k++)if(h!=d[k][b])return f;f=h}return f};g.Da=K;g.sa=function(a){return a.contentDocument||a.contentWindow.document};
g.ta=function(a){try{var b;if(!(b=a.contentWindow)){if(a.contentDocument){var c=a.contentDocument;var d=c?M(c):window}else d=null;b=d}return b}catch(e){}return null};g.Db=Tb;g.Ca=function(a){if("outerHTML"in a)return a.outerHTML;var b=K(a).createElement("DIV");b.appendChild(a.cloneNode(!0));return b.innerHTML};g.Z=function(a,b){var c=[];return Ub(a,b,c,!0)?c[0]:void 0};g.$=function(a,b){var c=[];Ub(a,b,c,!1);return c};g.kb=Wb;g.Bb=function(a,b){b?a.tabIndex=0:(a.tabIndex=-1,a.removeAttribute("tabIndex"))};
g.jb=function(a){var b;if((b="A"==a.tagName&&a.hasAttribute("href")||"INPUT"==a.tagName||"TEXTAREA"==a.tagName||"SELECT"==a.tagName||"BUTTON"==a.tagName?!a.disabled&&(!Xb(a)||Yb(a)):Wb(a))&&C){var c;"function"!=r(a.getBoundingClientRect)||C&&null==a.parentElement?c={height:a.offsetHeight,width:a.offsetWidth}:c=a.getBoundingClientRect();a=null!=c&&0<c.height&&0<c.width}else a=b;return a};g.Ka=Zb;g.Aa=function(a){return Zb(a).length};
g.Ba=function(a,b){b=b||K(a).body;for(var c=[];a&&a!=b;){for(var d=a;d=d.previousSibling;)c.unshift(Zb(d));a=a.parentNode}return c.join("").replace(/^[\s\xa0]+/,"").replace(/ +/g," ").length};
g.za=function(a,b,c){a=[a];for(var d=0,e=null;0<a.length&&d<b;)if(e=a.pop(),!(e.nodeName in Vb))if(3==e.nodeType){var f=e.nodeValue.replace(/(\r\n|\r|\n)/g,"").replace(/ +/g," ");d+=f.length}else if(e.nodeName in P)d+=P[e.nodeName].length;else for(f=e.childNodes.length-1;0<=f;f--)a.push(e.childNodes[f]);u(c)&&(c.ub=e?e.nodeValue.length+b-d-1:0,c.node=e);return e};g.mb=Nb;g.fa=ac;g.ea=function(a,b,c){return ac(a,null,b,c)};g.da=bc;g.ga=function(a){return a.getContext("2d")};/*
 Copyright (c) Microsoft Corporation. All rights reserved.
 Licensed under the Apache License, Version 2.0 (the "License"); you may not use
 this file except in compliance with the License. You may obtain a copy of the
 License at http://www.apache.org/licenses/LICENSE-2.0

 THIS CODE IS PROVIDED ON AN *AS IS* BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION ANY IMPLIED
 WARRANTIES OR CONDITIONS OF TITLE, FITNESS FOR A PARTICULAR PURPOSE,
 MERCHANTABLITY OR NON-INFRINGEMENT.

 See the Apache Version 2.0 License for specific language governing permissions
 and limitations under the License.
*/
var cc=!/^\s*class\s*\{\s*\}\s*$/.test(function(){}.toString());/*

 Copyright (c) 2016 The Polymer Project Authors. All rights reserved.
 This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
 The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
 The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
 Code distributed by Google as part of the polymer project is also
 subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
(function(){if(cc&&!HTMLElement.es5Shimmed&&void 0!==window.Reflect&&void 0!==window.customElements&&!window.customElements.polyfillWrapFlushCallback){var a=HTMLElement;window.HTMLElement=function(){return Reflect.construct(a,[],this.constructor)};HTMLElement.prototype=a.prototype;HTMLElement.prototype.constructor=HTMLElement;HTMLElement.es5Shimmed=!0;Object.setPrototypeOf(HTMLElement,a)}})();function Q(a){var b=HTMLElement.call(this)||this;a&&(p(a)&&(a=[a]),document.body.dispatchEvent(new CustomEvent("devsite-load-custom-elements",{bubbles:!0,detail:a})));return b}ja(Q,HTMLElement);Q.prototype.D=function(){console.warn(this.tagName,"has not implemented update")};Q.prototype.g=function(a){a=void 0===a?"":a;return document.createRange().createContextualFragment(a||"")};
Q.prototype.C=function(a,b){a&&b?a.parentNode.replaceChild(document.importNode(b,!0),a):!b&&a?a.parentNode.removeChild(a):!a&&b&&this.appendChild(document.importNode(b,!0))};function dc(a,b){window.getSelection().removeAllRanges();var c=document.createElement("pre");c.setAttribute("is-upgraded","");c.style.position="absolute";c.style.top="-99999px";c.style.left="-99999px";c.classList.add("clear-for-copy");Array.from(b.childNodes).forEach(function(d){d.classList&&d.classList.contains("no-select")||c.appendChild(d.cloneNode(!0))});a.appendChild(c);return c}
function ec(a,b){a=dc(a,b);b=!1;window.getSelection().selectAllChildren(a);window.getSelection().toString()&&document.queryCommandSupported("copy")&&(document.execCommand("copy"),b=!0);window.getSelection().removeAllRanges();N(a);return b}function fc(a,b){var c=document.createElement("pre");c.setAttribute("is-upgraded","");b.forEach(function(d){c.appendChild(d.cloneNode(!0))});b=document.querySelector("devsite-snackbar");ec(a,c)&&b&&b.setAttribute("type","copied-to-clipboard");N(c)};function R(){this.f=this.f;this.b=this.b}g=R.prototype;g.f=!1;g.J=function(){return this.f};g.ia=R.prototype.J;g.w=function(){this.f||(this.f=!0,this.m())};g.tb=function(a){a=sa(gc,a);this.f?n(void 0)?a.call(void 0):a():(this.b||(this.b=[]),this.b.push(n(void 0)?v(a,void 0):a))};g.m=function(){if(this.b)for(;this.b.length;)this.b.shift()()};function gc(a){a&&"function"==typeof a.w&&a.w()};var hc=!C||9<=Number(G),ic=!C||9<=Number(G),jc=C&&!F("9"),kc=function(){if(!m.addEventListener||!Object.defineProperty)return!1;var a=!1,b=Object.defineProperty({},"passive",{get:function(){a=!0}});try{m.addEventListener("test",oa,b),m.removeEventListener("test",oa,b)}catch(c){}return a}();function S(a,b){this.type=a;this.b=this.target=b;this.M=this.g=!1;this.O=!0}S.prototype.s=function(){this.g=!0};S.prototype.c=function(){this.M=!0;this.O=!1};function T(a,b){S.call(this,a?a.type:"");this.relatedTarget=this.b=this.target=null;this.button=this.screenY=this.screenX=this.clientY=this.clientX=this.K=this.D=0;this.key="";this.A=this.C=0;this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.L=null;this.N=!1;this.pointerId=0;this.pointerType="";this.a=null;if(a){var c=this.type=a.type,d=a.changedTouches&&a.changedTouches.length?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.b=b;if(b=a.relatedTarget){if(D){a:{try{Za(b.nodeName);
var e=!0;break a}catch(f){}e=!1}e||(b=null)}}else"mouseover"==c?b=a.fromElement:"mouseout"==c&&(b=a.toElement);this.relatedTarget=b;d?(this.clientX=void 0!==d.clientX?d.clientX:d.pageX,this.clientY=void 0!==d.clientY?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=d.screenY||0):(this.D=E||void 0!==a.offsetX?a.offsetX:a.layerX,this.K=E||void 0!==a.offsetY?a.offsetY:a.layerY,this.clientX=void 0!==a.clientX?a.clientX:a.pageX,this.clientY=void 0!==a.clientY?a.clientY:a.pageY,this.screenX=a.screenX||
0,this.screenY=a.screenY||0);this.button=a.button;this.C=a.keyCode||0;this.key=a.key||"";this.A=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.N=db?a.metaKey:a.ctrlKey;this.pointerId=a.pointerId||0;this.pointerType=p(a.pointerType)?a.pointerType:lc[a.pointerType]||"";this.L=a.state;this.a=a;a.defaultPrevented&&this.c()}}ta(T,S);var mc=[1,4,2],lc={2:"touch",3:"pen",4:"mouse"};
T.prototype.T=function(){return(hc?0==this.a.button:"click"==this.type?!0:!!(this.a.button&mc[0]))&&!(E&&db&&this.ctrlKey)};T.prototype.s=function(){T.i.s.call(this);this.a.stopPropagation?this.a.stopPropagation():this.a.cancelBubble=!0};T.prototype.c=function(){T.i.c.call(this);var a=this.a;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,jc)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};T.prototype.Fb=function(){return this.a};var U="closure_listenable_"+(1E6*Math.random()|0),nc=0;function oc(a,b,c,d,e){this.listener=a;this.a=null;this.src=b;this.type=c;this.capture=!!d;this.b=e;this.key=++nc;this.h=this.j=!1}function V(a){a.h=!0;a.listener=null;a.a=null;a.src=null;a.b=null};function pc(a){this.src=a;this.a={};this.b=0}g=pc.prototype;g.Va=function(){var a=0,b;for(b in this.a)a+=this.a[b].length;return a};g.add=function(a,b,c,d,e){var f=a.toString();a=this.a[f];a||(a=this.a[f]=[],this.b++);var h=qc(a,b,d,e);-1<h?(b=a[h],c||(b.j=!1)):(b=new oc(b,this.src,f,!!d,e),b.j=c,a.push(b));return b};
g.Xa=function(a,b,c,d){a=a.toString();if(!(a in this.a))return!1;var e=this.a[a];b=qc(e,b,c,d);return-1<b?(V(e[b]),Array.prototype.splice.call(e,b,1),0==e.length&&(delete this.a[a],this.b--),!0):!1};g.Ya=function(a){a=a&&a.toString();var b=0,c;for(c in this.a)if(!a||c==a){for(var d=this.a[c],e=0;e<d.length;e++)++b,V(d[e]);delete this.a[c];this.b--}return b};g.va=function(a,b){a=this.a[a.toString()];var c=[];if(a)for(var d=0;d<a.length;++d){var e=a[d];e.capture==b&&c.push(e)}return c};
g.Wa=function(a,b){var c=n(a),d=c?a.toString():"",e=n(b);return Ma(this.a,function(f){for(var h=0;h<f.length;++h)if(!(c&&f[h].type!=d||e&&f[h].capture!=b))return!0;return!1})};function qc(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.h&&f.listener==b&&f.capture==!!c&&f.b==d)return e}return-1};var rc="closure_lm_"+(1E6*Math.random()|0),sc={},tc=0;function uc(a,b,c,d,e){if(d&&d.once)return vc(a,b,c,d,e);if(t(b)){for(var f=0;f<b.length;f++)uc(a,b[f],c,d,e);return null}c=wc(c);return a&&a[U]?W(a,b,c,u(d)?!!d.capture:!!d,e):xc(a,b,c,!1,d,e)}
function xc(a,b,c,d,e,f){if(!b)throw Error("Invalid event type");var h=u(e)?!!e.capture:!!e,k=X(a);k||(a[rc]=k=new pc(a));c=k.add(b,c,d,h,f);if(c.a)return c;d=yc();c.a=d;d.src=a;d.listener=c;if(a.addEventListener)kc||(e=h),void 0===e&&(e=!1),a.addEventListener(b.toString(),d,e);else if(a.attachEvent)a.attachEvent(zc(b.toString()),d);else if(a.addListener&&a.removeListener)a.addListener(d);else throw Error("addEventListener and attachEvent are unavailable.");tc++;return c}
function yc(){var a=Ac,b=ic?function(c){return a.call(b.src,b.listener,c)}:function(c){c=a.call(b.src,b.listener,c);if(!c)return c};return b}function vc(a,b,c,d,e){if(t(b)){for(var f=0;f<b.length;f++)vc(a,b[f],c,d,e);return null}c=wc(c);return a&&a[U]?a.A(b,c,u(d)?!!d.capture:!!d,e):xc(a,b,c,!0,d,e)}
function Bc(a){if(!q(a)&&a&&!a.h){var b=a.src;if(b&&b[U])b.a(a);else{var c=a.type,d=a.a;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent?b.detachEvent(zc(c),d):b.addListener&&b.removeListener&&b.removeListener(d);tc--;if(c=X(b)){d=a.type;if(d in c.a){var e=c.a[d],f=va(e,a),h;(h=0<=f)&&Array.prototype.splice.call(e,f,1);h&&(V(a),0==c.a[d].length&&(delete c.a[d],c.b--))}0==c.b&&(c.src=null,b[rc]=null)}else V(a)}}}function zc(a){return a in sc?sc[a]:sc[a]="on"+a}
function Cc(a,b,c,d){var e=!0;if(a=X(a))if(b=a.a[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.capture==c&&!f.h&&(f=Dc(f,d),e=e&&!1!==f)}return e}function Dc(a,b){var c=a.listener,d=a.b||a.src;a.j&&Bc(a);return c.call(d,b)}
function Ac(a,b){if(a.h)return!0;if(!ic){if(!b)a:{b=["window","event"];for(var c=m,d=0;d<b.length;d++)if(c=c[b[d]],null==c){b=null;break a}b=c}d=b;b=new T(d,this);c=!0;if(!(0>d.keyCode||void 0!=d.returnValue)){a:{var e=!1;if(0==d.keyCode)try{d.keyCode=-1;break a}catch(h){e=!0}if(e||void 0==d.returnValue)d.returnValue=!0}d=[];for(e=b.b;e;e=e.parentNode)d.push(e);a=a.type;for(e=d.length-1;!b.g&&0<=e;e--){b.b=d[e];var f=Cc(d[e],a,!0,b);c=c&&f}for(e=0;!b.g&&e<d.length;e++)b.b=d[e],f=Cc(d[e],a,!1,b),c=
c&&f}return c}return Dc(a,new T(b,this))}function X(a){a=a[rc];return a instanceof pc?a:null}var Ec="__closure_events_fn_"+(1E9*Math.random()>>>0);function wc(a){if("function"==r(a))return a;a[Ec]||(a[Ec]=function(b){return a.handleEvent(b)});return a[Ec]};function Y(a){R.call(this);this.c=a;this.a={}}ta(Y,R);var Fc=[];function Gc(a,b,c){W(a,b,"click",c,void 0)}g=Y.prototype;g.pb=function(a,b,c,d,e){return W(this,a,b,c,d,e)};function W(a,b,c,d,e,f){t(c)||(c&&(Fc[0]=c.toString()),c=Fc);for(var h=0;h<c.length;h++){var k=uc(b,c[h],d||a.handleEvent,e||!1,f||a.c||a);if(!k)break;a.a[k.key]=k}return a}g.Ua=function(a,b,c,d){return Hc(this,a,b,c,d)};g.ob=function(a,b,c,d,e){return Hc(this,a,b,c,d,e)};
function Hc(a,b,c,d,e,f){if(t(c))for(var h=0;h<c.length;h++)Hc(a,b,c[h],d,e,f);else{b=vc(b,c,d||a.handleEvent,e,f||a.c||a);if(!b)return a;a.a[b.key]=b}return a}g.qb=function(a,b,c,d){W(b,a,c,d,this.c||this);return this};g.rb=function(a,b,c,d,e){W(b,a,c,d,e||this.c||this);return this};g.Ta=function(){var a=0,b;for(b in this.a)Object.prototype.hasOwnProperty.call(this.a,b)&&a++;return a};
function Ic(a,b,c,d,e,f){if(t(c))for(var h=0;h<c.length;h++)Ic(a,b,c[h],d,e,f);else d=d||a.handleEvent,e=u(e)?!!e.capture:!!e,f=f||a.c||a,d=wc(d),e=!!e,b&&b[U]?c=b.s(c,d,e,f):b?(b=X(b))?(c=b.a[c.toString()],b=-1,c&&(b=qc(c,d,e,f)),c=-1<b?c[b]:null):c=null:c=null,c&&(Bc(c),delete a.a[c.key])}g.Eb=function(a,b,c,d,e){Ic(b,a,c,d,e||this.c||this,this);return this};function Jc(a){La(a.a,function(b,c){this.a.hasOwnProperty(c)&&Bc(b)},a);a.a={}}g.m=function(){Y.i.m.call(this);Jc(this)};
g.handleEvent=function(){throw Error("EventHandler.handleEvent not implemented");};function Kc(a){var b=a(Lc,void 0,void 0);a=Bb().a.createElement("DIV");if(u(b))if(b instanceof H)if(b.l===nb)b=A(b.toString());else{if(b.l!==lb)throw Error("Sanitized content was not of kind TEXT or HTML.");b=B(b.toString(),b.v||null)}else b=A("zSoyz");else b=A(String(b));Xa(a,b);1==a.childNodes.length&&(b=a.firstChild,1==b.nodeType&&(a=b));return a}var Lc={};var Mc=!!document.queryCommandSupported("copy");function Z(){var a=Q.call(this,["devsite-snackbar"])||this;a.b=new Y;a.c=!1;a.a=null;return a}ja(Z,Q);function Nc(){return"devsite-heading"}Z.prototype.connectedCallback=function(){var a=this;this.c||(window.requestAnimationFrame(function(){Oc(a);a.parentNode&&(Pc(a),a.dispatchEvent(new CustomEvent("devsite-content-updated",{bubbles:!0})))}),this.c=!0)};Z.prototype.disconnectedCallback=function(){Jc(this.b)};
function Pc(a){if(a.a){if(a.id&&a.hasAttribute("link")){var b=a.querySelector(".devsite-heading-link");b||(b=Kc(tb),Gc(a.b,b,function(){var c=new URL(document.location.toString());c.hash=a.id;var d=document.createElement("div");d.innerText=c.href;fc(a,[d]);N(d)}),a.a.appendChild(b))}"docs"===document.body.getAttribute("layout")&&"h2"===a.getAttribute("level")&&(b=Kc(ub),a.a.appendChild(b),a.setAttribute("back-to-top",""))}}
function Oc(a){a.a=a.querySelector("h1, h2, h3, h4, h5, h6");if(a.a){var b=a.a.tagName.toLowerCase(),c=Qc(a.a);if(!a.hasAttribute("text")){if(!c){N(a);return}a.setAttribute("text",c)}if(!a.id){var d=a.a.id||a.a.getAttribute("name");d?(a.a.removeAttribute("id"),a.a.removeAttribute("name"),a.id=encodeURI(d)):(c=(void 0===c?"":c).toLowerCase().trim().replace(/\s+/g,"-").replace(/[!@#\$%\^&\*\(\)\{\}<>\?\\\/'"]+/g,"").trim()||"heading",d=encodeURI(d),a.id=Rc(c))}a.hasAttribute("level")||a.setAttribute("level",
b);a.hasAttribute("link")||(d="h1"!==b&&"docs"===document.body.getAttribute("layout")&&!a.a.classList.contains("no-link")&&!ac(a,"th"),c=a.a.classList.contains("add-link"),(d||c)&&Mc&&a.setAttribute("link",""));a.hasAttribute("toc")||"h2"!==b&&"h3"!==b||a.a.classList.contains("hide-from-toc")||"contents"===a.id||"table-of-contents"===a.id||a.setAttribute("toc","");b=Array.from(a.a.classList).filter(function(e){return"no-link"!==e&&"hide-from-toc"!==e});a.classList.add.apply(a.classList,b instanceof
Array?b:ca(ba(b)));a.a.classList.remove.apply(a.a.classList,b instanceof Array?b:ca(ba(b)))}}function Qc(a){return Array.from(a.childNodes).filter(function(b){return b.textContent&&(3===b.nodeType||1===b.nodeType&&!b.classList.contains("material-icons")&&null!==b.offsetParent)}).map(function(b){return b.textContent.trim()}).join(" ")}function Rc(a){for(var b=a,c=1;document.getElementById(b);)b=a+"_"+c++;return b}Z.prototype.disconnectedCallback=Z.prototype.disconnectedCallback;
Z.prototype.connectedCallback=Z.prototype.connectedCallback;Z.getTagName=Nc;try{window.customElements.define(Nc(),Z)}catch(a){console.warn("devsite.app.customElement.DevsiteHeading",a)};}).call(this);
