(function(){'use strict';var h,aa="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},ba;if("function"==typeof Object.setPrototypeOf)ba=Object.setPrototypeOf;else{var ca;a:{var da={L:!0},ea={};try{ea.__proto__=da;ca=ea.L;break a}catch(a){}ca=!1}ba=ca?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var fa=ba;
function ha(a,b){a.prototype=aa(b.prototype);a.prototype.constructor=a;if(fa)fa(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.w=b.prototype}var p="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)},q="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this;
function r(a,b){if(b){var c=q;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&p(c,a,{configurable:!0,writable:!0,value:b})}}function ia(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function ja(){ja=function(){};q.Symbol||(q.Symbol=ka)}function la(a,b){this.a=a;p(this,"description",{configurable:!0,writable:!0,value:b})}la.prototype.toString=function(){return this.a};
var ka=function(){function a(c){if(this instanceof a)throw new TypeError("Symbol is not a constructor");return new la("jscomp_symbol_"+(c||"")+"_"+b++,c)}var b=0;return a}();function ma(){ja();var a=q.Symbol.iterator;a||(a=q.Symbol.iterator=q.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[a]&&p(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return na(ia(this))}});ma=function(){}}function na(a){ma();a={next:a};a[q.Symbol.iterator]=function(){return this};return a}
r("Object.setPrototypeOf",function(a){return a||fa});function t(a,b){return Object.prototype.hasOwnProperty.call(a,b)}function oa(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:ia(a)}}
var pa=function(){function a(){function c(){}new c;Reflect.construct(c,[],function(){});return new c instanceof c}if("undefined"!=typeof Reflect&&Reflect.construct){if(a())return Reflect.construct;var b=Reflect.construct;return function(c,d,e){c=b(c,d);e&&Reflect.setPrototypeOf(c,e.prototype);return c}}return function(c,d,e){void 0===e&&(e=c);e=aa(e.prototype||Object.prototype);return Function.prototype.apply.call(c,e,d)||e}}();r("Reflect.construct",function(){return pa});
r("WeakMap",function(a){function b(g){this.a=(k+=Math.random()+1).toString();if(g){g=oa(g);for(var m;!(m=g.next()).done;)m=m.value,this.set(m[0],m[1])}}function c(){}function d(g){if(!t(g,f)){var m=new c;p(g,f,{value:m})}}function e(g){var m=Object[g];m&&(Object[g]=function(l){if(l instanceof c)return l;d(l);return m(l)})}if(function(){if(!a||!Object.seal)return!1;try{var g=Object.seal({}),m=Object.seal({}),l=new a([[g,2],[m,3]]);if(2!=l.get(g)||3!=l.get(m))return!1;l.delete(g);l.set(m,4);return!l.has(g)&&
4==l.get(m)}catch(n){return!1}}())return a;var f="$jscomp_hidden_"+Math.random();e("freeze");e("preventExtensions");e("seal");var k=0;b.prototype.set=function(g,m){d(g);if(!t(g,f))throw Error("WeakMap key fail: "+g);g[f][this.a]=m;return this};b.prototype.get=function(g){return t(g,f)?g[f][this.a]:void 0};b.prototype.has=function(g){return t(g,f)&&t(g[f],this.a)};b.prototype.delete=function(g){return t(g,f)&&t(g[f],this.a)?delete g[f][this.a]:!1};return b});
r("Map",function(a){function b(){var g={};return g.i=g.next=g.head=g}function c(g,m){var l=g.a;return na(function(){if(l){for(;l.head!=g.a;)l=l.i;for(;l.next!=l.head;)return l=l.next,{done:!1,value:m(l)};l=null}return{done:!0,value:void 0}})}function d(g,m){var l=m&&typeof m;"object"==l||"function"==l?f.has(m)?l=f.get(m):(l=""+ ++k,f.set(m,l)):l="p_"+m;var n=g.b[l];if(n&&t(g.b,l))for(g=0;g<n.length;g++){var P=n[g];if(m!==m&&P.key!==P.key||m===P.key)return{id:l,list:n,index:g,f:P}}return{id:l,list:n,
index:-1,f:void 0}}function e(g){this.b={};this.a=b();this.size=0;if(g){g=oa(g);for(var m;!(m=g.next()).done;)m=m.value,this.set(m[0],m[1])}}if(function(){if(!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var g=Object.seal({x:4}),m=new a(oa([[g,"s"]]));if("s"!=m.get(g)||1!=m.size||m.get({x:4})||m.set({x:4},"t")!=m||2!=m.size)return!1;var l=m.entries(),n=l.next();if(n.done||n.value[0]!=g||"s"!=n.value[1])return!1;n=l.next();return n.done||4!=n.value[0].x||
"t"!=n.value[1]||!l.next().done?!1:!0}catch(P){return!1}}())return a;ma();var f=new WeakMap;e.prototype.set=function(g,m){g=0===g?0:g;var l=d(this,g);l.list||(l.list=this.b[l.id]=[]);l.f?l.f.value=m:(l.f={next:this.a,i:this.a.i,head:this.a,key:g,value:m},l.list.push(l.f),this.a.i.next=l.f,this.a.i=l.f,this.size++);return this};e.prototype.delete=function(g){g=d(this,g);return g.f&&g.list?(g.list.splice(g.index,1),g.list.length||delete this.b[g.id],g.f.i.next=g.f.next,g.f.next.i=g.f.i,g.f.head=null,
this.size--,!0):!1};e.prototype.clear=function(){this.b={};this.a=this.a.i=b();this.size=0};e.prototype.has=function(g){return!!d(this,g).f};e.prototype.get=function(g){return(g=d(this,g).f)&&g.value};e.prototype.entries=function(){return c(this,function(g){return[g.key,g.value]})};e.prototype.keys=function(){return c(this,function(g){return g.key})};e.prototype.values=function(){return c(this,function(g){return g.value})};e.prototype.forEach=function(g,m){for(var l=this.entries(),n;!(n=l.next()).done;)n=
n.value,g.call(m,n[1],n[0],this)};e.prototype[Symbol.iterator]=e.prototype.entries;var k=0;return e});r("Array.from",function(a){return a?a:function(b,c,d){c=null!=c?c:function(g){return g};var e=[],f="undefined"!=typeof Symbol&&Symbol.iterator&&b[Symbol.iterator];if("function"==typeof f){b=f.call(b);for(var k=0;!(f=b.next()).done;)e.push(c.call(d,f.value,k++))}else for(f=b.length,k=0;k<f;k++)e.push(c.call(d,b[k],k));return e}});var u=this||self;function v(a){return void 0!==a}
function w(a){return"string"==typeof a}function x(a){return"number"==typeof a}function qa(){}
function ra(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function y(a){return"array"==ra(a)}function sa(a){var b=ra(a);return"array"==b||"object"==b&&"number"==typeof a.length}function z(a){return"function"==ra(a)}function A(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}function ta(a,b,c){return a.call.apply(a.bind,arguments)}
function ua(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,d);return a.apply(b,e)}}return function(){return a.apply(b,arguments)}}function B(a,b,c){Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?B=ta:B=ua;return B.apply(null,arguments)}
function va(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var d=c.slice();d.push.apply(d,arguments);return a.apply(this,d)}}var wa=Date.now||function(){return+new Date};function C(a,b){function c(){}c.prototype=b.prototype;a.w=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.aa=function(d,e,f){for(var k=Array(arguments.length-2),g=2;g<arguments.length;g++)k[g-2]=arguments[g];return b.prototype[e].apply(d,k)}};var xa;var ya=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if(w(a))return w(b)&&1==b.length?a.indexOf(b,0):-1;for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},za=Array.prototype.forEach?function(a,b){Array.prototype.forEach.call(a,b,void 0)}:function(a,b){for(var c=a.length,d=w(a)?a.split(""):a,e=0;e<c;e++)e in d&&b.call(void 0,d[e],e,a)},Aa=Array.prototype.filter?function(a,b){return Array.prototype.filter.call(a,b,void 0)}:function(a,
b){for(var c=a.length,d=[],e=0,f=w(a)?a.split(""):a,k=0;k<c;k++)if(k in f){var g=f[k];b.call(void 0,g,k,a)&&(d[e++]=g)}return d};function Ba(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]};function Ca(a,b,c){for(var d in a)b.call(c,a[d],d,a)}var Da="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");function Ea(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<Da.length;f++)c=Da[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};var Fa=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]};
function Ga(a,b){if(b)a=a.replace(Ha,"&amp;").replace(Ia,"&lt;").replace(Ja,"&gt;").replace(Ka,"&quot;").replace(La,"&#39;").replace(Ma,"&#0;");else{if(!Na.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(Ha,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(Ia,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(Ja,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(Ka,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(La,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(Ma,"&#0;"))}return a}
var Ha=/&/g,Ia=/</g,Ja=/>/g,Ka=/"/g,La=/'/g,Ma=/\x00/g,Na=/[\x00&<>"']/;function Oa(a,b){return a<b?-1:a>b?1:0};function D(){this.b="";this.c=Pa}D.prototype.G=!0;D.prototype.F=function(){return this.b.toString()};D.prototype.J=!0;D.prototype.a=function(){return 1};var Pa={};function Qa(a){var b=new D;b.b=a;return b}Qa("about:blank");var E;a:{var Ra=u.navigator;if(Ra){var Sa=Ra.userAgent;if(Sa){E=Sa;break a}}E=""};function F(){this.b="";this.g=Ta;this.c=null}F.prototype.J=!0;F.prototype.a=function(){return this.c};F.prototype.G=!0;F.prototype.F=function(){return this.b.toString()};function G(a){return a instanceof F&&a.constructor===F&&a.g===Ta?a.b:"type_error:SafeHtml"}function H(a){if(a instanceof F)return a;var b="object"==typeof a,c=null;b&&a.J&&(c=a.a());a=Ga(b&&a.G?a.F():String(a));return I(a,c)}
function Ua(a){function b(f){y(f)?za(f,b):(f=H(f),e.push(G(f).toString()),f=f.a(),0==d?d=f:0!=f&&d!=f&&(d=null))}var c=H(Va),d=c.a(),e=[];za(a,b);return I(e.join(G(c).toString()),d)}function Wa(a){return Ua(Array.prototype.slice.call(arguments))}var Ta={};function I(a,b){var c=new F;c.b=a;c.c=b;return c}I("<!DOCTYPE html>",0);var Va=I("",0),Xa=I("<br>",0);var Ya=function(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}}(function(){var a=document.createElement("div"),b=document.createElement("div");b.appendChild(document.createElement("div"));a.appendChild(b);b=a.firstChild.firstChild;a.innerHTML=G(Va);return!b.parentElement});function Za(a,b){if(Ya())for(;a.lastChild;)a.removeChild(a.lastChild);a.innerHTML=G(b)};function $a(a){return a=Ga(a,void 0)};var ab={},bb={},cb={};function J(){throw Error("Do not instantiate directly");}J.prototype.D=null;J.prototype.b=function(){return this.a};J.prototype.toString=function(){return this.a};J.prototype.c=function(){if(this.A!==bb)throw Error("Sanitized content was not of kind URI.");return Qa(this.toString())};function db(){J.call(this)}C(db,J);db.prototype.A=ab;function eb(a){eb[" "](a);return a}eb[" "]=qa;function fb(a,b){var c=gb;return Object.prototype.hasOwnProperty.call(c,a)?c[a]:c[a]=b(a)};var hb=-1!=E.indexOf("Opera"),K=-1!=E.indexOf("Trident")||-1!=E.indexOf("MSIE"),ib=-1!=E.indexOf("Edge"),L=-1!=E.indexOf("Gecko")&&!(-1!=E.toLowerCase().indexOf("webkit")&&-1==E.indexOf("Edge"))&&!(-1!=E.indexOf("Trident")||-1!=E.indexOf("MSIE"))&&-1==E.indexOf("Edge"),M=-1!=E.toLowerCase().indexOf("webkit")&&-1==E.indexOf("Edge"),jb=-1!=E.indexOf("Macintosh");function kb(){var a=u.document;return a?a.documentMode:void 0}var lb;
a:{var mb="",nb=function(){var a=E;if(L)return/rv:([^\);]+)(\)|;)/.exec(a);if(ib)return/Edge\/([\d\.]+)/.exec(a);if(K)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(M)return/WebKit\/(\S+)/.exec(a);if(hb)return/(?:Version)[ \/]?(\S+)/.exec(a)}();nb&&(mb=nb?nb[1]:"");if(K){var ob=kb();if(null!=ob&&ob>parseFloat(mb)){lb=String(ob);break a}}lb=mb}var pb=lb,gb={};
function N(a){return fb(a,function(){for(var b=0,c=Fa(String(pb)).split("."),d=Fa(String(a)).split("."),e=Math.max(c.length,d.length),f=0;0==b&&f<e;f++){var k=c[f]||"",g=d[f]||"";do{k=/(\d*)(\D*)(.*)/.exec(k)||["","","",""];g=/(\d*)(\D*)(.*)/.exec(g)||["","","",""];if(0==k[0].length&&0==g[0].length)break;b=Oa(0==k[1].length?0:parseInt(k[1],10),0==g[1].length?0:parseInt(g[1],10))||Oa(0==k[2].length,0==g[2].length)||Oa(k[2],g[2]);k=k[3];g=g[3]}while(0==b)}return 0<=b})}var O;var qb=u.document;
O=qb&&K?kb()||("CSS1Compat"==qb.compatMode?parseInt(pb,10):5):void 0;function rb(a){if(null!=a)switch(a.D){case 1:return 1;case -1:return-1;case 0:return 0}return null}var sb=function(a){function b(c){this.a=c}b.prototype=a.prototype;return function(c,d){c=new b(String(c));void 0!==d&&(c.D=d);return c}}(db);/*
 Copyright (c) Microsoft Corporation. All rights reserved.
 Licensed under the Apache License, Version 2.0 (the "License"); you may not use
 this file except in compliance with the License. You may obtain a copy of the
 License at http://www.apache.org/licenses/LICENSE-2.0

 THIS CODE IS PROVIDED ON AN *AS IS* BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION ANY IMPLIED
 WARRANTIES OR CONDITIONS OF TITLE, FITNESS FOR A PARTICULAR PURPOSE,
 MERCHANTABLITY OR NON-INFRINGEMENT.

 See the Apache Version 2.0 License for specific language governing permissions
 and limitations under the License.
*/
var tb=!/^\s*class\s*\{\s*\}\s*$/.test(function(){}.toString());/*

 Copyright (c) 2016 The Polymer Project Authors. All rights reserved.
 This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
 The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
 The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
 Code distributed by Google as part of the polymer project is also
 subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
(function(){if(tb&&!HTMLElement.es5Shimmed&&void 0!==window.Reflect&&void 0!==window.customElements&&!window.customElements.polyfillWrapFlushCallback){var a=HTMLElement;window.HTMLElement=function(){return Reflect.construct(a,[],this.constructor)};HTMLElement.prototype=a.prototype;HTMLElement.prototype.constructor=HTMLElement;HTMLElement.es5Shimmed=!0;Object.setPrototypeOf(HTMLElement,a)}})();function Q(a){var b=HTMLElement.call(this)||this;a&&(w(a)&&(a=[a]),document.body.dispatchEvent(new CustomEvent("devsite-load-custom-elements",{bubbles:!0,detail:a})));return b}ha(Q,HTMLElement);Q.prototype.u=function(){console.warn(this.tagName,"has not implemented update")};Q.prototype.j=function(a){a=void 0===a?"":a;return document.createRange().createContextualFragment(a||"")};
Q.prototype.s=function(a,b){a&&b?a.parentNode.replaceChild(document.importNode(b,!0),a):!b&&a?a.parentNode.removeChild(a):!a&&b&&this.appendChild(document.importNode(b,!0))};var ub=new Map;function R(){return Q.call(this)||this}ha(R,Q);R.prototype.connectedCallback=function(){var a=this.constructor,b=ub.get(a);b?console.error("can't add duplicate element to page: "+b.tagName):ub.set(a,this)};R.prototype.disconnectedCallback=function(){var a=this.constructor;ub.get(a)===this&&ub.delete(a)};R.prototype.disconnectedCallback=R.prototype.disconnectedCallback;R.prototype.connectedCallback=R.prototype.connectedCallback;function S(){this.l=this.l;this.b=this.b}h=S.prototype;h.l=!1;h.P=function(){return this.l};h.pa=S.prototype.P;h.H=function(){this.l||(this.l=!0,this.o())};h.wb=function(a){a=va(vb,a);this.l?v(void 0)?a.call(void 0):a():(this.b||(this.b=[]),this.b.push(v(void 0)?B(a,void 0):a))};h.o=function(){if(this.b)for(;this.b.length;)this.b.shift()()};function vb(a){a&&"function"==typeof a.H&&a.H()};function wb(a,b){this.type=a;this.b=this.target=b;this.T=this.g=!1;this.W=!0}wb.prototype.h=function(){this.g=!0};wb.prototype.c=function(){this.T=!0;this.W=!1};var xb=!K||9<=Number(O),yb=!K||9<=Number(O),zb=K&&!N("9"),Ab=function(){if(!u.addEventListener||!Object.defineProperty)return!1;var a=!1,b=Object.defineProperty({},"passive",{get:function(){a=!0}});try{u.addEventListener("test",qa,b),u.removeEventListener("test",qa,b)}catch(c){}return a}();var Bb;Bb=M?"webkitTransitionEnd":hb?"otransitionend":"transitionend";function T(a,b){wb.call(this,a?a.type:"");this.relatedTarget=this.b=this.target=null;this.button=this.screenY=this.screenX=this.clientY=this.clientX=this.B=this.u=0;this.key="";this.j=this.s=0;this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.R=null;this.V=!1;this.pointerId=0;this.pointerType="";this.a=null;if(a){var c=this.type=a.type,d=a.changedTouches&&a.changedTouches.length?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.b=b;if(b=a.relatedTarget){if(L){a:{try{eb(b.nodeName);
var e=!0;break a}catch(f){}e=!1}e||(b=null)}}else"mouseover"==c?b=a.fromElement:"mouseout"==c&&(b=a.toElement);this.relatedTarget=b;d?(this.clientX=void 0!==d.clientX?d.clientX:d.pageX,this.clientY=void 0!==d.clientY?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=d.screenY||0):(this.u=M||void 0!==a.offsetX?a.offsetX:a.layerX,this.B=M||void 0!==a.offsetY?a.offsetY:a.layerY,this.clientX=void 0!==a.clientX?a.clientX:a.pageX,this.clientY=void 0!==a.clientY?a.clientY:a.pageY,this.screenX=a.screenX||
0,this.screenY=a.screenY||0);this.button=a.button;this.s=a.keyCode||0;this.key=a.key||"";this.j=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.V=jb?a.metaKey:a.ctrlKey;this.pointerId=a.pointerId||0;this.pointerType=w(a.pointerType)?a.pointerType:Cb[a.pointerType]||"";this.R=a.state;this.a=a;a.defaultPrevented&&this.c()}}C(T,wb);var Db=[1,4,2],Cb={2:"touch",3:"pen",4:"mouse"};
T.prototype.$=function(){return(xb?0==this.a.button:"click"==this.type?!0:!!(this.a.button&Db[0]))&&!(M&&jb&&this.ctrlKey)};T.prototype.h=function(){T.w.h.call(this);this.a.stopPropagation?this.a.stopPropagation():this.a.cancelBubble=!0};T.prototype.c=function(){T.w.c.call(this);var a=this.a;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,zb)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};T.prototype.Ib=function(){return this.a};var Eb="closure_listenable_"+(1E6*Math.random()|0),Fb=0;function Gb(a,b,c,d,e){this.listener=a;this.a=null;this.src=b;this.type=c;this.capture=!!d;this.b=e;this.key=++Fb;this.v=this.C=!1}function Hb(a){a.v=!0;a.listener=null;a.a=null;a.src=null;a.b=null};function Ib(a){this.src=a;this.a={};this.b=0}Ib.prototype.c=function(){var a=0,b;for(b in this.a)a+=this.a[b].length;return a};Ib.prototype.add=function(a,b,c,d,e){var f=a.toString();a=this.a[f];a||(a=this.a[f]=[],this.b++);var k=Jb(a,b,d,e);-1<k?(b=a[k],c||(b.C=!1)):(b=new Gb(b,this.src,f,!!d,e),b.C=c,a.push(b));return b};function Kb(a,b){var c=b.type;if(c in a.a){var d=a.a[c],e=ya(d,b),f;(f=0<=e)&&Array.prototype.splice.call(d,e,1);f&&(Hb(b),0==a.a[c].length&&(delete a.a[c],a.b--))}}
function Lb(a,b,c,d,e){a=a.a[b.toString()];b=-1;a&&(b=Jb(a,c,d,e));return-1<b?a[b]:null}function Jb(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.v&&f.listener==b&&f.capture==!!c&&f.b==d)return e}return-1};var Mb="closure_lm_"+(1E6*Math.random()|0),Nb={},Ob=0;function Pb(a,b,c,d,e){if(d&&d.once)return Qb(a,b,c,d,e);if(y(b)){for(var f=0;f<b.length;f++)Pb(a,b[f],c,d,e);return null}c=Rb(c);return a&&a[Eb]?a.m(b,c,A(d)?!!d.capture:!!d,e):Sb(a,b,c,!1,d,e)}
function Sb(a,b,c,d,e,f){if(!b)throw Error("Invalid event type");var k=A(e)?!!e.capture:!!e,g=Tb(a);g||(a[Mb]=g=new Ib(a));c=g.add(b,c,d,k,f);if(c.a)return c;d=Ub();c.a=d;d.src=a;d.listener=c;if(a.addEventListener)Ab||(e=k),void 0===e&&(e=!1),a.addEventListener(b.toString(),d,e);else if(a.attachEvent)a.attachEvent(Vb(b.toString()),d);else if(a.addListener&&a.removeListener)a.addListener(d);else throw Error("addEventListener and attachEvent are unavailable.");Ob++;return c}
function Ub(){var a=Wb,b=yb?function(c){return a.call(b.src,b.listener,c)}:function(c){c=a.call(b.src,b.listener,c);if(!c)return c};return b}function Qb(a,b,c,d,e){if(y(b)){for(var f=0;f<b.length;f++)Qb(a,b[f],c,d,e);return null}c=Rb(c);return a&&a[Eb]?a.g.add(String(b),c,!0,A(d)?!!d.capture:!!d,e):Sb(a,b,c,!0,d,e)}
function Xb(a){if(!x(a)&&a&&!a.v){var b=a.src;if(b&&b[Eb])Kb(b.g,a);else{var c=a.type,d=a.a;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent?b.detachEvent(Vb(c),d):b.addListener&&b.removeListener&&b.removeListener(d);Ob--;(c=Tb(b))?(Kb(c,a),0==c.b&&(c.src=null,b[Mb]=null)):Hb(a)}}}function Vb(a){return a in Nb?Nb[a]:Nb[a]="on"+a}
function Yb(a,b,c,d){var e=!0;if(a=Tb(a))if(b=a.a[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.capture==c&&!f.v&&(f=Zb(f,d),e=e&&!1!==f)}return e}function Zb(a,b){var c=a.listener,d=a.b||a.src;a.C&&Xb(a);return c.call(d,b)}
function Wb(a,b){if(a.v)return!0;if(!yb){if(!b)a:{b=["window","event"];for(var c=u,d=0;d<b.length;d++)if(c=c[b[d]],null==c){b=null;break a}b=c}d=b;b=new T(d,this);c=!0;if(!(0>d.keyCode||void 0!=d.returnValue)){a:{var e=!1;if(0==d.keyCode)try{d.keyCode=-1;break a}catch(k){e=!0}if(e||void 0==d.returnValue)d.returnValue=!0}d=[];for(e=b.b;e;e=e.parentNode)d.push(e);a=a.type;for(e=d.length-1;!b.g&&0<=e;e--){b.b=d[e];var f=Yb(d[e],a,!0,b);c=c&&f}for(e=0;!b.g&&e<d.length;e++)b.b=d[e],f=Yb(d[e],a,!1,b),c=
c&&f}return c}return Zb(a,new T(b,this))}function Tb(a){a=a[Mb];return a instanceof Ib?a:null}var $b="__closure_events_fn_"+(1E9*Math.random()>>>0);function Rb(a){if(z(a))return a;a[$b]||(a[$b]=function(b){return a.handleEvent(b)});return a[$b]};function ac(a,b){if(!z(a))if(a&&"function"==typeof a.handleEvent)a=B(a.handleEvent,a);else throw Error("Invalid listener argument");return 2147483647<Number(b)?-1:u.setTimeout(a,b||0)};function bc(a,b,c){S.call(this);this.B=null!=c?B(a,c):a;this.u=b;this.s=B(this.S,this);this.c=!1;this.g=0;this.h=this.a=null;this.j=[]}C(bc,S);h=bc.prototype;h.I=function(a){this.j=arguments;this.c=!1;this.a?this.h=wa()+this.u:this.a=ac(this.s,this.u)};h.Ra=function(){++this.g};h.Sa=function(){this.g&&(--this.g,!this.g&&this.c&&(this.c=!1,this.B.apply(null,this.j)))};h.o=function(){this.a&&(u.clearTimeout(this.a),this.a=null);this.h=null;this.c=!1;this.j=[];bc.w.o.call(this)};
h.S=function(){this.h?(this.a=ac(this.s,this.h-wa()),this.h=null):(this.a=null,this.g?this.c=!0:(this.c=!1,this.B.apply(null,this.j)))};var cc=!K||9<=Number(O),dc=!L&&!K||K&&9<=Number(O)||L&&N("1.9.1"),ec=K&&!N("9"),fc=K||hb||M;function U(a,b){this.x=v(a)?a:0;this.a=v(b)?b:0}h=U.prototype;h.cb=function(){return new U(this.x,this.a)};h.da=function(a){return a instanceof U&&(this==a?!0:this&&a?this.x==a.x&&this.a==a.a:!1)};h.ceil=function(){this.x=Math.ceil(this.x);this.a=Math.ceil(this.a);return this};h.floor=function(){this.x=Math.floor(this.x);this.a=Math.floor(this.a);return this};h.round=function(){this.x=Math.round(this.x);this.a=Math.round(this.a);return this};
h.fb=function(a,b){a instanceof U?(this.x+=a.x,this.a+=a.a):(this.x+=Number(a),x(b)&&(this.a+=b));return this};h.eb=function(a,b){b=x(b)?b:a;this.x*=a;this.a*=b;return this};h.zb=function(a,b){a=a*Math.PI/180;b=b||new U(0,0);var c=this.x,d=this.a,e=Math.cos(a);a=Math.sin(a);this.x=(c-b.x)*e-(d-b.a)*a+b.x;this.a=(c-b.x)*a+(d-b.a)*e+b.a};function V(a,b){this.width=a;this.height=b}h=V.prototype;h.gb=function(){return new V(this.width,this.height)};h.Ba=function(){return Math.max(this.width,this.height)};h.Oa=function(){return Math.min(this.width,this.height)};h.vb=function(){return 2*(this.width+this.height)};h.aspectRatio=function(){return this.width/this.height};h.lb=function(){return!(this.width*this.height)};h.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};
h.ha=function(a){return this.width<=a.width&&this.height<=a.height};h.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};h.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};function gc(a,b){var c=x(void 0)?void 0:b;a.width*=b;a.height*=c;return a}h.Bb=function(a){a=this.aspectRatio()<=a.aspectRatio()?a.width/this.width:a.height/this.height;return gc(this,a)};
h.Cb=function(a){a=this.aspectRatio()>a.aspectRatio()?a.width/this.width:a.height/this.height;return gc(this,a)};function hc(a){return a?new W(X(a)):xa||(xa=new W)}function ic(a,b){var c=b||document,d=null;c.getElementsByClassName?d=c.getElementsByClassName(a)[0]:d=jc(document,"*",a,b);return d||null}
function kc(a,b,c,d){a=d||a;var e=b&&"*"!=b?String(b).toUpperCase():"";if(a.querySelectorAll&&a.querySelector&&(e||c))return a.querySelectorAll(e+(c?"."+c:""));if(c&&a.getElementsByClassName){b=a.getElementsByClassName(c);if(e){a={};for(var f=d=0,k;k=b[f];f++)e==k.nodeName&&(a[d++]=k);a.length=d;return a}return b}b=a.getElementsByTagName(e||"*");if(c){a={};for(f=d=0;k=b[f];f++){e=k.className;var g;if(g="function"==typeof e.split)g=0<=ya(e.split(/\s+/),c);g&&(a[d++]=k)}a.length=d;return a}return b}
function jc(a,b,c,d){var e=d||a,f=b&&"*"!=b?String(b).toUpperCase():"";return e.querySelectorAll&&e.querySelector&&(f||c)?e.querySelector(f+(c?"."+c:"")):kc(a,b,c,d)[0]||null}function lc(a,b){Ca(b,function(c,d){c&&"object"==typeof c&&c.G&&(c=c.F());"style"==d?a.style.cssText=c:"class"==d?a.className=c:"for"==d?a.htmlFor=c:mc.hasOwnProperty(d)?a.setAttribute(mc[d],c):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,c):a[d]=c})}
var mc={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};function nc(a){a=a.document;a=oc(a)?a.documentElement:a.body;return new V(a.clientWidth,a.clientHeight)}function pc(a){return a.scrollingElement?a.scrollingElement:!M&&oc(a)?a.documentElement:a.body||a.documentElement}
function qc(a){return a.parentWindow||a.defaultView}function rc(a,b,c,d){function e(k){k&&b.appendChild(w(k)?a.createTextNode(k):k)}for(;d<c.length;d++){var f=c[d];sa(f)&&!sc(f)?za(tc(f)?Ba(f):f,e):e(f)}}function oc(a){return"CSS1Compat"==a.compatMode}function uc(a){for(var b;b=a.firstChild;)a.removeChild(b)}function Y(a){return a&&a.parentNode?a.parentNode.removeChild(a):null}function vc(a,b){for(;a&&1!=a.nodeType;)a=b?a.nextSibling:a.previousSibling;return a}
function sc(a){return A(a)&&0<a.nodeType}function wc(a){return A(a)&&1==a.nodeType}function xc(a,b){if(!a||!b)return!1;if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a}function yc(a,b){var c=a.parentNode;if(c==b)return-1;for(;b.parentNode!=c;)b=b.parentNode;return zc(b,a)}function zc(a,b){for(;b=b.previousSibling;)if(b==a)return-1;return 1}
function X(a){return 9==a.nodeType?a:a.ownerDocument||a.document}function Ac(a,b){if("textContent"in a)a.textContent=b;else if(3==a.nodeType)a.data=String(b);else if(a.firstChild&&3==a.firstChild.nodeType){for(;a.lastChild!=a.firstChild;)a.removeChild(a.lastChild);a.firstChild.data=String(b)}else uc(a),a.appendChild(X(a).createTextNode(String(b)))}function Bc(a,b,c,d){if(null!=a)for(a=a.firstChild;a;){if(b(a)&&(c.push(a),d)||Bc(a,b,c,d))return!0;a=a.nextSibling}return!1}
var Cc={SCRIPT:1,STYLE:1,HEAD:1,IFRAME:1,OBJECT:1},Dc={IMG:" ",BR:"\n"};function Ec(a){return Fc(a)&&Gc(a)}function Fc(a){return K&&!N("9")?(a=a.getAttributeNode("tabindex"),null!=a&&a.specified):a.hasAttribute("tabindex")}function Gc(a){a=a.tabIndex;return x(a)&&0<=a&&32768>a}
function Hc(a){if(ec&&null!==a&&"innerText"in a)a=a.innerText.replace(/(\r\n|\r|\n)/g,"\n");else{var b=[];Ic(a,b,!0);a=b.join("")}a=a.replace(/ \xAD /g," ").replace(/\xAD/g,"");a=a.replace(/\u200B/g,"");ec||(a=a.replace(/ +/g," "));" "!=a&&(a=a.replace(/^\s*/,""));return a}
function Ic(a,b,c){if(!(a.nodeName in Cc))if(3==a.nodeType)c?b.push(String(a.nodeValue).replace(/(\r\n|\r|\n)/g,"")):b.push(a.nodeValue);else if(a.nodeName in Dc)b.push(Dc[a.nodeName]);else for(a=a.firstChild;a;)Ic(a,b,c),a=a.nextSibling}function tc(a){if(a&&"number"==typeof a.length){if(A(a))return"function"==typeof a.item||"string"==typeof a.item;if(z(a))return"function"==typeof a.item}return!1}
function Jc(a,b,c,d){if(!b&&!c)return null;var e=b?String(b).toUpperCase():null;return Kc(a,function(f){var k;(k=!e||f.nodeName==e)&&!(k=!c)&&(k=w(f.className))&&(k=0<=ya(f.className.split(/\s+/),c));return k},!0,d)}function Kc(a,b,c,d){a&&!c&&(a=a.parentNode);for(c=0;a&&(null==d||c<=d);){if(b(a))return a;a=a.parentNode;c++}return null}function W(a){this.a=a||u.document||document}h=W.prototype;h.ta=hc;h.Db=function(a){this.a=a};h.qa=function(){return this.a};
h.N=function(a){return w(a)?this.a.getElementById(a):a};h.Ma=function(a){return w(a)?this.a.getElementById(a):a};h.X=W.prototype.N;h.Ya=function(a,b){return(b||this.a).getElementsByTagName(String(a))};h.O=function(a,b,c){return kc(this.a,a,b,c)};h.va=function(a,b,c){return jc(this.a,a,b,c)};h.wa=function(a,b){var c=(b=b||this.a)||document;return c.querySelectorAll&&c.querySelector?c.querySelectorAll("."+a):kc(document,"*",a,b)};h.ua=function(a,b){return ic(a,b||this.a)};
h.Na=function(a,b){return ic(a,b||this.a)};h.Y=W.prototype.O;h.Fb=lc;h.Qa=function(a){return nc(a||qc(this.a)||window)};h.ra=function(){var a=qc(this.a),b=a.document;var c=0;if(b){c=b.body;var d=b.documentElement;if(d&&c)if(a=nc(a).height,oc(b)&&d.scrollHeight)c=d.scrollHeight!=a?d.scrollHeight:d.offsetHeight;else{b=d.scrollHeight;var e=d.offsetHeight;d.clientHeight!=e&&(b=c.scrollHeight,e=c.offsetHeight);c=b>a?b>e?b:e:b<e?b:e}else c=0}return c};
h.M=function(a,b,c){var d=this.a,e=arguments,f=String(e[0]),k=e[1];if(!cc&&k&&(k.name||k.type)){f=["<",f];k.name&&f.push(' name="',$a(k.name),'"');if(k.type){f.push(' type="',$a(k.type),'"');var g={};Ea(g,k);delete g.type;k=g}f.push(">");f=f.join("")}f=d.createElement(f);k&&(w(k)?f.className=k:y(k)?f.className=k.join(" "):lc(f,k));2<e.length&&rc(d,f,e,2);return f};h.Z=W.prototype.M;h.Xa=function(a){return this.a.createTextNode(String(a))};
h.ca=function(a,b,c){var d=this.a;c=!!c;for(var e=d.createElement("TABLE"),f=e.appendChild(d.createElement("TBODY")),k=0;k<a;k++){for(var g=d.createElement("TR"),m=0;m<b;m++){var l=d.createElement("TD");c&&Ac(l,"\u00a0");g.appendChild(l)}f.appendChild(g)}return e};
h.Ab=function(a){var b=this.a;var c=b.createElement("DIV");K?(a=Wa(Xa,a),Za(c,a),c.removeChild(c.firstChild)):Za(c,a);if(1==c.childNodes.length)c=c.removeChild(c.firstChild);else{for(b=b.createDocumentFragment();c.firstChild;)b.appendChild(c.firstChild);c=b}return c};h.sa=function(){return pc(this.a)};h.ja=function(a){a=a||this.a;try{var b=a&&a.activeElement;var c=b&&b.nodeName?b:null}catch(d){c=null}return c};h.Ua=function(a,b){a.appendChild(b)};h.Ta=function(a,b){rc(X(a),a,arguments,1)};
h.Va=function(a){if(1!=a.nodeType)return!1;switch(a.tagName){case "APPLET":case "AREA":case "BASE":case "BR":case "COL":case "COMMAND":case "EMBED":case "FRAME":case "HR":case "IMG":case "INPUT":case "IFRAME":case "ISINDEX":case "KEYGEN":case "LINK":case "NOFRAMES":case "NOSCRIPT":case "META":case "OBJECT":case "PARAM":case "SCRIPT":case "SOURCE":case "STYLE":case "TRACK":case "WBR":return!1}return!0};h.yb=uc;h.jb=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b)};
h.ib=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b.nextSibling)};h.hb=function(a,b,c){a.insertBefore(b,a.childNodes[c]||null)};h.Za=Y;h.$a=function(a,b){var c=b.parentNode;c&&c.replaceChild(a,b)};h.ia=function(a){var b,c=a.parentNode;if(c&&11!=c.nodeType){if(a.removeNode)return a.removeNode(!1);for(;b=a.firstChild;)c.insertBefore(b,a);return Y(a)}};h.oa=function(a){return dc&&void 0!=a.children?a.children:Aa(a.childNodes,function(b){return 1==b.nodeType})};
h.xa=function(a){return v(a.firstElementChild)?a.firstElementChild:vc(a.firstChild,!0)};h.Aa=function(a){return v(a.lastElementChild)?a.lastElementChild:vc(a.lastChild,!1)};h.Ca=function(a){return v(a.nextElementSibling)?a.nextElementSibling:vc(a.nextSibling,!0)};h.Ka=function(a){return v(a.previousElementSibling)?a.previousElementSibling:vc(a.previousSibling,!1)};h.Da=function(a){if(!a)return null;if(a.firstChild)return a.firstChild;for(;a&&!a.nextSibling;)a=a.parentNode;return a?a.nextSibling:null};
h.La=function(a){if(!a)return null;if(!a.previousSibling)return a.parentNode;for(a=a.previousSibling;a&&a.lastChild;)a=a.lastChild;return a};h.ob=sc;h.kb=wc;h.qb=function(a){return A(a)&&a.window==a};h.Ja=function(a){var b;if(fc&&!(K&&N("9")&&!N("10")&&u.SVGElement&&a instanceof u.SVGElement)&&(b=a.parentElement))return b;b=a.parentNode;return wc(b)?b:null};h.Wa=xc;
h.ba=function(a,b){if(a==b)return 0;if(a.compareDocumentPosition)return a.compareDocumentPosition(b)&2?1:-1;if(K&&!(9<=Number(O))){if(9==a.nodeType)return-1;if(9==b.nodeType)return 1}if("sourceIndex"in a||a.parentNode&&"sourceIndex"in a.parentNode){var c=1==a.nodeType,d=1==b.nodeType;if(c&&d)return a.sourceIndex-b.sourceIndex;var e=a.parentNode,f=b.parentNode;return e==f?zc(a,b):!c&&xc(e,b)?-1*yc(a,b):!d&&xc(f,a)?yc(b,a):(c?a.sourceIndex:e.sourceIndex)-(d?b.sourceIndex:f.sourceIndex)}d=X(a);c=d.createRange();
c.selectNode(a);c.collapse(!0);a=d.createRange();a.selectNode(b);a.collapse(!0);return c.compareBoundaryPoints(u.Range.START_TO_END,a)};h.ea=function(a){var b,c=arguments.length;if(!c)return null;if(1==c)return arguments[0];var d=[],e=Infinity;for(b=0;b<c;b++){for(var f=[],k=arguments[b];k;)f.unshift(k),k=k.parentNode;d.push(f);e=Math.min(e,f.length)}f=null;for(b=0;b<e;b++){k=d[0][b];for(var g=1;g<c;g++)if(k!=d[g][b])return f;f=k}return f};h.Ia=X;h.ya=function(a){return a.contentDocument||a.contentWindow.document};
h.za=function(a){try{var b;if(!(b=a.contentWindow)){if(a.contentDocument){var c=a.contentDocument;var d=c?qc(c):window}else d=null;b=d}return b}catch(e){}return null};h.Gb=Ac;h.Ha=function(a){if("outerHTML"in a)return a.outerHTML;var b=X(a).createElement("DIV");b.appendChild(a.cloneNode(!0));return b.innerHTML};h.fa=function(a,b){var c=[];return Bc(a,b,c,!0)?c[0]:void 0};h.ga=function(a,b){var c=[];Bc(a,b,c,!1);return c};h.nb=Ec;h.Eb=function(a,b){b?a.tabIndex=0:(a.tabIndex=-1,a.removeAttribute("tabIndex"))};
h.mb=function(a){var b;if((b="A"==a.tagName&&a.hasAttribute("href")||"INPUT"==a.tagName||"TEXTAREA"==a.tagName||"SELECT"==a.tagName||"BUTTON"==a.tagName?!a.disabled&&(!Fc(a)||Gc(a)):Ec(a))&&K){var c;!z(a.getBoundingClientRect)||K&&null==a.parentElement?c={height:a.offsetHeight,width:a.offsetWidth}:c=a.getBoundingClientRect();a=null!=c&&0<c.height&&0<c.width}else a=b;return a};h.Pa=Hc;h.Fa=function(a){return Hc(a).length};
h.Ga=function(a,b){b=b||X(a).body;for(var c=[];a&&a!=b;){for(var d=a;d=d.previousSibling;)c.unshift(Hc(d));a=a.parentNode}return c.join("").replace(/^[\s\xa0]+/,"").replace(/ +/g," ").length};
h.Ea=function(a,b,c){a=[a];for(var d=0,e=null;0<a.length&&d<b;)if(e=a.pop(),!(e.nodeName in Cc))if(3==e.nodeType){var f=e.nodeValue.replace(/(\r\n|\r|\n)/g,"").replace(/ +/g," ");d+=f.length}else if(e.nodeName in Dc)d+=Dc[e.nodeName].length;else for(f=e.childNodes.length-1;0<=f;f--)a.push(e.childNodes[f]);A(c)&&(c.xb=e?e.nodeValue.length+b-d-1:0,c.node=e);return e};h.pb=tc;h.ma=Jc;h.la=function(a,b,c){return Jc(a,null,b,c)};h.ka=Kc;h.na=function(a){return a.getContext("2d")};function Lc(a){S.call(this);this.c=a;this.a={}}C(Lc,S);var Mc=[];h=Lc.prototype;h.m=function(a,b,c,d){return Nc(this,a,b,c,d)};h.sb=function(a,b,c,d,e){return Nc(this,a,b,c,d,e)};function Nc(a,b,c,d,e,f){y(c)||(c&&(Mc[0]=c.toString()),c=Mc);for(var k=0;k<c.length;k++){var g=Pb(b,c[k],d||a.handleEvent,e||!1,f||a.c||a);if(!g)break;a.a[g.key]=g}return a}h.bb=function(a,b,c,d){return Oc(this,a,b,c,d)};h.rb=function(a,b,c,d,e){return Oc(this,a,b,c,d,e)};
function Oc(a,b,c,d,e,f){if(y(c))for(var k=0;k<c.length;k++)Oc(a,b,c[k],d,e,f);else{b=Qb(b,c,d||a.handleEvent,e,f||a.c||a);if(!b)return a;a.a[b.key]=b}return a}h.tb=function(a,b,c,d){b.m(a,c,d,this.c||this);return this};h.ub=function(a,b,c,d,e){b.m(a,c,d,e||this.c||this);return this};h.ab=function(){var a=0,b;for(b in this.a)Object.prototype.hasOwnProperty.call(this.a,b)&&a++;return a};
h.K=function(a,b,c,d,e){if(y(b))for(var f=0;f<b.length;f++)this.K(a,b[f],c,d,e);else c=c||this.handleEvent,d=A(d)?!!d.capture:!!d,e=e||this.c||this,c=Rb(c),d=!!d,b=a&&a[Eb]?Lb(a.g,String(b),c,d,e):a?(a=Tb(a))?Lb(a,b,c,d,e):null:null,b&&(Xb(b),delete this.a[b.key])};h.Hb=function(a,b,c,d,e){b.K(a,c,d,e||this.c||this,this);return this};function Pc(a){Ca(a.a,function(b,c){this.a.hasOwnProperty(c)&&Xb(b)},a);a.a={}}h.o=function(){Lc.w.o.call(this);Pc(this)};
h.handleEvent=function(){throw Error("EventHandler.handleEvent not implemented");};function Qc(a){a=(a||Rc).U;a=null!=a&&a.A===ab?a:a instanceof F?sb(G(a).toString(),a.a()):sb($a(String(String(a))),rb(a));var b=sb("<devsite-tooltip-msg>"+a+"</devsite-tooltip-msg>");a=hc().a.createElement("DIV");if(A(b))if(b instanceof J)if(b.A===cb)b=H(b.toString());else{if(b.A!==ab)throw Error("Sanitized content was not of kind TEXT or HTML.");b=I(b.toString(),b.D||null)}else b=H("zSoyz");else b=H(String(b));Za(a,b);1==a.childNodes.length&&(b=a.firstChild,1==b.nodeType&&(a=b));return a}
var Rc={};function Sc(a){try{var b=a.getBoundingClientRect()}catch(c){return{left:0,top:0,right:0,bottom:0}}K&&a.ownerDocument.body&&(a=a.ownerDocument,b.left-=a.documentElement.clientLeft+a.body.clientLeft,b.top-=a.documentElement.clientTop+a.body.clientTop);return b}
function Tc(a){var b=X(a),c=new U(0,0);var d=b?X(b):document;d=!K||9<=Number(O)||oc(hc(d).a)?d.documentElement:d.body;if(a==d)return c;a=Sc(a);d=hc(b).a;b=pc(d);d=qc(d);b=K&&N("10")&&d.pageYOffset!=b.scrollTop?new U(b.scrollLeft,b.scrollTop):new U(d.pageXOffset||b.scrollLeft,d.pageYOffset||b.scrollTop);c.x=a.left+b.x;c.a=a.top+b.a;return c}
function Uc(a){var b=Vc;a:{var c=X(a);if(c.defaultView&&c.defaultView.getComputedStyle&&(c=c.defaultView.getComputedStyle(a,null))){c=c.display||c.getPropertyValue("display")||"";break a}c=""}c||(c=a.currentStyle?a.currentStyle.display:null);if("none"!=(c||a.style&&a.style.display))return b(a);c=a.style;var d=c.display,e=c.visibility,f=c.position;c.visibility="hidden";c.position="absolute";c.display="inline";a=b(a);c.display=d;c.position=f;c.visibility=e;return a}
function Vc(a){var b=a.offsetWidth,c=a.offsetHeight,d=M&&!b&&!c;return v(b)&&!d||!a.getBoundingClientRect?new V(b,c):(a=Sc(a),new V(a.right-a.left,a.bottom-a.top))};var Wc=["dl.google.com"],Xc="abc.xyz admob.com android.com blogger.com blogspot.com chrome.com chromium.org domains.google doubleclick.com feedburner.com g.co ggpht.com gmail.com gmodules.com goo.gl google.com google.org googleapis.com googleapps.com googlecode.com googledrive.com googlemail.com googlesource.com googlesyndication.com googletagmanager.com googleusercontent.com gv.com keyhole.com madewithcode.com panoramio.com urchin.com withgoogle.com youtu.be youtube.com ytimg.com".split(" ");
function Z(){var a=R.call(this)||this;a.b=new Lc;a.a=null;a.c=null;a.h=new bc(function(){return Yc(a)},250);return a}ha(Z,R);Z.prototype.connectedCallback=function(){document.body.hasAttribute("touch")?Y(this):(Zc(this),this.h.I())};Z.prototype.disconnectedCallback=function(){R.prototype.disconnectedCallback.call(this);Pc(this.b)};
function Zc(a){a.b.m(document.body,"devsite-content-updated",function(){return a.h.I()});a.b.m(document.body,"onpointermove"in window?"pointermove":"mousemove",function(b){for(b=b.target;b&&(!b.hasAttribute||!b.hasAttribute("data-title"));)b=b.parentNode;b&&!b.hasAttribute("no-tooltip")?$c(a,b):ad(a)});a.b.m(document.body,["devsite-sticky-scroll","devsite-sticky-resize"],function(){return ad(a)})}
function $c(a,b){if(a.a!==b){ad(a);var c=b.getAttribute("data-title"),d=Qc({U:c});d.style.opacity=0;document.body.appendChild(d);var e=nc(window),f=Uc(b),k=Uc(d),g=Tc(b);c=g.a+f.height;f=g.x+f.width/2-k.width/2;k.width>e.width?f=0:(f=Math.max(f,8),e=e.width-(f+k.width+8),0>e&&(f=f+e-8));d.style.top=c+"px";d.style.left=f+"px";a.a=b;a.c=d;window.requestAnimationFrame(function(){d.style.opacity=1})}}
function ad(a){if(a.a){a.a=null;var b=a.c;a.c=null;Qb(b,Bb,function(){Y(b);uc(b)});window.setTimeout(function(){Y(b);uc(b)},1E3);b.style.opacity=0}}
function Yc(a){Array.from(document.querySelectorAll(".devsite-nav-text, .devsite-nav-title, devsite-tabs a[title], .devsite-nav-item a[title]")).forEach(function(b){b.clientWidth<b.scrollWidth?b.setAttribute("data-title",b.getAttribute("title")||b.textContent.trim()):b.removeAttribute("data-title");b.removeAttribute("title")});["title","data-tooltip"].forEach(function(b){Array.from(document.querySelectorAll("["+b+"]")).forEach(function(c){var d=c.getAttribute(b);d&&d.trim()&&(c.setAttribute("data-title",
d.trim()),c.removeAttribute(b))})});a.hasAttribute("blocked-link")&&Array.from(document.querySelectorAll("a")).forEach(function(b){if(b.hasAttribute("href")){for(var c=(new URL(b.getAttribute("href"),document.location.origin)).hostname.replace("www.",""),d=0;d<Wc.length;d++)if(-1!==c.indexOf(Wc[d]))return;for(d=0;d<Xc.length;d++)if(-1!==c.indexOf(Xc[d])){b.setAttribute("data-title","This link may not be accessible in your region.");break}}})}Z.prototype.disconnectedCallback=Z.prototype.disconnectedCallback;
Z.prototype.connectedCallback=Z.prototype.connectedCallback;try{window.customElements.define("devsite-tooltip",Z)}catch(a){console.warn("devsite.app.customElement.DevsiteTooltip",a)};}).call(this);
