(function(){'use strict';var g,aa="function"==typeof Object.create?Object.create:function(a){function b(){}b.prototype=a;return new b},ba;if("function"==typeof Object.setPrototypeOf)ba=Object.setPrototypeOf;else{var ca;a:{var da={fa:!0},fa={};try{fa.__proto__=da;ca=fa.fa;break a}catch(a){}ca=!1}ba=ca?function(a,b){a.__proto__=b;if(a.__proto__!==b)throw new TypeError(a+" is not extensible");return a}:null}var ha=ba;
function ia(a,b){a.prototype=aa(b.prototype);a.prototype.constructor=a;if(ha)ha(a,b);else for(var c in b)if("prototype"!=c)if(Object.defineProperties){var d=Object.getOwnPropertyDescriptor(b,c);d&&Object.defineProperty(a,c,d)}else a[c]=b[c];a.w=b.prototype}var ja="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this,ka="function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};
function la(a,b){if(b){var c=ja;a=a.split(".");for(var d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&ka(c,a,{configurable:!0,writable:!0,value:b})}}la("Object.setPrototypeOf",function(a){return a||ha});
var na=function(){function a(){function c(){}new c;Reflect.construct(c,[],function(){});return new c instanceof c}if("undefined"!=typeof Reflect&&Reflect.construct){if(a())return Reflect.construct;var b=Reflect.construct;return function(c,d,e){c=b(c,d);e&&Reflect.setPrototypeOf(c,e.prototype);return c}}return function(c,d,e){void 0===e&&(e=c);e=aa(e.prototype||Object.prototype);return Function.prototype.apply.call(c,e,d)||e}}();la("Reflect.construct",function(){return na});
la("Array.from",function(a){return a?a:function(b,c,d){c=null!=c?c:function(p){return p};var e=[],f="undefined"!=typeof Symbol&&Symbol.iterator&&b[Symbol.iterator];if("function"==typeof f){b=f.call(b);for(var h=0;!(f=b.next()).done;)e.push(c.call(d,f.value,h++))}else for(f=b.length,h=0;h<f;h++)e.push(c.call(d,b[h],h));return e}});var I=this||self;function J(a){return void 0!==a}function K(a){return"string"==typeof a}function oa(a){return"number"==typeof a}function pa(){}
function qa(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b}function M(a){return"array"==qa(a)}function ra(a){var b=qa(a);return"array"==b||"object"==b&&"number"==typeof a.length}function N(a){var b=typeof a;return"object"==b&&null!=a||"function"==b}function sa(a,b,c){return a.call.apply(a.bind,arguments)}
function ta(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,d);return a.apply(b,e)}}return function(){return a.apply(b,arguments)}}function ua(a,b,c){Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ua=sa:ua=ta;return ua.apply(null,arguments)}
function va(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var d=c.slice();d.push.apply(d,arguments);return a.apply(this,d)}}function O(a,b){function c(){}c.prototype=b.prototype;a.w=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.qa=function(d,e,f){for(var h=Array(arguments.length-2),p=2;p<arguments.length;p++)h[p-2]=arguments[p];return b.prototype[e].apply(d,h)}};function wa(a){if(Error.captureStackTrace)Error.captureStackTrace(this,wa);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a));this.b=!0}O(wa,Error);wa.prototype.name="CustomError";var xa;function ya(a,b){for(var c=a.split("%s"),d="",e=c.length-1,f=0;f<e;f++)d+=c[f]+(f<b.length?b[f]:"%s");wa.call(this,d+c[e]);this.a=a}O(ya,wa);ya.prototype.name="AssertionError";var za=Array.prototype.indexOf?function(a,b){return Array.prototype.indexOf.call(a,b,void 0)}:function(a,b){if(K(a))return K(b)&&1==b.length?a.indexOf(b,0):-1;for(var c=0;c<a.length;c++)if(c in a&&a[c]===b)return c;return-1},P=Array.prototype.forEach?function(a,b,c){Array.prototype.forEach.call(a,b,c)}:function(a,b,c){for(var d=a.length,e=K(a)?a.split(""):a,f=0;f<d;f++)f in e&&b.call(c,e[f],f,a)},Aa=Array.prototype.filter?function(a,b){return Array.prototype.filter.call(a,b,void 0)}:function(a,b){for(var c=
a.length,d=[],e=0,f=K(a)?a.split(""):a,h=0;h<c;h++)if(h in f){var p=f[h];b.call(void 0,p,h,a)&&(d[e++]=p)}return d},Ba=Array.prototype.map?function(a,b){return Array.prototype.map.call(a,b,void 0)}:function(a,b){for(var c=a.length,d=Array(c),e=K(a)?a.split(""):a,f=0;f<c;f++)f in e&&(d[f]=b.call(void 0,e[f],f,a));return d};function Ca(a,b){b=za(a,b);var c;(c=0<=b)&&Array.prototype.splice.call(a,b,1);return c}
function Da(a){var b=a.length;if(0<b){for(var c=Array(b),d=0;d<b;d++)c[d]=a[d];return c}return[]}function Fa(a,b,c,d){Array.prototype.splice.apply(a,Ga(arguments,1))}function Ga(a,b,c){return 2>=arguments.length?Array.prototype.slice.call(a,b):Array.prototype.slice.call(a,b,c)};var Ha=String.prototype.trim?function(a){return a.trim()}:function(a){return/^[\s\xa0]*([\s\S]*?)[\s\xa0]*$/.exec(a)[1]};
function Ia(a,b){if(b)a=a.replace(Ja,"&amp;").replace(Ka,"&lt;").replace(La,"&gt;").replace(Ma,"&quot;").replace(Na,"&#39;").replace(Pa,"&#0;");else{if(!Qa.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(Ja,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(Ka,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(La,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(Ma,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(Na,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(Pa,"&#0;"))}return a}
var Ja=/&/g,Ka=/</g,La=/>/g,Ma=/"/g,Na=/'/g,Pa=/\x00/g,Qa=/[\x00&<>"']/;function Ra(a,b){return a<b?-1:a>b?1:0};var Q;a:{var Sa=I.navigator;if(Sa){var Ta=Sa.userAgent;if(Ta){Q=Ta;break a}}Q=""};function Ua(a,b,c){for(var d in a)b.call(c,a[d],d,a)}function Va(a,b){for(var c in a)if(b.call(void 0,a[c],c,a))return!0;return!1}function Wa(a,b,c){if(null!==a&&b in a)throw Error('The object already contains the key "'+b+'"');a[b]=c}function Xa(a,b){return null!==a&&b in a?a[b]:void 0}var Ya="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");
function Za(a,b){for(var c,d,e=1;e<arguments.length;e++){d=arguments[e];for(c in d)a[c]=d[c];for(var f=0;f<Ya.length;f++)c=Ya[f],Object.prototype.hasOwnProperty.call(d,c)&&(a[c]=d[c])}};var $a={area:!0,base:!0,br:!0,col:!0,command:!0,embed:!0,hr:!0,img:!0,input:!0,keygen:!0,link:!0,meta:!0,param:!0,source:!0,track:!0,wbr:!0};function ab(a,b){this.a=a===bb&&b||"";this.b=cb}ab.prototype.u=!0;ab.prototype.l=function(){return this.a};ab.prototype.toString=function(){return"Const{"+this.a+"}"};function db(a){return a instanceof ab&&a.constructor===ab&&a.b===cb?a.a:"type_error:Const"}var cb={},bb={};function eb(){this.a="";this.c=null;this.b=fb}g=eb.prototype;g.u=!0;g.l=function(){return this.a.toString()};g.R=!0;g.C=function(){return 1};g.ra=function(a,b){var c=gb.exec(hb(this).toString()),d=c[3]||"";a=c[1]+ib("?",c[2]||"",a)+ib("#",d,b);b=new eb;b.a=a;return b};function hb(a){return a instanceof eb&&a.constructor===eb&&a.b===fb?a.a:"type_error:TrustedResourceUrl"}var gb=/^([^?#]*)(\?[^#]*)?(#[\s\S]*)?/,fb={};
function ib(a,b,c){if(null==c)return b;if(K(c))return c?a+encodeURIComponent(c):"";for(var d in c){var e=c[d];e=M(e)?e:[e];for(var f=0;f<e.length;f++){var h=e[f];null!=h&&(b||(b=a),b+=(b.length>a.length?"&":"")+encodeURIComponent(d)+"="+encodeURIComponent(String(h)))}}return b};function R(){this.a="";this.b=jb}R.prototype.u=!0;R.prototype.l=function(){return this.a.toString()};R.prototype.R=!0;R.prototype.C=function(){return 1};function kb(a){return a instanceof R&&a.constructor===R&&a.b===jb?a.a:"type_error:SafeUrl"}var lb=/^(?:(?:https?|mailto|ftp):|[^:/?#]*(?:[/?#]|$))/i;function mb(a){if(a instanceof R)return a;a="object"==typeof a&&a.u?a.l():String(a);lb.test(a)||(a="about:invalid#zClosurez");return nb(a)}var jb={};function nb(a){var b=new R;b.a=a;return b}nb("about:blank");function ob(){this.a="";this.b=pb}ob.prototype.u=!0;var pb={};ob.prototype.l=function(){return this.a};function qb(a){var b=new ob;b.a=a;return b}var sb=qb("");
function tb(a){if(a instanceof R)return'url("'+kb(a).toString().replace(/</g,"%3c").replace(/[\\"]/g,"\\$&")+'")';if(a instanceof ab)a=db(a);else{a=String(a);var b=a.replace(ub,"$1").replace(ub,"$1").replace(vb,"url");if(wb.test(b)){if(b=!xb.test(a)){for(var c=b=!0,d=0;d<a.length;d++){var e=a.charAt(d);"'"==e&&c?b=!b:'"'==e&&b&&(c=!c)}b=b&&c&&yb(a)}a=b?zb(a):"zClosurez"}else a="zClosurez"}if(/[{;}]/.test(a))throw new ya("Value does not allow [{;}], got: %s.",[a]);return a}
function yb(a){for(var b=!0,c=/^[-_a-zA-Z0-9]$/,d=0;d<a.length;d++){var e=a.charAt(d);if("]"==e){if(b)return!1;b=!0}else if("["==e){if(!b)return!1;b=!1}else if(!b&&!c.test(e))return!1}return b}var wb=/^[-,."'%_!# a-zA-Z0-9\[\]]+$/,vb=/\b(url\([ \t\n]*)('[ -&(-\[\]-~]*'|"[ !#-\[\]-~]*"|[!#-&*-\[\]-~]*)([ \t\n]*\))/g,ub=/\b(hsl|hsla|rgb|rgba|matrix|calc|minmax|fit-content|repeat|(rotate|scale|translate)(X|Y|Z|3d)?)\([-+*/0-9a-z.%\[\], ]+\)/g,xb=/\/\*/;
function zb(a){return a.replace(vb,function(b,c,d,e){var f="";d=d.replace(/^(['"])(.*)\1$/,function(h,p,D){f=p;return D});b=mb(d).l();return c+f+b+f+e})};function S(){this.a="";this.c=Ab;this.b=null}S.prototype.R=!0;S.prototype.C=function(){return this.b};S.prototype.u=!0;S.prototype.l=function(){return this.a.toString()};function Bb(a){return a instanceof S&&a.constructor===S&&a.c===Ab?a.a:"type_error:SafeHtml"}function Cb(a){if(a instanceof S)return a;var b="object"==typeof a,c=null;b&&a.R&&(c=a.C());a=Ia(b&&a.u?a.l():String(a));return Db(a,c)}
var Eb=/^[a-zA-Z0-9-]+$/,Fb={action:!0,cite:!0,data:!0,formaction:!0,href:!0,manifest:!0,poster:!0,src:!0},Gb={APPLET:!0,BASE:!0,EMBED:!0,IFRAME:!0,LINK:!0,MATH:!0,META:!0,OBJECT:!0,SCRIPT:!0,STYLE:!0,SVG:!0,TEMPLATE:!0};
function Hb(a){if(!Eb.test("input"))throw Error("Invalid tag name <input>.");if("INPUT"in Gb)throw Error("Tag name <input> is not allowed for SafeHtml.");var b=null,c="";if(a)for(D in a){if(!Eb.test(D))throw Error('Invalid attribute name "'+D+'".');var d=a[D];if(null!=d){var e=D;var f=d;if(f instanceof ab)f=db(f);else if("style"==e.toLowerCase()){d=void 0;if(!N(f))throw Error('The "style" attribute requires goog.html.SafeStyle or map of style properties, '+typeof f+" given: "+f);if(!(f instanceof
ob)){var h="";for(d in f){if(!/^[-_a-zA-Z0-9]+$/.test(d))throw Error("Name allows only [-_a-zA-Z0-9], got: "+d);var p=f[d];null!=p&&(p=M(p)?Ba(p,tb).join(" "):tb(p),h+=d+":"+p+";")}f=h?qb(h):sb}f=f instanceof ob&&f.constructor===ob&&f.b===pb?f.a:"type_error:SafeStyle"}else{if(/^on/i.test(e))throw Error('Attribute "'+e+'" requires goog.string.Const value, "'+f+'" given.');if(e.toLowerCase()in Fb)if(f instanceof eb)f=hb(f).toString();else if(f instanceof R)f=kb(f).toString();else if(K(f))f=mb(f).l();
else throw Error('Attribute "'+e+'" on tag "input" requires goog.html.SafeUrl, goog.string.Const, or string, value "'+f+'" given.');}f.u&&(f=f.l());e=e+'="'+Ia(String(f))+'"';c+=" "+e}}var D="<input"+c;c=void 0;null!=c?M(c)||(c=[c]):c=[];!0===$a.input?D+=">":(b=Ib(c),D+=">"+Bb(b).toString()+"</input>",b=b.C());(a=a&&a.dir)&&(/^(ltr|rtl|auto)$/i.test(a)?b=0:b=null);return Db(D,b)}
function Jb(a){function b(f){M(f)?P(f,b):(f=Cb(f),e.push(Bb(f).toString()),f=f.C(),0==d?d=f:0!=f&&d!=f&&(d=null))}var c=Cb(Kb),d=c.C(),e=[];P(a,b);return Db(e.join(Bb(c).toString()),d)}function Ib(a){return Jb(Array.prototype.slice.call(arguments))}var Ab={};function Db(a,b){var c=new S;c.a=a;c.b=b;return c}Db("<!DOCTYPE html>",0);var Kb=Db("",0),Lb=Db("<br>",0);var Mb=function(a){var b=!1,c;return function(){b||(c=a(),b=!0);return c}}(function(){var a=document.createElement("div"),b=document.createElement("div");b.appendChild(document.createElement("div"));a.appendChild(b);b=a.firstChild.firstChild;a.innerHTML=Bb(Kb);return!b.parentElement});function Nb(a,b){if(Mb())for(;a.lastChild;)a.removeChild(a.lastChild);a.innerHTML=Bb(b)}function Ob(a,b){Nb(a,b)};function Pb(a){return a=Ia(a,void 0)};function Qb(a){Qb[" "](a);return a}Qb[" "]=pa;function Rb(a,b){var c=Sb;return Object.prototype.hasOwnProperty.call(c,a)?c[a]:c[a]=b(a)};var Tb=-1!=Q.indexOf("Opera"),T=-1!=Q.indexOf("Trident")||-1!=Q.indexOf("MSIE"),Ub=-1!=Q.indexOf("Edge"),Vb=-1!=Q.indexOf("Gecko")&&!(-1!=Q.toLowerCase().indexOf("webkit")&&-1==Q.indexOf("Edge"))&&!(-1!=Q.indexOf("Trident")||-1!=Q.indexOf("MSIE"))&&-1==Q.indexOf("Edge"),Wb=-1!=Q.toLowerCase().indexOf("webkit")&&-1==Q.indexOf("Edge"),Xb=-1!=Q.indexOf("Macintosh");function Yb(){var a=I.document;return a?a.documentMode:void 0}var Zb;
a:{var $b="",ac=function(){var a=Q;if(Vb)return/rv:([^\);]+)(\)|;)/.exec(a);if(Ub)return/Edge\/([\d\.]+)/.exec(a);if(T)return/\b(?:MSIE|rv)[: ]([^\);]+)(\)|;)/.exec(a);if(Wb)return/WebKit\/(\S+)/.exec(a);if(Tb)return/(?:Version)[ \/]?(\S+)/.exec(a)}();ac&&($b=ac?ac[1]:"");if(T){var bc=Yb();if(null!=bc&&bc>parseFloat($b)){Zb=String(bc);break a}}Zb=$b}var cc=Zb,Sb={};
function dc(a){return Rb(a,function(){for(var b=0,c=Ha(String(cc)).split("."),d=Ha(String(a)).split("."),e=Math.max(c.length,d.length),f=0;0==b&&f<e;f++){var h=c[f]||"",p=d[f]||"";do{h=/(\d*)(\D*)(.*)/.exec(h)||["","","",""];p=/(\d*)(\D*)(.*)/.exec(p)||["","","",""];if(0==h[0].length&&0==p[0].length)break;b=Ra(0==h[1].length?0:parseInt(h[1],10),0==p[1].length?0:parseInt(p[1],10))||Ra(0==h[2].length,0==p[2].length)||Ra(h[2],p[2]);h=h[3];p=p[3]}while(0==b)}return 0<=b})}var ec;var fc=I.document;
ec=fc&&T?Yb()||("CSS1Compat"==fc.compatMode?parseInt(cc,10):5):void 0;var gc="StopIteration"in I?I.StopIteration:{message:"StopIteration",stack:""};function hc(){}hc.prototype.next=function(){throw gc;};hc.prototype.H=function(){return this};function ic(a){if(a instanceof hc)return a;if("function"==typeof a.H)return a.H(!1);if(ra(a)){var b=0,c=new hc;c.next=function(){for(;;){if(b>=a.length)throw gc;if(b in a)return a[b++];b++}};return c}throw Error("Not implemented");}
function jc(a,b){if(ra(a))try{P(a,b,void 0)}catch(c){if(c!==gc)throw c;}else{a=ic(a);try{for(;;)b.call(void 0,a.next(),void 0,a)}catch(c){if(c!==gc)throw c;}}}function kc(a){if(ra(a))return Da(a);a=ic(a);var b=[];jc(a,function(c){b.push(c)});return b};var lc={},mc={},nc={};function oc(){throw Error("Do not instantiate directly");}oc.prototype.X=null;oc.prototype.b=function(){return this.a};oc.prototype.toString=function(){return this.a};oc.prototype.c=function(){if(this.O!==mc)throw Error("Sanitized content was not of kind URI.");return nb(this.toString())};function pc(){oc.call(this)}O(pc,oc);pc.prototype.O=lc;var qc=function(a){function b(c){this.a=c}b.prototype=a.prototype;return function(c,d){c=new b(String(c));void 0!==d&&(c.X=d);return c}}(pc),rc={"\x00":"&#0;","\t":"&#9;","\n":"&#10;","\x0B":"&#11;","\f":"&#12;","\r":"&#13;"," ":"&#32;",'"':"&quot;","&":"&amp;","'":"&#39;","-":"&#45;","/":"&#47;","<":"&lt;","=":"&#61;",">":"&gt;","`":"&#96;","\u0085":"&#133;","\u00a0":"&#160;","\u2028":"&#8232;","\u2029":"&#8233;"};function sc(a){return rc[a]}var tc=/[\x00\x22\x27\x3c\x3e]/g;/*
 Copyright (C) 2006 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
window.PR_SHOULD_USE_CONTINUATION=!0;window.PR_TAB_WIDTH=8;window.PR_normalizedHtml=void 0;window.PR=void 0;window.prettyPrintOne=void 0;window.prettyPrint=void 0;window._pr_isIE6=function(){var a=navigator&&navigator.userAgent&&navigator.userAgent.match(/\bMSIE ([678])\./);a=a?+a[1]:!1;window._pr_isIE6=function(){return a};return a};
(function(){function a(l){return l.replace(Ec,"&amp;").replace(Fc,"&lt;").replace(Gc,"&gt;")}function b(l,r,u){switch(l.nodeType){case 1:var w=l.tagName.toLowerCase();r.push("<",w);var z=l.attributes,H=z.length;if(H){if(u){for(var C=[],x=H;0<=--x;)C[x]=z[x];C.sort(function(v,E){return v.name<E.name?-1:v.name===E.name?0:1});z=C}for(x=0;x<H;++x)C=z[x],C.specified&&r.push(" ",C.name.toLowerCase(),'="',C.value.replace(Ec,"&amp;").replace(Fc,"&lt;").replace(Gc,"&gt;").replace(de,"&quot;"),'"')}r.push(">");
for(z=l.firstChild;z;z=z.nextSibling)b(z,r,u);!l.firstChild&&/^(?:br|link|img)$/.test(w)||r.push("</",w,">");break;case 3:case 4:r.push(a(l.nodeValue))}}function c(l){function r(m){if("\\"!==m.charAt(0))return m.charCodeAt(0);switch(m.charAt(1)){case "b":return 8;case "t":return 9;case "n":return 10;case "v":return 11;case "f":return 12;case "r":return 13;case "u":case "x":return parseInt(m.substring(2),16)||m.charCodeAt(1);case "0":case "1":case "2":case "3":case "4":case "5":case "6":case "7":return parseInt(m.substring(1),
8);default:return m.charCodeAt(1)}}function u(m){if(32>m)return(16>m?"\\x0":"\\x")+m.toString(16);m=String.fromCharCode(m);if("\\"===m||"-"===m||"["===m||"]"===m)m="\\"+m;return m}function w(m){var n=m.substring(1,m.length-1).match(/\\u[0-9A-Fa-f]{4}|\\x[0-9A-Fa-f]{2}|\\[0-3][0-7]{0,2}|\\[0-7]{1,2}|\\[\s\S]|-|[^-\\]/g);m=[];for(var k=[],A="^"===n[0],q=A?1:0,y=n.length;q<y;++q){var t=n[q];switch(t){case "\\B":case "\\b":case "\\D":case "\\d":case "\\S":case "\\s":case "\\W":case "\\w":m.push(t);continue}t=
r(t);if(q+2<y&&"-"===n[q+1]){var G=r(n[q+2]);q+=2}else G=t;k.push([t,G]);65>G||122<t||(65>G||90<t||k.push([Math.max(65,t)|32,Math.min(G,90)|32]),97>G||122<t||k.push([Math.max(97,t)&-33,Math.min(G,122)&-33]))}k.sort(function(L,ea){return L[0]-ea[0]||ea[1]-L[1]});n=[];t=[NaN,NaN];for(q=0;q<k.length;++q)y=k[q],y[0]<=t[1]+1?t[1]=Math.max(t[1],y[1]):n.push(t=y);k=["["];A&&k.push("^");k.push.apply(k,m);for(q=0;q<n.length;++q)y=n[q],k.push(u(y[0])),y[1]>y[0]&&(y[1]+1>y[0]&&k.push("-"),k.push(u(y[1])));k.push("]");
return k.join("")}function z(m){for(var n=m.source.match(/(?:\[(?:[^\x5C\x5D]|\\[\s\S])*\]|\\u[A-Fa-f0-9]{4}|\\x[A-Fa-f0-9]{2}|\\[0-9]+|\\[^ux0-9]|\(\?[:!=]|[\(\)\^]|[^\x5B\x5C\(\)\^]+)/g),k=n.length,A=[],q=0,y=0;q<k;++q){var t=n[q];"("===t?++y:"\\"===t.charAt(0)&&(t=+t.substring(1))&&t<=y&&(A[t]=-1)}for(q=1;q<A.length;++q)-1===A[q]&&(A[q]=++H);for(y=q=0;q<k;++q)t=n[q],"("===t?(++y,void 0===A[y]&&(n[q]="(?:")):"\\"===t.charAt(0)&&(t=+t.substring(1))&&t<=y&&(n[q]="\\"+A[y]);for(y=q=0;q<k;++q)"^"===
n[q]&&"^"!==n[q+1]&&(n[q]="");if(m.ignoreCase&&C)for(q=0;q<k;++q)t=n[q],m=t.charAt(0),2<=t.length&&"["===m?n[q]=w(t):"\\"!==m&&(n[q]=t.replace(/[a-zA-Z]/g,function(G){G=G.charCodeAt(0);return"["+String.fromCharCode(G&-33,G|32)+"]"}));return n.join("")}for(var H=0,C=!1,x=!1,v=0,E=l.length;v<E;++v){var F=l[v];if(F.ignoreCase)x=!0;else if(/[a-z]/i.test(F.source.replace(/\\u[0-9a-f]{4}|\\x[0-9a-f]{2}|\\[^ux]/gi,""))){C=!0;x=!1;break}}var B=[];v=0;for(E=l.length;v<E;++v){F=l[v];if(F.global||F.multiline)throw Error(""+
F);B.push("(?:"+z(F)+")")}return new RegExp(B.join("|"),x?"gi":"g")}function d(l){var r=0;return function(u){for(var w=null,z=0,H=0,C=u.length;H<C;++H)switch(u.charAt(H)){case "\t":w||(w=[]);w.push(u.substring(z,H));z=l-r%l;for(r+=z;0<=z;z-=16)w.push("                ".substring(0,z));z=H+1;break;case "\n":r=0;break;default:++r}if(!w)return u;w.push(u.substring(z));return w.join("")}}function e(l,r,u,w){r&&(l={source:r,W:l},u(l),w.push.apply(w,l.Y))}function f(l,r){function u(C){for(var x=C.W,v=[x,
"pln"],E=0,F=C.source.match(z)||[],B={},m=0,n=F.length;m<n;++m){var k=F[m],A=B[k],q=void 0;if("string"===typeof A)var y=!1;else{var t=w[k.charAt(0)];if(t)q=k.match(t[1]),A=t[0];else{for(y=0;y<H;++y)if(t=r[y],q=k.match(t[1])){A=t[0];break}q||(A="pln")}!(y=5<=A.length&&"lang-"===A.substring(0,5))||q&&"string"===typeof q[1]||(y=!1,A="src");y||(B[k]=A)}t=E;E+=k.length;if(y){y=q[1];var G=k.indexOf(y),L=G+y.length;q[2]&&(L=k.length-q[2].length,G=L-y.length);A=A.substring(5);e(x+t,k.substring(0,G),u,v);
e(x+t+G,y,Ea(A,y),v);e(x+t+L,k.substring(L),u,v)}else v.push(x+t,A)}C.Y=v}var w={},z;(function(){for(var C=l.concat(r),x=[],v={},E=0,F=C.length;E<F;++E){var B=C[E],m=B[3];if(m)for(var n=m.length;0<=--n;)w[m.charAt(n)]=B;B=B[1];m=""+B;v.hasOwnProperty(m)||(x.push(B),v[m]=null)}x.push(/[\0-\uffff]/);z=c(x)})();var H=r.length;return u}function h(l){var r=[],u=[];l.tripleQuotedStrings?r.push(["str",/^(?:'''(?:[^'\\]|\\[\s\S]|'{1,2}(?=[^']))*(?:'''|$)|"""(?:[^"\\]|\\[\s\S]|"{1,2}(?=[^"]))*(?:"""|$)|'(?:[^\\']|\\[\s\S])*(?:'|$)|"(?:[^\\"]|\\[\s\S])*(?:"|$))/,
null,"'\""]):l.multiLineStrings?r.push(["str",/^(?:'(?:[^\\']|\\[\s\S])*(?:'|$)|"(?:[^\\"]|\\[\s\S])*(?:"|$)|`(?:[^\\`]|\\[\s\S])*(?:`|$))/,null,"'\"`"]):r.push(["str",/^(?:'(?:[^\\'\r\n]|\\.)*(?:'|$)|"(?:[^\\"\r\n]|\\.)*(?:"|$))/,null,"\"'"]);l.verbatimStrings&&u.push(["str",/^@"(?:[^"]|"")*(?:"|$)/,null]);var w=l.hashComments;w&&(l.cStyleComments?(1<w?r.push(["com",/^#(?:##(?:[^#]|#(?!##))*(?:###|$)|.*)/,null,"#"]):r.push(["com",/^#(?:(?:define|elif|else|endif|error|ifdef|include|ifndef|line|pragma|undef|warning)\b|[^\r\n]*)/,
null,"#"]),u.push(["str",/^<(?:(?:(?:\.\.\/)*|\/?)(?:[\w-]+(?:\/[\w-]+)+)?[\w-]+\.h|[a-z]\w*)>/,null])):r.push(["com",/^#[^\r\n]*/,null,"#"]));l.cStyleComments&&(u.push(["com",/^\/\/[^\r\n]*/,null]),u.push(["com",/^\/\*[\s\S]*?(?:\*\/|$)/,null]));l.regexLiterals&&u.push(["lang-regex",new RegExp("^"+ee+"(/(?=[^/*])(?:[^/\\x5B\\x5C]|\\x5C[\\s\\S]|\\x5B(?:[^\\x5C\\x5D]|\\x5C[\\s\\S])*(?:\\x5D|$))+/)")]);l=l.keywords.replace(/^\s+|\s+$/g,"");l.length&&u.push(["kwd",new RegExp("^(?:"+l.replace(/\s+/g,
"|")+")\\b"),null]);r.push(["pln",/^\s+/,null," \r\n\t\u00a0"]);u.push(["lit",/^@[a-z_$][a-z_$@0-9]*/i,null],["typ",/^@?[A-Z]+[a-z][A-Za-z_$@0-9]*/,null],["pln",/^[a-z_$][a-z_$@0-9]*/i,null],["lit",/^(?:0x[a-f0-9]+|(?:\d(?:_\d+)*\d*(?:\.\d*)?|\.\d\+)(?:e[+\-]?\d+)?)[a-z]*/i,null,"0123456789"],["pun",/^.[^\s\w\.$@'"`\/#]*/,null]);return f(r,u)}function p(l){function r(ma){if(ma>v){E&&E!==F&&(x.push("</span>"),E=null);!E&&F&&(E=F,x.push('<span class="',E,'">'));var Hc=a(n(u.substring(v,ma))).replace(t?
A:k,"$1&#160;");t=y.test(Hc);x.push(Hc.replace(q,Ic));v=ma}}var u=l.source,w=l.ga,z=l.Y,H=l.aa,C=l.da,x=[],v=0,E=null,F=null,B=0,m=0,n=d(window.PR_TAB_WIDTH),k=/([\r\n ]) /g,A=/(^| ) /gm,q=/\r\n?|\n/g,y=/[ \r\n]$/,t=!0,G=window._pr_isIE6();C=G?C&&"PRE"===C.tagName?6===G?"&#160;\r\n":7===G?"&#160;<br />\r":8===G?"&#160;<br />":"&#160;\r":"&#160;<br />":"<br />";if(H){var L=[];for(G=0;10>G;++G)L[G]=C+'</li><li class="L'+G+'">';var ea="number"===typeof H?H-1:0;x.push('<ol class="linenums"><li class="L',
ea%10,'"');ea&&x.push(' value="',ea+1,'"');x.push(">");var Ic=function(){var ma=L[++ea%10];return E?"</span>"+ma+'<span class="'+E+'">':ma}}else Ic=C;for(;;)if(B<w.length&&(m<z.length?w[B]<=z[m]:1))r(w[B]),E&&(x.push("</span>"),E=null),x.push(w[B+1]),B+=2;else if(m<z.length)r(z[m]),F=z[m+1],m+=2;else break;r(u.length);E&&x.push("</span>");H&&x.push("</li></ol>");l.S=x.join("")}function D(l,r){for(var u=r.length;0<=--u;){var w=r[u];Oa.hasOwnProperty(w)?"console"in window&&console.warn("cannot override language handler %s",
w):Oa[w]=l}}function Ea(l,r){l&&Oa.hasOwnProperty(l)||(l=/^\s*</.test(r)?"default-markup":"default-code");return Oa[l]}function Jc(l){var r=l.ca,u=l.$;l.S=r;try{var w=r.match(fe);r=[];var z=0,H=[];if(w)for(var C=0,x=w.length;C<x;++C){var v=w[C];if(1<v.length&&"<"===v.charAt(0)){if(!ge.test(v))if(he.test(v))r.push(v.substring(9,v.length-3)),z+=v.length-12;else if(ie.test(v))r.push("\n"),++z;else if(0<=v.indexOf("nocode")&&v.replace(/\s(\w+)\s*=\s*(?:"([^"]*)"|'([^']*)'|(\S+))/g,' $1="$2$3$4"').match(/[cC][lL][aA][sS][sS]="[^"]*\bnocode\b/)){var E=
v.match(Kc)[2],F=1;var B=C+1;a:for(;B<x;++B){var m=w[B].match(Kc);if(m&&m[2]===E)if("/"===m[1]){if(0===--F)break a}else++F}B<x?(H.push(z,w.slice(C,B+1).join("")),C=B):H.push(z,v)}else H.push(z,v)}else{F=v;var n=F.indexOf("&");if(0>n)var k=F;else{for(--n;0<=(n=F.indexOf("&#",n+1));){var A=F.indexOf(";",n);if(0<=A){var q=F.substring(n+3,A),y=10;q&&"x"===q.charAt(0)&&(q=q.substring(1),y=16);var t=parseInt(q,y);isNaN(t)||(F=F.substring(0,n)+String.fromCharCode(t)+F.substring(A+1))}}k=F.replace(je,"<").replace(ke,
">").replace(le,"'").replace(me,'"').replace(ne," ").replace(oe,"&")}r.push(k);z+=k.length}}var G=r.join("");l.source=G;l.W=0;l.ga=H;Ea(u,G)(l);p(l)}catch(L){"console"in window&&console.log(L&&L.stack?L.stack:L)}}var ee=function(){for(var l="! != !== # % %= & && &&= &= ( * *= += , -= -> / /= : :: ; < << <<= <= = == === > >= >> >>= >>> >>>= ? @ [ ^ ^= ^^ ^^= { | |= || ||= ~ break case continue delete do else finally instanceof return throw try typeof".split(" "),r="(?:^^|[+-]",u=0;u<l.length;++u)r+=
"|"+l[u].replace(/([^=<>:&a-z])/g,"\\$1");return r+")\\s*"}(),Ec=/&/g,Fc=/</g,Gc=/>/g,de=/"/g,je=/&lt;/g,ke=/&gt;/g,le=/&apos;/g,me=/&quot;/g,oe=/&amp;/g,ne=/&nbsp;/g,pe=/[\r\n]/g,rb=null,fe=/[^<]+|\x3c!--[\s\S]*?--\x3e|<!\[CDATA\[[\s\S]*?\]\]>|<\/?[a-zA-Z](?:[^>"']|'[^']*'|"[^"]*")*>|</g,ge=/^\x3c!--/,he=/^<!\[CDATA\[/,ie=/^<br\b/i,Kc=/^<(\/?)([a-zA-Z][a-zA-Z0-9]*)/,qe=h({keywords:"break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof alignof align_union asm axiom bool concept concept_map const_cast constexpr decltype dynamic_cast explicit export friend inline late_check mutable namespace nullptr reinterpret_cast static_assert static_cast template typeid typename using virtual wchar_t where break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof abstract boolean byte extends final finally implements import instanceof null native package strictfp super synchronized throws transient as base by checked decimal delegate descending dynamic event fixed foreach from group implicit in interface internal into is lock object out override orderby params partial readonly ref sbyte sealed stackalloc string select uint ulong unchecked unsafe ushort var break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof debugger eval export function get null set undefined var with Infinity NaN caller delete die do dump elsif eval exit foreach for goto if import last local my next no our print package redo require sub undef unless until use wantarray while BEGIN END break continue do else for if return while and as assert class def del elif except exec finally from global import in is lambda nonlocal not or pass print raise try with yield False True None break continue do else for if return while alias and begin case class def defined elsif end ensure false in module next nil not or redo rescue retry self super then true undef unless until when yield BEGIN END break continue do else for if return while case done elif esac eval fi function in local set then until ",
hashComments:!0,cStyleComments:!0,multiLineStrings:!0,regexLiterals:!0}),Oa={};D(qe,["default-code"]);D(f([],[["pln",/^[^<?]+/],["dec",/^<!\w[^>]*(?:>|$)/],["com",/^\x3c!--[\s\S]*?(?:-\->|$)/],["lang-",/^<\?([\s\S]+?)(?:\?>|$)/],["lang-",/^<%([\s\S]+?)(?:%>|$)/],["pun",/^(?:<[%?]|[%?]>)/],["lang-",/^<xmp\b[^>]*>([\s\S]+?)<\/xmp\b[^>]*>/i],["lang-js",/^<script\b[^>]*>([\s\S]*?)(<\/script\b[^>]*>)/i],["lang-css",/^<style\b[^>]*>([\s\S]*?)(<\/style\b[^>]*>)/i],["lang-in.tag",/^(<\/?[a-z][^<>]*>)/i]]),
"default-markup htm html mxml xhtml xml xsl".split(" "));D(f([["pln",/^[\s]+/,null," \t\r\n"],["atv",/^(?:"[^"]*"?|'[^']*'?)/,null,"\"'"]],[["tag",/^^<\/?[a-z](?:[\w.:-]*\w)?|\/?>$/i],["atn",/^(?!style[\s=]|on)[a-z](?:[\w:-]*\w)?/i],["lang-uq.val",/^=\s*([^>'"\s]*(?:[^>'"\s\/]|\/(?=\s)))/],["pun",/^[=<>\/]+/],["lang-js",/^on\w+\s*=\s*"([^"]+)"/i],["lang-js",/^on\w+\s*=\s*'([^']+)'/i],["lang-js",/^on\w+\s*=\s*([^"'>\s]+)/i],["lang-css",/^style\s*=\s*"([^"]+)"/i],["lang-css",/^style\s*=\s*'([^']+)'/i],
["lang-css",/^style\s*=\s*([^"'>\s]+)/i]]),["in.tag"]);D(f([],[["atv",/^[\s\S]+/]]),["uq.val"]);D(h({keywords:"break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof alignof align_union asm axiom bool concept concept_map const_cast constexpr decltype dynamic_cast explicit export friend inline late_check mutable namespace nullptr reinterpret_cast static_assert static_cast template typeid typename using virtual wchar_t where ",
hashComments:!0,cStyleComments:!0}),"c cc cpp cxx cyc m".split(" "));D(h({keywords:"null true false"}),["json"]);D(h({keywords:"break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof abstract boolean byte extends final finally implements import instanceof null native package strictfp super synchronized throws transient as base by checked decimal delegate descending dynamic event fixed foreach from group implicit in interface internal into is lock object out override orderby params partial readonly ref sbyte sealed stackalloc string select uint ulong unchecked unsafe ushort var ",
hashComments:!0,cStyleComments:!0,verbatimStrings:!0}),["cs"]);D(h({keywords:"break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof abstract boolean byte extends final finally implements import instanceof null native package strictfp super synchronized throws transient ",
cStyleComments:!0}),["java"]);D(h({keywords:"break continue do else for if return while case done elif esac eval fi function in local set then until ",hashComments:!0,multiLineStrings:!0}),["bsh","csh","sh"]);D(h({keywords:"break continue do else for if return while and as assert class def del elif except exec finally from global import in is lambda nonlocal not or pass print raise try with yield False True None ",hashComments:!0,multiLineStrings:!0,tripleQuotedStrings:!0}),["cv","py"]);D(h({keywords:"caller delete die do dump elsif eval exit foreach for goto if import last local my next no our print package redo require sub undef unless until use wantarray while BEGIN END ",
hashComments:!0,multiLineStrings:!0,regexLiterals:!0}),["perl","pl","pm"]);D(h({keywords:"break continue do else for if return while alias and begin case class def defined elsif end ensure false in module next nil not or redo rescue retry self super then true undef unless until when yield BEGIN END ",hashComments:!0,multiLineStrings:!0,regexLiterals:!0}),["rb"]);D(h({keywords:"break continue do else for if return while auto case char const default double enum extern float goto int long register short signed sizeof static struct switch typedef union unsigned void volatile catch class delete false import new operator private protected public this throw true try typeof debugger eval export function get null set undefined var with Infinity NaN ",
cStyleComments:!0,regexLiterals:!0}),["js"]);D(h({keywords:"all and by catch class else extends false finally for if in is isnt loop new no not null of off on or return super then true try unless until when while yes ",hashComments:3,cStyleComments:!0,multilineStrings:!0,tripleQuotedStrings:!0,regexLiterals:!0}),["coffee"]);D(f([],[["str",/^[\s\S]+/]]),["regex"]);window.PR_normalizedHtml=b;window.prettyPrintOne=function(l,r,u){l={ca:l,$:r,aa:u};Jc(l);return l.S};window.prettyPrint=function(l){function r(){for(var F=
window.PR_SHOULD_USE_CONTINUATION?x.now()+250:Infinity;v<w.length&&x.now()<F;v++){var B=w[v];if(B.className&&0<=B.className.indexOf("prettyprint")){var m=B.className.match(/\blang-(\w+)\b/);m&&(m=m[1]);for(var n=!1,k=B.parentNode;k;k=k.parentNode)if(("pre"===k.tagName||"code"===k.tagName||"xmp"===k.tagName)&&k.className&&0<=k.className.indexOf("prettyprint")){n=!0;break}if(!n){k=B;null===rb&&(n=document.createElement("PRE"),n.appendChild(document.createTextNode('<!DOCTYPE foo PUBLIC "foo bar">\n<foo />')),
rb=!/</.test(n.innerHTML));if(rb)if(n=k.innerHTML,"XMP"===k.tagName)n=a(n);else{if("PRE"!==k.tagName&&pe.test(n)){var A="";k.currentStyle?A=k.currentStyle.whiteSpace:window.getComputedStyle&&(A=window.getComputedStyle(k,null).whiteSpace);k=!A||"pre"===A}else k=!0;k||(n=n.replace(/(<br\s*\/?>)[\r\n]+/g,"$1").replace(/(?:[\r\n]+[ \t]*)+/g," "))}else{n=[];for(k=k.firstChild;k;k=k.nextSibling)b(k,n);n=n.join("")}n=n.replace(/(?:\r\n?|\n)$/,"");k=B.className.match(/\blinenums\b(?::(\d+))?/);E={ca:n,$:m,
da:B,aa:k?k[1]&&k[1].length?+k[1]:!0:!1};Jc(E);if(B=E.S)if(m=E.da,"XMP"===m.tagName){n=document.createElement("PRE");for(k=0;k<m.attributes.length;++k)A=m.attributes[k],A.specified&&("class"===A.name.toLowerCase()?n.className=A.value:n.setAttribute(A.name,A.value));n.innerHTML=B;m.parentNode.replaceChild(n,m)}else m.innerHTML=B}}}v<w.length?setTimeout(r,250):l&&l()}for(var u=[document.getElementsByTagName("pre"),document.getElementsByTagName("code"),document.getElementsByTagName("xmp")],w=[],z=0;z<
u.length;++z)for(var H=0,C=u[z].length;H<C;++H)w.push(u[z][H]);u=null;var x=Date;x.now||(x={now:function(){return(new Date).getTime()}});var v=0,E;r()};window.PR={combinePrefixPatterns:c,createSimpleLexer:f,registerLangHandler:D,sourceDecorator:h,PR_ATTRIB_NAME:"atn",PR_ATTRIB_VALUE:"atv",PR_COMMENT:"com",PR_DECLARATION:"dec",PR_KEYWORD:"kwd",PR_LITERAL:"lit",PR_NOCODE:"nocode",PR_PLAIN:"pln",PR_PUNCTUATION:"pun",PR_SOURCE:"src",PR_STRING:"str",PR_TAG:"tag",PR_TYPE:"typ"}})();/*
 Copyright (C) 2009 Onno Hommes.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_COMMENT,/^#[^\r\n]*/,null,"#"],[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_STRING,/^"(?:[^"\\]|\\[\s\S])*(?:"|$)/,null,'"']],[[PR.PR_KEYWORD,/^(?:ADS|AD|AUG|BZF|BZMF|CAE|CAF|CA|CCS|COM|CS|DAS|DCA|DCOM|DCS|DDOUBL|DIM|DOUBLE|DTCB|DTCF|DV|DXCH|EDRUPT|EXTEND|INCR|INDEX|NDX|INHINT|LXCH|MASK|MSK|MP|MSU|NOOP|OVSK|QXCH|RAND|READ|RELINT|RESUME|RETURN|ROR|RXOR|SQUARE|SU|TCR|TCAA|OVSK|TCF|TC|TS|WAND|WOR|WRITE|XCH|XLQ|XXALQ|ZL|ZQ|ADD|ADZ|SUB|SUZ|MPY|MPR|MPZ|DVP|COM|ABS|CLA|CLZ|LDQ|STO|STQ|ALS|LLS|LRS|TRA|TSQ|TMI|TOV|AXT|TIX|DLY|INP|OUT)\s/,
null],[PR.PR_TYPE,/^(?:-?GENADR|=MINUS|2BCADR|VN|BOF|MM|-?2CADR|-?[1-6]DNADR|ADRES|BBCON|[SE]?BANK=?|BLOCK|BNKSUM|E?CADR|COUNT\*?|2?DEC\*?|-?DNCHAN|-?DNPTR|EQUALS|ERASE|MEMORY|2?OCT|REMADR|SETLOC|SUBRO|ORG|BSS|BES|SYN|EQU|DEFINE|END)\s/,null],[PR.PR_LITERAL,/^'(?:-*(?:\w|\\[\x21-\x7e])(?:[\w-]*|\\[\x21-\x7e])[=!?]?)?/],[PR.PR_PLAIN,/^-*(?:[!-z_]|\\[\x21-\x7e])(?:[\w-]*|\\[\x21-\x7e])[=!?]?/i],[PR.PR_PUNCTUATION,/^[^\w\t\n\r \xA0()"\\';]+/]]),["apollo","agc","aea"]);/*
 Copyright (C) 2011 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
PR.registerLangHandler(PR.createSimpleLexer([["opn",/^[\(\{\[]+/,null,"([{"],["clo",/^[\)\}\]]+/,null,")]}"],[PR.PR_COMMENT,/^;[^\r\n]*/,null,";"],[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_STRING,/^"(?:[^"\\]|\\[\s\S])*(?:"|$)/,null,'"']],[[PR.PR_KEYWORD,/^(?:def|if|do|let|quote|var|fn|loop|recur|throw|try|monitor-enter|monitor-exit|defmacro|defn|defn-|macroexpand|macroexpand-1|for|doseq|dosync|dotimes|and|or|when|not|assert|doto|proxy|defstruct|first|rest|cons|defprotocol|deftype|defrecord|reify|defmulti|defmethod|meta|with-meta|ns|in-ns|create-ns|import|intern|refer|alias|namespace|resolve|ref|deref|refset|new|set!|memfn|to-array|into-array|aset|gen-class|reduce|map|filter|find|nil?|empty?|hash-map|hash-set|vec|vector|seq|flatten|reverse|assoc|dissoc|list|list?|disj|get|union|difference|intersection|extend|extend-type|extend-protocol|prn)\b/,
null],[PR.PR_TYPE,/^:[0-9a-zA-Z\-]+/]]),["clj"]);/*
 Copyright (C) 2009 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[ \t\r\n\f]+/,null," \t\r\n\f"]],[[PR.PR_STRING,/^"(?:[^\n\r\f\\"]|\\(?:\r\n?|\n|\f)|\\[\s\S])*"/,null],[PR.PR_STRING,/^'(?:[^\n\r\f\\']|\\(?:\r\n?|\n|\f)|\\[\s\S])*'/,null],["lang-css-str",/^url\(([^\)"']*)\)/i],[PR.PR_KEYWORD,/^(?:url|rgb|!important|@import|@page|@media|@charset|inherit)(?=[^\-\w]|$)/i,null],["lang-css-kw",/^(-?(?:[_a-z]|(?:\\[0-9a-f]+ ?))(?:[_a-z0-9\-]|\\(?:\\[0-9a-f]+ ?))*)\s*:/i],[PR.PR_COMMENT,/^\/\*[^*]*\*+(?:[^\/*][^*]*\*+)*\//],
[PR.PR_COMMENT,/^(?:\x3c!--|--\x3e)/],[PR.PR_LITERAL,/^(?:\d+|\d*\.\d+)(?:%|[a-z]+)?/i],[PR.PR_LITERAL,/^#(?:[0-9a-f]{3}){1,2}/i],[PR.PR_PLAIN,/^-?(?:[_a-z]|(?:\\[\da-f]+ ?))(?:[_a-z\d\-]|\\(?:\\[\da-f]+ ?))*/i],[PR.PR_PUNCTUATION,/^[^\s\w'"]+/]]),["css"]);PR.registerLangHandler(PR.createSimpleLexer([],[[PR.PR_KEYWORD,/^-?(?:[_a-z]|(?:\\[\da-f]+ ?))(?:[_a-z\d\-]|\\(?:\\[\da-f]+ ?))*/i]]),["css-kw"]);PR.registerLangHandler(PR.createSimpleLexer([],[[PR.PR_STRING,/^[^\)"']+/]]),["css-str"]);/*
 Copyright (C) 2010 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_PLAIN,/^(?:"(?:[^"\\]|\\[\s\S])*(?:"|$)|'(?:[^'\\]|\\[\s\S])+(?:'|$))/,null,"\"'"]],[[PR.PR_COMMENT,/^(?:\/\/[^\r\n]*|\/\*[\s\S]*?\*\/)/],[PR.PR_PLAIN,/^(?:[^\/"']|\/(?![\/\*]))+/i]]),["go"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\x0B\x0C\r ]+/,null,"\t\n\x0B\f\r "],[PR.PR_STRING,/^"(?:[^"\\\n\x0C\r]|\\[\s\S])*(?:"|$)/,null,'"'],[PR.PR_STRING,/^'(?:[^'\\\n\x0C\r]|\\[^&])'?/,null,"'"],[PR.PR_LITERAL,/^(?:0o[0-7]+|0x[\da-f]+|\d+(?:\.\d+)?(?:e[+\-]?\d+)?)/i,null,"0123456789"]],[[PR.PR_COMMENT,/^(?:(?:--+(?:[^\r\n\x0C]*)?)|(?:\{-(?:[^-]|-+[^-\}])*-\}))/],[PR.PR_KEYWORD,/^(?:case|class|data|default|deriving|do|else|if|import|in|infix|infixl|infixr|instance|let|module|newtype|of|then|type|where|_)(?=[^a-zA-Z0-9']|$)/,
null],[PR.PR_PLAIN,/^(?:[A-Z][\w']*\.)*[a-zA-Z][\w']*/],[PR.PR_PUNCTUATION,/^[^\t\n\x0B\x0C\r a-zA-Z0-9'"]+/]]),["hs"]);/*

 Copyright (C) 2017 Micha? B?czkowski

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_PUNCTUATION,/^[.!%&()*+,\-;<=>?\[\\\]^{|}:]+/,null,".!%&()*+,-;<=>?[\\]^{|}:"]],[[PR.PR_KEYWORD,/^\b(package|public|protected|private|open|abstract|constructor|final|override|import|for|while|as|typealias|get|set|((data|enum|annotation|sealed) )?class|this|super|val|var|fun|is|in|throw|return|break|continue|(companion )?object|if|try|else|do|when|init|interface|typeof)\b/],[PR.PR_LITERAL,/^(?:true|false|null)\b/],
[PR.PR_LITERAL,/^(0[xX][0-9a-fA-F_]+L?|0[bB][0-1]+L?|[0-9_.]+([eE]-?[0-9]+)?[fFL]?)/],[PR.PR_TYPE,/^(\b[A-Z]+[a-z][a-zA-Z0-9_$@]*|`.*`)/,null],[PR.PR_COMMENT,/^\/\/.*/],[PR.PR_COMMENT,/^\/\*[\s\S]*?(?:\*\/|$)/],[PR.PR_STRING,/'.'/],[PR.PR_STRING,/^"([^"\\]|\\[\s\S])*"/],[PR.PR_STRING,/^"{3}[\s\S]*?[^\\]"{3}/],[PR.PR_LITERAL,/^@([a-zA-Z0-9_$@]*|`.*`)/],[PR.PR_LITERAL,/^[a-zA-Z0-9_]+@/]]),["kotlin"]);/*
 Copyright (C) 2008 Google Inc.

 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0

 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
PR.registerLangHandler(PR.createSimpleLexer([["opn",/^\(+/,null,"("],["clo",/^\)+/,null,")"],[PR.PR_COMMENT,/^;[^\r\n]*/,null,";"],[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_STRING,/^"(?:[^"\\]|\\[\s\S])*(?:"|$)/,null,'"']],[[PR.PR_KEYWORD,/^(?:block|c[ad]+r|catch|con[ds]|def(?:ine|un)|do|eq|eql|equal|equalp|eval-when|flet|format|go|if|labels|lambda|let|load-time-value|locally|macrolet|multiple-value-call|nil|progn|progv|quote|require|return-from|setq|symbol-macrolet|t|tagbody|the|throw|unwind)\b/,
null],[PR.PR_LITERAL,/^[+\-]?(?:[0#]x[0-9a-f]+|\d+\/\d+|(?:\.\d+|\d+(?:\.\d*)?)(?:[ed][+\-]?\d+)?)/i],[PR.PR_LITERAL,/^'(?:-*(?:\w|\\[\x21-\x7e])(?:[\w-]*|\\[\x21-\x7e])[=!?]?)?/],[PR.PR_PLAIN,/^-*(?:[a-z_]|\\[\x21-\x7e])(?:[\w-]*|\\[\x21-\x7e])[=!?]?/i],[PR.PR_PUNCTUATION,/^[^\w\t\n\r \xA0()"\\';]+/]]),["cl","el","lisp","scm"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_STRING,/^(?:"(?:[^"\\]|\\[\s\S])*(?:"|$)|'(?:[^'\\]|\\[\s\S])*(?:'|$))/,null,"\"'"]],[[PR.PR_COMMENT,/^--(?:\[(=*)\[[\s\S]*?(?:\]\1\]|$)|[^\r\n]*)/],[PR.PR_STRING,/^\[(=*)\[[\s\S]*?(?:\]\1\]|$)/],[PR.PR_KEYWORD,/^(?:and|break|do|else|elseif|end|false|for|function|if|in|local|nil|not|or|repeat|return|then|true|until|while)\b/,null],[PR.PR_LITERAL,/^[+-]?(?:0x[\da-f]+|(?:(?:\.\d+|\d+(?:\.\d*)?)(?:e[+\-]?\d+)?))/i],
[PR.PR_PLAIN,/^[a-z_]\w*/i],[PR.PR_PUNCTUATION,/^[^\w\t\n\r \xA0][^\w\t\n\r \xA0"'\-\+=]*/]]),["lua"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_COMMENT,/^#(?:if[\t\n\r \xA0]+(?:[a-z_$][\w']*|``[^\r\n\t`]*(?:``|$))|else|endif|light)/i,null,"#"],[PR.PR_STRING,/^(?:"(?:[^"\\]|\\[\s\S])*(?:"|$)|'(?:[^'\\]|\\[\s\S])(?:'|$))/,null,"\"'"]],[[PR.PR_COMMENT,/^(?:\/\/[^\r\n]*|\(\*[\s\S]*?\*\))/],[PR.PR_KEYWORD,/^(?:abstract|and|as|assert|begin|class|default|delegate|do|done|downcast|downto|elif|else|end|exception|extern|false|finally|for|fun|function|if|in|inherit|inline|interface|internal|lazy|let|match|member|module|mutable|namespace|new|null|of|open|or|override|private|public|rec|return|static|struct|then|to|true|try|type|upcast|use|val|void|when|while|with|yield|asr|land|lor|lsl|lsr|lxor|mod|sig|atomic|break|checked|component|const|constraint|constructor|continue|eager|event|external|fixed|functor|global|include|method|mixin|object|parallel|process|protected|pure|sealed|trait|virtual|volatile)\b/],
[PR.PR_LITERAL,/^[+\-]?(?:0x[\da-f]+|(?:(?:\.\d+|\d+(?:\.\d*)?)(?:e[+\-]?\d+)?))/i],[PR.PR_PLAIN,/^(?:[a-z_][\w']*[!?#]?|``[^\r\n\t`]*(?:``|$))/i],[PR.PR_PUNCTUATION,/^[^\t\n\r \xA0"'\w]+/]]),["fs","ml"]);PR.registerLangHandler(PR.sourceDecorator({keywords:"bool bytes default double enum extend extensions false fixed32 fixed64 float group import int32 int64 max message option optional package repeated required returns rpc service sfixed32 sfixed64 sint32 sint64 string syntax to true uint32 uint64",cStyleComments:!0}),["proto"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_STRING,/^(?:"(?:(?:""(?:""?(?!")|[^\\"]|\\.)*"{0,3})|(?:[^"\r\n\\]|\\.)*"?))/,null,'"'],[PR.PR_LITERAL,/^`(?:[^\r\n\\`]|\\.)*`?/,null,"`"],[PR.PR_PUNCTUATION,/^[!#%&()*+,\-:;<=>?@\[\\\]^{|}~]+/,null,"!#%&()*+,-:;<=>?@[\\]^{|}~"]],[[PR.PR_STRING,/^'(?:[^\r\n\\']|\\(?:'|[^\r\n']+))'/],[PR.PR_LITERAL,/^'[a-zA-Z_$][\w$]*(?!['$\w])/],[PR.PR_KEYWORD,/^(?:abstract|case|catch|class|def|do|else|extends|final|finally|for|forSome|if|implicit|import|lazy|match|new|object|override|package|private|protected|requires|return|sealed|super|throw|trait|try|type|val|var|while|with|yield)\b/],
[PR.PR_LITERAL,/^(?:true|false|null|this)\b/],[PR.PR_LITERAL,/^(?:(?:0(?:[0-7]+|X[0-9A-F]+))L?|(?:(?:0|[1-9][0-9]*)(?:(?:\.[0-9]+)?(?:E[+\-]?[0-9]+)?F?|L?))|\\.[0-9]+(?:E[+\-]?[0-9]+)?F?)/i],[PR.PR_TYPE,/^[$_]*[A-Z][_$A-Z0-9]*[a-z][\w$]*/],[PR.PR_PLAIN,/^[$a-zA-Z_][\w$]*/],[PR.PR_COMMENT,/^\/(?:\/.*|\*(?:\/|\**[^*/])*(?:\*+\/?)?)/],[PR.PR_PUNCTUATION,/^(?:\.+|\/)/]]),["scala"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"],[PR.PR_STRING,/^(?:"(?:[^"\\]|\\.)*"|'(?:[^'\\]|\\.)*')/,null,"\"'"]],[[PR.PR_COMMENT,/^(?:--[^\r\n]*|\/\*[\s\S]*?(?:\*\/|$))/],[PR.PR_KEYWORD,/^(?:ADD|ALL|ALTER|AND|ANY|AS|ASC|AUTHORIZATION|BACKUP|BEGIN|BETWEEN|BREAK|BROWSE|BULK|BY|CASCADE|CASE|CHECK|CHECKPOINT|CLOSE|CLUSTERED|COALESCE|COLLATE|COLUMN|COMMIT|COMPUTE|CONSTRAINT|CONTAINS|CONTAINSTABLE|CONTINUE|CONVERT|CREATE|CROSS|CURRENT|CURRENT_DATE|CURRENT_TIME|CURRENT_TIMESTAMP|CURRENT_USER|CURSOR|DATABASE|DBCC|DEALLOCATE|DECLARE|DEFAULT|DELETE|DENY|DESC|DISK|DISTINCT|DISTRIBUTED|DOUBLE|DROP|DUMMY|DUMP|ELSE|END|ERRLVL|ESCAPE|EXCEPT|EXEC|EXECUTE|EXISTS|EXIT|FETCH|FILE|FILLFACTOR|FOR|FOREIGN|FREETEXT|FREETEXTTABLE|FROM|FULL|FUNCTION|GOTO|GRANT|GROUP|HAVING|HOLDLOCK|IDENTITY|IDENTITYCOL|IDENTITY_INSERT|IF|IN|INDEX|INNER|INSERT|INTERSECT|INTO|IS|JOIN|KEY|KILL|LEFT|LIKE|LINENO|LOAD|NATIONAL|NOCHECK|NONCLUSTERED|NOT|NULL|NULLIF|OF|OFF|OFFSETS|ON|OPEN|OPENDATASOURCE|OPENQUERY|OPENROWSET|OPENXML|OPTION|OR|ORDER|OUTER|OVER|PERCENT|PLAN|PRECISION|PRIMARY|PRINT|PROC|PROCEDURE|PUBLIC|RAISERROR|READ|READTEXT|RECONFIGURE|REFERENCES|REPLICATION|RESTORE|RESTRICT|RETURN|REVOKE|RIGHT|ROLLBACK|ROWCOUNT|ROWGUIDCOL|RULE|SAVE|SCHEMA|SELECT|SESSION_USER|SET|SETUSER|SHUTDOWN|SOME|STATISTICS|SYSTEM_USER|TABLE|TEXTSIZE|THEN|TO|TOP|TRAN|TRANSACTION|TRIGGER|TRUNCATE|TSEQUAL|UNION|UNIQUE|UPDATE|UPDATETEXT|USE|USER|VALUES|VARYING|VIEW|WAITFOR|WHEN|WHERE|WHILE|WITH|WRITETEXT)(?=[^\w-]|$)/i,
null],[PR.PR_LITERAL,/^[+-]?(?:0x[\da-f]+|(?:(?:\.\d+|\d+(?:\.\d*)?)(?:e[+\-]?\d+)?))/i],[PR.PR_PLAIN,/^[a-z_][\w-]*/i],[PR.PR_PUNCTUATION,/^[^\w\t\n\r \xA0"'][^\w\t\n\r \xA0+\-"']*/]]),["sql"]);/*
 Copyright (C) 2015 Google Inc.
 Licensed under the Apache License, Version 2.0 (the "License");
 you may not use this file except in compliance with the License.
 You may obtain a copy of the License at

      http://www.apache.org/licenses/LICENSE-2.0
 Unless required by applicable law or agreed to in writing, software
 distributed under the License is distributed on an "AS IS" BASIS,
 WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 See the License for the specific language governing permissions and
 limitations under the License.
*/
PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[ \n\r\t\v\f\0]+/,null," \n\r\t\v\f\x00"],[PR.PR_STRING,/^"(?:[^"\\]|(?:\\.)|(?:\\\((?:[^"\\)]|\\.)*\)))*"/,null,'"']],[[PR.PR_LITERAL,/^(?:(?:0x[\da-fA-F][\da-fA-F_]*\.[\da-fA-F][\da-fA-F_]*[pP]?)|(?:\d[\d_]*\.\d[\d_]*[eE]?))[+-]?\d[\d_]*/,null],[PR.PR_LITERAL,/^-?(?:(?:0(?:(?:b[01][01_]*)|(?:o[0-7][0-7_]*)|(?:x[\da-fA-F][\da-fA-F_]*)))|(?:\d[\d_]*))/,null],[PR.PR_LITERAL,/^(?:true|false|nil)\b/,null],[PR.PR_KEYWORD,/^\b(?:__COLUMN__|__FILE__|__FUNCTION__|__LINE__|associativity|as|break|case|class|continue|convenience|default|deinit|didSet|do|dynamic|dynamicType|else|enum|fallthrough|final|for|func|get|import|infix|init|inout|internal|if|in|is|lazy|left|let|mutating|none|nonmutating|operator|optional|override|postfix|precedence|prefix|private|protocol|Protocol|public|required|return|right|safe|self|set|static|struct|subscript|super|switch|Type|typealias|unowned|unsafe|var|weak|while|willSet)\b/,
null],[PR.PR_COMMENT,/^\/\/.*?[\n\r]/,null],[PR.PR_COMMENT,/^\/\*[\s\S]*?(?:\*\/|$)/,null],[PR.PR_PUNCTUATION,/^<<=|<=|<<|>>=|>=|>>|===|==|\.\.\.|&&=|\.\.<|!==|!=|&=|~=|~|\(|\)|\[|\]|{|}|@|#|;|\.|,|:|\|\|=|\?\?|\|\||&&|&\*|&\+|&-|&=|\+=|-=|\/=|\*=|\^=|%=|\|=|->|`|==|\+\+|--|\/|\+|!|\*|%|<|>|&|\||\^|\?|=|-|_/,null],[PR.PR_TYPE,/^\b(?:[@_]?[A-Z]+[a-z][A-Za-z_$@0-9]*|\w+_t\b)/,null]]),["swift"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\r \xA0\u2028\u2029]+/,null,"\t\n\r \u00a0\u2028\u2029"],[PR.PR_STRING,/^(?:["\u201C\u201D](?:[^"\u201C\u201D]|["\u201C\u201D]{2})(?:["\u201C\u201D]c|$)|["\u201C\u201D](?:[^"\u201C\u201D]|["\u201C\u201D]{2})*(?:["\u201C\u201D]|$))/i,null,'"\u201c\u201d'],[PR.PR_COMMENT,/^['\u2018\u2019][^\r\n\u2028\u2029]*/,null,"'\u2018\u2019"]],[[PR.PR_KEYWORD,/^(?:AddHandler|AddressOf|Alias|And|AndAlso|Ansi|As|Assembly|Auto|Boolean|ByRef|Byte|ByVal|Call|Case|Catch|CBool|CByte|CChar|CDate|CDbl|CDec|Char|CInt|Class|CLng|CObj|Const|CShort|CSng|CStr|CType|Date|Decimal|Declare|Default|Delegate|Dim|DirectCast|Do|Double|Each|Else|ElseIf|End|EndIf|Enum|Erase|Error|Event|Exit|Finally|For|Friend|Function|Get|GetType|GoSub|GoTo|Handles|If|Implements|Imports|In|Inherits|Integer|Interface|Is|Let|Lib|Like|Long|Loop|Me|Mod|Module|MustInherit|MustOverride|MyBase|MyClass|Namespace|New|Next|Not|NotInheritable|NotOverridable|Object|On|Option|Optional|Or|OrElse|Overloads|Overridable|Overrides|ParamArray|Preserve|Private|Property|Protected|Public|RaiseEvent|ReadOnly|ReDim|RemoveHandler|Resume|Return|Select|Set|Shadows|Shared|Short|Single|Static|Step|Stop|String|Structure|Sub|SyncLock|Then|Throw|To|Try|TypeOf|Unicode|Until|Variant|Wend|When|While|With|WithEvents|WriteOnly|Xor|EndIf|GoSub|Let|Variant|Wend)\b/i,
null],[PR.PR_COMMENT,/^REM[^\r\n\u2028\u2029]*/i],[PR.PR_LITERAL,/^(?:True\b|False\b|Nothing\b|\d+(?:E[+\-]?\d+[FRD]?|[FRDSIL])?|(?:&H[0-9A-F]+|&O[0-7]+)[SIL]?|\d*\.\d+(?:E[+\-]?\d+)?[FRD]?|#\s+(?:\d+[\-\/]\d+[\-\/]\d+(?:\s+\d+:\d+(?::\d+)?(\s*(?:AM|PM))?)?|\d+:\d+(?::\d+)?(\s*(?:AM|PM))?)\s+#)/i],[PR.PR_PLAIN,/^(?:(?:[a-z]|_\w)\w*|\[(?:[a-z]|_\w)\w*\])/i],[PR.PR_PUNCTUATION,/^[^\w\t\n\r "'\[\]\xA0\u2018\u2019\u201C\u201D\u2028\u2029]+/],[PR.PR_PUNCTUATION,/^(?:\[|\])/]]),["vb","vbs"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t\n\r \xA0]+/,null,"\t\n\r \u00a0"]],[[PR.PR_STRING,/^(?:[BOX]?"(?:[^"]|"")*"|'.')/i],[PR.PR_COMMENT,/^--[^\r\n]*/],[PR.PR_KEYWORD,/^(?:abs|access|after|alias|all|and|architecture|array|assert|attribute|begin|block|body|buffer|bus|case|component|configuration|constant|disconnect|downto|else|elsif|end|entity|exit|file|for|function|generate|generic|group|guarded|if|impure|in|inertial|inout|is|label|library|linkage|literal|loop|map|mod|nand|new|next|nor|not|null|of|on|open|or|others|out|package|port|postponed|procedure|process|pure|range|record|register|reject|rem|report|return|rol|ror|select|severity|shared|signal|sla|sll|sra|srl|subtype|then|to|transport|type|unaffected|units|until|use|variable|wait|when|while|with|xnor|xor)(?=[^\w-]|$)/i,
null],[PR.PR_TYPE,/^(?:bit|bit_vector|character|boolean|integer|real|time|string|severity_level|positive|natural|signed|unsigned|line|text|std_u?logic(?:_vector)?)(?=[^\w-]|$)/i,null],[PR.PR_TYPE,/^'(?:ACTIVE|ASCENDING|BASE|DELAYED|DRIVING|DRIVING_VALUE|EVENT|HIGH|IMAGE|INSTANCE_NAME|LAST_ACTIVE|LAST_EVENT|LAST_VALUE|LEFT|LEFTOF|LENGTH|LOW|PATH_NAME|POS|PRED|QUIET|RANGE|REVERSE_RANGE|RIGHT|RIGHTOF|SIMPLE_NAME|STABLE|SUCC|TRANSACTION|VAL|VALUE)(?=[^\w-]|$)/i,null],[PR.PR_LITERAL,/^\d+(?:_\d+)*(?:#[\w\\.]+#(?:[+\-]?\d+(?:_\d+)*)?|(?:\.\d+(?:_\d+)*)?(?:E[+\-]?\d+(?:_\d+)*)?)/i],
[PR.PR_PLAIN,/^(?:[a-z]\w*|\\[^\\]*\\)/i],[PR.PR_PUNCTUATION,/^[^\w\t\n\r \xA0"'][^\w\t\n\r \xA0\-"']*/]]),["vhdl","vhd"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PLAIN,/^[\t \xA0a-gi-z0-9]+/,null,"\t \u00a0abcdefgijklmnopqrstuvwxyz0123456789"],[PR.PR_PUNCTUATION,/^[=*~\^\[\]]+/,null,"=*~^[]"]],[["lang-wiki.meta",/(?:^^|\r\n?|\n)(#[a-z]+)\b/],[PR.PR_LITERAL,/^(?:[A-Z][a-z][a-z0-9]+[A-Z][a-z][a-zA-Z0-9]+)\b/],["lang-",/^\{\{\{([\s\S]+?)\}\}\}/],["lang-",/^`([^\r\n`]+)`/],[PR.PR_STRING,/^https?:\/\/[^\/?#\s]*(?:\/[^?#\s]*)?(?:\?[^#\s]*)?(?:#\S*)?/i],[PR.PR_PLAIN,/^(?:\r\n|[\s\S])[^#=*~^A-Zh\{`\[\r\n]*/]]),["wiki"]);
PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_KEYWORD,/^#[a-z]+/i,null,"#"]],[]),["wiki.meta"]);PR.registerLangHandler(PR.createSimpleLexer([[PR.PR_PUNCTUATION,/^[:|>?]+/,null,":|>?"],[PR.PR_DECLARATION,/^%(?:YAML|TAG)[^#\r\n]+/,null,"%"],[PR.PR_TYPE,/^[&]\S+/,null,"&"],[PR.PR_TYPE,/^!\S*/,null,"!"],[PR.PR_STRING,/^"(?:[^\\"]|\\.)*(?:"|$)/,null,'"'],[PR.PR_STRING,/^'(?:[^']|'')*(?:'|$)/,null,"'"],[PR.PR_COMMENT,/^#[^\r\n]*/,null,"#"],[PR.PR_PLAIN,/^\s+/,null," \t\r\n"]],[[PR.PR_DECLARATION,/^(?:---|\.\.\.)(?:[\r\n]|$)/],[PR.PR_PUNCTUATION,/^-/],[PR.PR_KEYWORD,/^\w+:[ \r\n]/],[PR.PR_PLAIN,/^\w+/]]),
["yaml","yml"]);function uc(){return qc('<div class="devsite-code-buttons-container"></div>')}function vc(){var a='<button class="gc-analytics-event material-icons devsite-icon-code-dark devsite-toggle-dark" data-category="Site-Wide Custom Events" data-label="Dark Code Toggle" track-type="exampleCode" track-name="darkCodeToggle" title="'+"Dark code theme".replace(tc,sc);return qc(a+'"></button>')}
function wc(){var a='<button class="gc-analytics-event material-icons devsite-icon-code-light devsite-toggle-light" data-category="Site-Wide Custom Events" data-label="Light Code Toggle" track-type="exampleCode" track-name="lightCodeToggle" title="'+"Light code theme".replace(tc,sc);return qc(a+'"></button>')}
function xc(){var a='<button class="gc-analytics-event material-icons devsite-icon-copy" data-category="Site-Wide Custom Events" data-label="Click To Copy" track-type="exampleCode" track-name="clickToCopy" title="'+"Click to copy".replace(tc,sc);return qc(a+'"></button>')}
function yc(){var a='<button class="gc-analytics-event material-icons devsite-icon-code" data-category="jsfiddle" data-label="" track-type="exampleCode" track-name="jsfiddle" title="'+"Open in JSFiddle".replace(tc,sc);return qc(a+'"></button>')};/*
 Copyright (c) Microsoft Corporation. All rights reserved.
 Licensed under the Apache License, Version 2.0 (the "License"); you may not use
 this file except in compliance with the License. You may obtain a copy of the
 License at http://www.apache.org/licenses/LICENSE-2.0

 THIS CODE IS PROVIDED ON AN *AS IS* BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION ANY IMPLIED
 WARRANTIES OR CONDITIONS OF TITLE, FITNESS FOR A PARTICULAR PURPOSE,
 MERCHANTABLITY OR NON-INFRINGEMENT.

 See the Apache Version 2.0 License for specific language governing permissions
 and limitations under the License.
*/
var zc=!/^\s*class\s*\{\s*\}\s*$/.test(function(){}.toString());/*

 Copyright (c) 2016 The Polymer Project Authors. All rights reserved.
 This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
 The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
 The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
 Code distributed by Google as part of the polymer project is also
 subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
(function(){if(zc&&!HTMLElement.es5Shimmed&&void 0!==window.Reflect&&void 0!==window.customElements&&!window.customElements.polyfillWrapFlushCallback){var a=HTMLElement;window.HTMLElement=function(){return Reflect.construct(a,[],this.constructor)};HTMLElement.prototype=a.prototype;HTMLElement.prototype.constructor=HTMLElement;HTMLElement.es5Shimmed=!0;Object.setPrototypeOf(HTMLElement,a)}})();function Ac(a){var b=HTMLElement.call(this)||this;a&&(K(a)&&(a=[a]),document.body.dispatchEvent(new CustomEvent("devsite-load-custom-elements",{bubbles:!0,detail:a})));return b}ia(Ac,HTMLElement);Ac.prototype.o=function(){console.warn(this.tagName,"has not implemented update")};Ac.prototype.i=function(a){a=void 0===a?"":a;return document.createRange().createContextualFragment(a||"")};
Ac.prototype.m=function(a,b){a&&b?a.parentNode.replaceChild(document.importNode(b,!0),a):!b&&a?a.parentNode.removeChild(a):!a&&b&&this.appendChild(document.importNode(b,!0))};var Bc=!T||9<=Number(ec),Cc=!Vb&&!T||T&&9<=Number(ec)||Vb&&dc("1.9.1"),Dc=T&&!dc("9"),Lc=T||Tb||Wb;function Mc(a,b){this.x=J(a)?a:0;this.a=J(b)?b:0}g=Mc.prototype;g.Bb=function(){return new Mc(this.x,this.a)};g.va=function(a){return a instanceof Mc&&(this==a?!0:this&&a?this.x==a.x&&this.a==a.a:!1)};g.ceil=function(){this.x=Math.ceil(this.x);this.a=Math.ceil(this.a);return this};g.floor=function(){this.x=Math.floor(this.x);this.a=Math.floor(this.a);return this};g.round=function(){this.x=Math.round(this.x);this.a=Math.round(this.a);return this};
g.Db=function(a,b){a instanceof Mc?(this.x+=a.x,this.a+=a.a):(this.x+=Number(a),oa(b)&&(this.a+=b));return this};g.Cb=function(a,b){b=oa(b)?b:a;this.x*=a;this.a*=b;return this};g.fc=function(a,b){a=a*Math.PI/180;b=b||new Mc(0,0);var c=this.x,d=this.a,e=Math.cos(a);a=Math.sin(a);this.x=(c-b.x)*e-(d-b.a)*a+b.x;this.a=(c-b.x)*a+(d-b.a)*e+b.a};function Nc(a,b){this.width=a;this.height=b}g=Nc.prototype;g.Eb=function(){return new Nc(this.width,this.height)};g.Va=function(){return Math.max(this.width,this.height)};g.ib=function(){return Math.min(this.width,this.height)};g.ac=function(){return 2*(this.width+this.height)};g.aspectRatio=function(){return this.width/this.height};g.Pb=function(){return!(this.width*this.height)};g.ceil=function(){this.width=Math.ceil(this.width);this.height=Math.ceil(this.height);return this};
g.za=function(a){return this.width<=a.width&&this.height<=a.height};g.floor=function(){this.width=Math.floor(this.width);this.height=Math.floor(this.height);return this};g.round=function(){this.width=Math.round(this.width);this.height=Math.round(this.height);return this};function Oc(a,b){var c=oa(void 0)?void 0:b;a.width*=b;a.height*=c;return a}g.hc=function(a){a=this.aspectRatio()<=a.aspectRatio()?a.width/this.width:a.height/this.height;return Oc(this,a)};
g.ic=function(a){a=this.aspectRatio()>a.aspectRatio()?a.width/this.width:a.height/this.height;return Oc(this,a)};function Pc(a){return a?new Qc(U(a)):xa||(xa=new Qc)}function Rc(a,b){var c=b||document,d=null;c.getElementsByClassName?d=c.getElementsByClassName(a)[0]:d=Sc(document,"*",a,b);return d||null}
function Tc(a,b,c,d){a=d||a;var e=b&&"*"!=b?String(b).toUpperCase():"";if(a.querySelectorAll&&a.querySelector&&(e||c))return a.querySelectorAll(e+(c?"."+c:""));if(c&&a.getElementsByClassName){b=a.getElementsByClassName(c);if(e){a={};for(var f=d=0,h;h=b[f];f++)e==h.nodeName&&(a[d++]=h);a.length=d;return a}return b}b=a.getElementsByTagName(e||"*");if(c){a={};for(f=d=0;h=b[f];f++){e=h.className;var p;if(p="function"==typeof e.split)p=0<=za(e.split(/\s+/),c);p&&(a[d++]=h)}a.length=d;return a}return b}
function Sc(a,b,c,d){var e=d||a,f=b&&"*"!=b?String(b).toUpperCase():"";return e.querySelectorAll&&e.querySelector&&(f||c)?e.querySelector(f+(c?"."+c:"")):Tc(a,b,c,d)[0]||null}function Uc(a,b){Ua(b,function(c,d){c&&"object"==typeof c&&c.u&&(c=c.l());"style"==d?a.style.cssText=c:"class"==d?a.className=c:"for"==d?a.htmlFor=c:Vc.hasOwnProperty(d)?a.setAttribute(Vc[d],c):0==d.lastIndexOf("aria-",0)||0==d.lastIndexOf("data-",0)?a.setAttribute(d,c):a[d]=c})}
var Vc={cellpadding:"cellPadding",cellspacing:"cellSpacing",colspan:"colSpan",frameborder:"frameBorder",height:"height",maxlength:"maxLength",nonce:"nonce",role:"role",rowspan:"rowSpan",type:"type",usemap:"useMap",valign:"vAlign",width:"width"};function Wc(a){a=a.document;a=Xc(a)?a.documentElement:a.body;return new Nc(a.clientWidth,a.clientHeight)}function Yc(a){return a.scrollingElement?a.scrollingElement:!Wb&&Xc(a)?a.documentElement:a.body||a.documentElement}
function Zc(a){return a.parentWindow||a.defaultView}function $c(a,b,c,d){function e(h){h&&b.appendChild(K(h)?a.createTextNode(h):h)}for(;d<c.length;d++){var f=c[d];ra(f)&&!ad(f)?P(bd(f)?Da(f):f,e):e(f)}}function V(a,b){return a.createElement(String(b))}function Xc(a){return"CSS1Compat"==a.compatMode}function cd(a){for(var b;b=a.firstChild;)a.removeChild(b)}function dd(a){return a&&a.parentNode?a.parentNode.removeChild(a):null}
function ed(a,b){for(;a&&1!=a.nodeType;)a=b?a.nextSibling:a.previousSibling;return a}function ad(a){return N(a)&&0<a.nodeType}function fd(a){return N(a)&&1==a.nodeType}function gd(a,b){if(!a||!b)return!1;if(a.contains&&1==b.nodeType)return a==b||a.contains(b);if("undefined"!=typeof a.compareDocumentPosition)return a==b||!!(a.compareDocumentPosition(b)&16);for(;b&&a!=b;)b=b.parentNode;return b==a}
function hd(a,b){var c=a.parentNode;if(c==b)return-1;for(;b.parentNode!=c;)b=b.parentNode;return id(b,a)}function id(a,b){for(;b=b.previousSibling;)if(b==a)return-1;return 1}function U(a){return 9==a.nodeType?a:a.ownerDocument||a.document}
function jd(a,b){if("textContent"in a)a.textContent=b;else if(3==a.nodeType)a.data=String(b);else if(a.firstChild&&3==a.firstChild.nodeType){for(;a.lastChild!=a.firstChild;)a.removeChild(a.lastChild);a.firstChild.data=String(b)}else cd(a),a.appendChild(U(a).createTextNode(String(b)))}function kd(a,b,c,d){if(null!=a)for(a=a.firstChild;a;){if(b(a)&&(c.push(a),d)||kd(a,b,c,d))return!0;a=a.nextSibling}return!1}var ld={SCRIPT:1,STYLE:1,HEAD:1,IFRAME:1,OBJECT:1},md={IMG:" ",BR:"\n"};
function nd(a){return od(a)&&pd(a)}function od(a){return T&&!dc("9")?(a=a.getAttributeNode("tabindex"),null!=a&&a.specified):a.hasAttribute("tabindex")}function pd(a){a=a.tabIndex;return oa(a)&&0<=a&&32768>a}function qd(a){if(Dc&&null!==a&&"innerText"in a)a=a.innerText.replace(/(\r\n|\r|\n)/g,"\n");else{var b=[];rd(a,b,!0);a=b.join("")}a=a.replace(/ \xAD /g," ").replace(/\xAD/g,"");a=a.replace(/\u200B/g,"");Dc||(a=a.replace(/ +/g," "));" "!=a&&(a=a.replace(/^\s*/,""));return a}
function rd(a,b,c){if(!(a.nodeName in ld))if(3==a.nodeType)c?b.push(String(a.nodeValue).replace(/(\r\n|\r|\n)/g,"")):b.push(a.nodeValue);else if(a.nodeName in md)b.push(md[a.nodeName]);else for(a=a.firstChild;a;)rd(a,b,c),a=a.nextSibling}function bd(a){if(a&&"number"==typeof a.length){if(N(a))return"function"==typeof a.item||"string"==typeof a.item;if("function"==qa(a))return"function"==typeof a.item}return!1}
function sd(a,b,c,d){if(!b&&!c)return null;var e=b?String(b).toUpperCase():null;return td(a,function(f){var h;(h=!e||f.nodeName==e)&&!(h=!c)&&(h=K(f.className))&&(h=0<=za(f.className.split(/\s+/),c));return h},!0,d)}function td(a,b,c,d){a&&!c&&(a=a.parentNode);for(c=0;a&&(null==d||c<=d);){if(b(a))return a;a=a.parentNode;c++}return null}function Qc(a){this.a=a||I.document||document}g=Qc.prototype;g.pb=Pc;g.jc=function(a){this.a=a};g.s=function(a){return K(a)?this.a.getElementById(a):a};
g.hb=function(a){return K(a)?this.a.getElementById(a):a};g.la=Qc.prototype.s;g.qb=function(a,b){return(b||this.a).getElementsByTagName(String(a))};g.ia=function(a,b,c){return Tc(this.a,a,b,c)};g.Na=function(a,b,c){return Sc(this.a,a,b,c)};g.rb=function(a,b){return Rc(a,b||this.a)};g.ma=Qc.prototype.ia;g.oc=Uc;g.kb=function(a){return Wc(a||Zc(this.a)||window)};
g.Ja=function(){var a=Zc(this.a),b=a.document;var c=0;if(b){c=b.body;var d=b.documentElement;if(d&&c)if(a=Wc(a).height,Xc(b)&&d.scrollHeight)c=d.scrollHeight!=a?d.scrollHeight:d.offsetHeight;else{b=d.scrollHeight;var e=d.offsetHeight;d.clientHeight!=e&&(b=c.scrollHeight,e=c.offsetHeight);c=b>a?b>e?b:e:b<e?b:e}else c=0}return c};
g.Z=function(a,b,c){var d=this.a,e=arguments,f=String(e[0]),h=e[1];if(!Bc&&h&&(h.name||h.type)){f=["<",f];h.name&&f.push(' name="',Pb(h.name),'"');if(h.type){f.push(' type="',Pb(h.type),'"');var p={};Za(p,h);delete p.type;h=p}f.push(">");f=f.join("")}f=d.createElement(f);h&&(K(h)?f.className=h:M(h)?f.className=h.join(" "):Uc(f,h));2<e.length&&$c(d,f,e,2);return f};g.na=Qc.prototype.Z;g.ob=function(a){return this.a.createTextNode(String(a))};
g.ta=function(a,b,c){var d=this.a;c=!!c;for(var e=V(d,"TABLE"),f=e.appendChild(V(d,"TBODY")),h=0;h<a;h++){for(var p=V(d,"TR"),D=0;D<b;D++){var Ea=V(d,"TD");c&&jd(Ea,"\u00a0");p.appendChild(Ea)}f.appendChild(p)}return e};g.gc=function(a){var b=this.a;var c=V(b,"DIV");T?(a=Ib(Lb,a),Nb(c,a),c.removeChild(c.firstChild)):Nb(c,a);if(1==c.childNodes.length)c=c.removeChild(c.firstChild);else{for(b=b.createDocumentFragment();c.firstChild;)b.appendChild(c.firstChild);c=b}return c};g.Nb=function(){return Xc(this.a)};
g.La=function(){return Yc(this.a)};g.Ka=function(){var a=this.a,b=Yc(a);a=Zc(a);return T&&dc("10")&&a.pageYOffset!=b.scrollTop?new Mc(b.scrollLeft,b.scrollTop):new Mc(a.pageXOffset||b.scrollLeft,a.pageYOffset||b.scrollTop)};g.Ba=function(a){a=a||this.a;try{var b=a&&a.activeElement;var c=b&&b.nodeName?b:null}catch(d){c=null}return c};g.mb=function(a,b){a.appendChild(b)};g.lb=function(a,b){$c(U(a),a,arguments,1)};g.nb=function(a){if(1!=a.nodeType)return!1;switch(a.tagName){case "APPLET":case "AREA":case "BASE":case "BR":case "COL":case "COMMAND":case "EMBED":case "FRAME":case "HR":case "IMG":case "INPUT":case "IFRAME":case "ISINDEX":case "KEYGEN":case "LINK":case "NOFRAMES":case "NOSCRIPT":case "META":case "OBJECT":case "PARAM":case "SCRIPT":case "SOURCE":case "STYLE":case "TRACK":case "WBR":return!1}return!0};
g.sb=cd;g.Lb=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b)};g.Kb=function(a,b){b.parentNode&&b.parentNode.insertBefore(a,b.nextSibling)};g.Jb=function(a,b,c){a.insertBefore(b,a.childNodes[c]||null)};g.tb=dd;g.ub=function(a,b){var c=b.parentNode;c&&c.replaceChild(a,b)};g.Aa=function(a){var b,c=a.parentNode;if(c&&11!=c.nodeType){if(a.removeNode)return a.removeNode(!1);for(;b=a.firstChild;)c.insertBefore(b,a);return dd(a)}};
g.Ha=function(a){return Cc&&void 0!=a.children?a.children:Aa(a.childNodes,function(b){return 1==b.nodeType})};g.Pa=function(a){return J(a.firstElementChild)?a.firstElementChild:ed(a.firstChild,!0)};g.Ua=function(a){return J(a.lastElementChild)?a.lastElementChild:ed(a.lastChild,!1)};g.Xa=function(a){return J(a.nextElementSibling)?a.nextElementSibling:ed(a.nextSibling,!0)};g.fb=function(a){return J(a.previousElementSibling)?a.previousElementSibling:ed(a.previousSibling,!1)};
g.Ya=function(a){if(!a)return null;if(a.firstChild)return a.firstChild;for(;a&&!a.nextSibling;)a=a.parentNode;return a?a.nextSibling:null};g.gb=function(a){if(!a)return null;if(!a.previousSibling)return a.parentNode;for(a=a.previousSibling;a&&a.lastChild;)a=a.lastChild;return a};g.Sb=ad;g.Ob=fd;g.Vb=function(a){return N(a)&&a.window==a};g.eb=function(a){var b;if(Lc&&!(T&&dc("9")&&!dc("10")&&I.SVGElement&&a instanceof I.SVGElement)&&(b=a.parentElement))return b;b=a.parentNode;return fd(b)?b:null};
g.contains=gd;
g.sa=function(a,b){if(a==b)return 0;if(a.compareDocumentPosition)return a.compareDocumentPosition(b)&2?1:-1;if(T&&!(9<=Number(ec))){if(9==a.nodeType)return-1;if(9==b.nodeType)return 1}if("sourceIndex"in a||a.parentNode&&"sourceIndex"in a.parentNode){var c=1==a.nodeType,d=1==b.nodeType;if(c&&d)return a.sourceIndex-b.sourceIndex;var e=a.parentNode,f=b.parentNode;return e==f?id(a,b):!c&&gd(e,b)?-1*hd(a,b):!d&&gd(f,a)?hd(b,a):(c?a.sourceIndex:e.sourceIndex)-(d?b.sourceIndex:f.sourceIndex)}d=U(a);c=d.createRange();
c.selectNode(a);c.collapse(!0);a=d.createRange();a.selectNode(b);a.collapse(!0);return c.compareBoundaryPoints(I.Range.START_TO_END,a)};g.wa=function(a){var b,c=arguments.length;if(!c)return null;if(1==c)return arguments[0];var d=[],e=Infinity;for(b=0;b<c;b++){for(var f=[],h=arguments[b];h;)f.unshift(h),h=h.parentNode;d.push(f);e=Math.min(e,f.length)}f=null;for(b=0;b<e;b++){h=d[0][b];for(var p=1;p<c;p++)if(h!=d[p][b])return f;f=h}return f};g.cb=U;g.Ra=function(a){return a.contentDocument||a.contentWindow.document};
g.Sa=function(a){try{var b;if(!(b=a.contentWindow)){if(a.contentDocument){var c=a.contentDocument;var d=c?Zc(c):window}else d=null;b=d}return b}catch(e){}return null};g.rc=jd;g.bb=function(a){if("outerHTML"in a)return a.outerHTML;var b=V(U(a),"DIV");b.appendChild(a.cloneNode(!0));return b.innerHTML};g.xa=function(a,b){var c=[];return kd(a,b,c,!0)?c[0]:void 0};g.ya=function(a,b){var c=[];kd(a,b,c,!1);return c};g.Rb=nd;g.kc=function(a,b){b?a.tabIndex=0:(a.tabIndex=-1,a.removeAttribute("tabIndex"))};
g.Qb=function(a){var b;if((b="A"==a.tagName&&a.hasAttribute("href")||"INPUT"==a.tagName||"TEXTAREA"==a.tagName||"SELECT"==a.tagName||"BUTTON"==a.tagName?!a.disabled&&(!od(a)||pd(a)):nd(a))&&T){var c;"function"!=qa(a.getBoundingClientRect)||T&&null==a.parentElement?c={height:a.offsetHeight,width:a.offsetWidth}:c=a.getBoundingClientRect();a=null!=c&&0<c.height&&0<c.width}else a=b;return a};g.jb=qd;g.$a=function(a){return qd(a).length};
g.ab=function(a,b){b=b||U(a).body;for(var c=[];a&&a!=b;){for(var d=a;d=d.previousSibling;)c.unshift(qd(d));a=a.parentNode}return c.join("").replace(/^[\s\xa0]+/,"").replace(/ +/g," ").length};
g.Za=function(a,b,c){a=[a];for(var d=0,e=null;0<a.length&&d<b;)if(e=a.pop(),!(e.nodeName in ld))if(3==e.nodeType){var f=e.nodeValue.replace(/(\r\n|\r|\n)/g,"").replace(/ +/g," ");d+=f.length}else if(e.nodeName in md)d+=md[e.nodeName].length;else for(f=e.childNodes.length-1;0<=f;f--)a.push(e.childNodes[f]);N(c)&&(c.dc=e?e.nodeValue.length+b-d-1:0,c.node=e);return e};g.Tb=bd;g.Ea=sd;g.Da=function(a,b,c){return sd(a,null,b,c)};g.Ca=td;g.Fa=function(a){return a.getContext("2d")};function ud(a,b){window.getSelection().removeAllRanges();var c=document.createElement("pre");c.setAttribute("is-upgraded","");c.style.position="absolute";c.style.top="-99999px";c.style.left="-99999px";c.classList.add("clear-for-copy");Array.from(b.childNodes).forEach(function(d){d.classList&&d.classList.contains("no-select")||c.appendChild(d.cloneNode(!0))});a.appendChild(c);return c}function vd(a){window.getSelection().selectAllChildren(a);return window.getSelection().toString()}
function wd(a,b){a=ud(a,b);b=!1;vd(a)&&document.queryCommandSupported("copy")&&(document.execCommand("copy"),b=!0);window.getSelection().removeAllRanges();dd(a);return b}function xd(a){var b=document.body,c=document.createElement("pre");c.setAttribute("is-upgraded","");a.forEach(function(d){c.appendChild(d.cloneNode(!0))});a=document.querySelector("devsite-snackbar");wd(b,c)&&a&&a.setAttribute("type","copied-to-clipboard");dd(c)};function yd(){this.B=this.B;this.m=this.m}g=yd.prototype;g.B=!1;g.ka=function(){return this.B};g.Ia=yd.prototype.ka;g.K=function(){this.B||(this.B=!0,this.A())};g.cc=function(a){a=va(zd,a);this.B?J(void 0)?a.call(void 0):a():(this.m||(this.m=[]),this.m.push(J(void 0)?ua(a,void 0):a))};g.A=function(){if(this.m)for(;this.m.length;)this.m.shift()()};function zd(a){a&&"function"==typeof a.K&&a.K()};var Ad=!T||9<=Number(ec),Bd=!T||9<=Number(ec),Cd=T&&!dc("9"),Dd=function(){if(!I.addEventListener||!Object.defineProperty)return!1;var a=!1,b=Object.defineProperty({},"passive",{get:function(){a=!0}});try{I.addEventListener("test",pa,b),I.removeEventListener("test",pa,b)}catch(c){}return a}();function Ed(a,b){this.type=a;this.b=this.target=b;this.G=this.c=!1;this.ba=!0}Ed.prototype.h=function(){this.c=!0};Ed.prototype.f=function(){this.G=!0;this.ba=!1};function W(a,b){Ed.call(this,a?a.type:"");this.relatedTarget=this.b=this.target=null;this.button=this.screenY=this.screenX=this.clientY=this.clientX=this.o=this.m=0;this.key="";this.i=this.j=0;this.metaKey=this.shiftKey=this.altKey=this.ctrlKey=!1;this.D=null;this.I=!1;this.pointerId=0;this.pointerType="";this.a=null;if(a){var c=this.type=a.type,d=a.changedTouches&&a.changedTouches.length?a.changedTouches[0]:null;this.target=a.target||a.srcElement;this.b=b;if(b=a.relatedTarget){if(Vb){a:{try{Qb(b.nodeName);
var e=!0;break a}catch(f){}e=!1}e||(b=null)}}else"mouseover"==c?b=a.fromElement:"mouseout"==c&&(b=a.toElement);this.relatedTarget=b;d?(this.clientX=void 0!==d.clientX?d.clientX:d.pageX,this.clientY=void 0!==d.clientY?d.clientY:d.pageY,this.screenX=d.screenX||0,this.screenY=d.screenY||0):(this.m=Wb||void 0!==a.offsetX?a.offsetX:a.layerX,this.o=Wb||void 0!==a.offsetY?a.offsetY:a.layerY,this.clientX=void 0!==a.clientX?a.clientX:a.pageX,this.clientY=void 0!==a.clientY?a.clientY:a.pageY,this.screenX=a.screenX||
0,this.screenY=a.screenY||0);this.button=a.button;this.j=a.keyCode||0;this.key=a.key||"";this.i=a.charCode||("keypress"==c?a.keyCode:0);this.ctrlKey=a.ctrlKey;this.altKey=a.altKey;this.shiftKey=a.shiftKey;this.metaKey=a.metaKey;this.I=Xb?a.metaKey:a.ctrlKey;this.pointerId=a.pointerId||0;this.pointerType=K(a.pointerType)?a.pointerType:Fd[a.pointerType]||"";this.D=a.state;this.a=a;a.defaultPrevented&&this.f()}}O(W,Ed);var Gd=[1,4,2],Fd={2:"touch",3:"pen",4:"mouse"};
W.prototype.U=function(){return(Ad?0==this.a.button:"click"==this.type?!0:!!(this.a.button&Gd[0]))&&!(Wb&&Xb&&this.ctrlKey)};W.prototype.h=function(){W.w.h.call(this);this.a.stopPropagation?this.a.stopPropagation():this.a.cancelBubble=!0};W.prototype.f=function(){W.w.f.call(this);var a=this.a;if(a.preventDefault)a.preventDefault();else if(a.returnValue=!1,Cd)try{if(a.ctrlKey||112<=a.keyCode&&123>=a.keyCode)a.keyCode=-1}catch(b){}};W.prototype.N=function(){return this.a};var Hd="closure_listenable_"+(1E6*Math.random()|0);function Id(a){return!(!a||!a[Hd])}var Jd=0;function Kd(a,b,c,d,e){this.listener=a;this.a=null;this.src=b;this.type=c;this.capture=!!d;this.L=e;this.key=++Jd;this.F=this.J=!1}function Ld(a){a.F=!0;a.listener=null;a.a=null;a.src=null;a.L=null};function Md(a){this.src=a;this.a={};this.b=0}Md.prototype.c=function(){var a=0,b;for(b in this.a)a+=this.a[b].length;return a};Md.prototype.add=function(a,b,c,d,e){var f=a.toString();a=this.a[f];a||(a=this.a[f]=[],this.b++);var h=Nd(a,b,d,e);-1<h?(b=a[h],c||(b.J=!1)):(b=new Kd(b,this.src,f,!!d,e),b.J=c,a.push(b));return b};
Md.prototype.remove=function(a,b,c,d){a=a.toString();if(!(a in this.a))return!1;var e=this.a[a];b=Nd(e,b,c,d);return-1<b?(Ld(e[b]),Array.prototype.splice.call(e,b,1),0==e.length&&(delete this.a[a],this.b--),!0):!1};function Od(a,b){var c=b.type;c in a.a&&Ca(a.a[c],b)&&(Ld(b),0==a.a[c].length&&(delete a.a[c],a.b--))}function Pd(a,b,c,d,e){a=a.a[b.toString()];b=-1;a&&(b=Nd(a,c,d,e));return-1<b?a[b]:null}
function Qd(a,b,c){var d=J(b),e=d?b.toString():"",f=J(c);return Va(a.a,function(h){for(var p=0;p<h.length;++p)if(!(d&&h[p].type!=e||f&&h[p].capture!=c))return!0;return!1})}function Nd(a,b,c,d){for(var e=0;e<a.length;++e){var f=a[e];if(!f.F&&f.listener==b&&f.capture==!!c&&f.L==d)return e}return-1};var Rd="closure_lm_"+(1E6*Math.random()|0),Sd={},Td=0;function Ud(a,b,c,d,e){if(d&&d.once)return Vd(a,b,c,d,e);if(M(b)){for(var f=0;f<b.length;f++)Ud(a,b[f],c,d,e);return null}c=Wd(c);return Id(a)?a.v(b,c,N(d)?!!d.capture:!!d,e):Xd(a,b,c,!1,d,e)}
function Xd(a,b,c,d,e,f){if(!b)throw Error("Invalid event type");var h=N(e)?!!e.capture:!!e,p=Yd(a);p||(a[Rd]=p=new Md(a));c=p.add(b,c,d,h,f);if(c.a)return c;d=Zd();c.a=d;d.src=a;d.listener=c;if(a.addEventListener)Dd||(e=h),void 0===e&&(e=!1),a.addEventListener(b.toString(),d,e);else if(a.attachEvent)a.attachEvent($d(b.toString()),d);else if(a.addListener&&a.removeListener)a.addListener(d);else throw Error("addEventListener and attachEvent are unavailable.");Td++;return c}
function Zd(){var a=ae,b=Bd?function(c){return a.call(b.src,b.listener,c)}:function(c){c=a.call(b.src,b.listener,c);if(!c)return c};return b}function Vd(a,b,c,d,e){if(M(b)){for(var f=0;f<b.length;f++)Vd(a,b[f],c,d,e);return null}c=Wd(c);return Id(a)?a.h.add(String(b),c,!0,N(d)?!!d.capture:!!d,e):Xd(a,b,c,!0,d,e)}function be(a,b,c,d,e){if(M(b))for(var f=0;f<b.length;f++)be(a,b[f],c,d,e);else d=N(d)?!!d.capture:!!d,c=Wd(c),Id(a)?a.M(b,c,d,e):a&&(a=Yd(a))&&(b=Pd(a,b,c,d,e))&&ce(b)}
function ce(a){if(!oa(a)&&a&&!a.F){var b=a.src;if(Id(b))Od(b.h,a);else{var c=a.type,d=a.a;b.removeEventListener?b.removeEventListener(c,d,a.capture):b.detachEvent?b.detachEvent($d(c),d):b.addListener&&b.removeListener&&b.removeListener(d);Td--;(c=Yd(b))?(Od(c,a),0==c.b&&(c.src=null,b[Rd]=null)):Ld(a)}}}function $d(a){return a in Sd?Sd[a]:Sd[a]="on"+a}
function re(a,b,c,d){var e=!0;if(a=Yd(a))if(b=a.a[b.toString()])for(b=b.concat(),a=0;a<b.length;a++){var f=b[a];f&&f.capture==c&&!f.F&&(f=se(f,d),e=e&&!1!==f)}return e}function se(a,b){var c=a.listener,d=a.L||a.src;a.J&&ce(a);return c.call(d,b)}
function ae(a,b){if(a.F)return!0;if(!Bd){if(!b)a:{b=["window","event"];for(var c=I,d=0;d<b.length;d++)if(c=c[b[d]],null==c){b=null;break a}b=c}d=b;b=new W(d,this);c=!0;if(!(0>d.keyCode||void 0!=d.returnValue)){a:{var e=!1;if(0==d.keyCode)try{d.keyCode=-1;break a}catch(h){e=!0}if(e||void 0==d.returnValue)d.returnValue=!0}d=[];for(e=b.b;e;e=e.parentNode)d.push(e);a=a.type;for(e=d.length-1;!b.c&&0<=e;e--){b.b=d[e];var f=re(d[e],a,!0,b);c=c&&f}for(e=0;!b.c&&e<d.length;e++)b.b=d[e],f=re(d[e],a,!1,b),c=
c&&f}return c}return se(a,new W(b,this))}function Yd(a){a=a[Rd];return a instanceof Md?a:null}var te="__closure_events_fn_"+(1E9*Math.random()>>>0);function Wd(a){if("function"==qa(a))return a;a[te]||(a[te]=function(b){return a.handleEvent(b)});return a[te]};function ue(a){yd.call(this);this.b=a;this.a={}}O(ue,yd);var ve=[];g=ue.prototype;g.v=function(a,b,c,d){return we(this,a,b,c,d)};g.Xb=function(a,b,c,d,e){return we(this,a,b,c,d,e)};function we(a,b,c,d,e,f){M(c)||(c&&(ve[0]=c.toString()),c=ve);for(var h=0;h<c.length;h++){var p=Ud(b,c[h],d||a.handleEvent,e||!1,f||a.b||a);if(!p)break;a.a[p.key]=p}return a}g.wb=function(a,b,c,d){return xe(this,a,b,c,d)};g.Wb=function(a,b,c,d,e){return xe(this,a,b,c,d,e)};
function xe(a,b,c,d,e,f){if(M(c))for(var h=0;h<c.length;h++)xe(a,b,c[h],d,e,f);else{b=Vd(b,c,d||a.handleEvent,e,f||a.b||a);if(!b)return a;a.a[b.key]=b}return a}g.Yb=function(a,b,c,d){b.v(a,c,d,this.b||this);return this};g.Zb=function(a,b,c,d,e){b.v(a,c,d,e||this.b||this);return this};g.vb=function(){var a=0,b;for(b in this.a)Object.prototype.hasOwnProperty.call(this.a,b)&&a++;return a};
g.M=function(a,b,c,d,e){if(M(b))for(var f=0;f<b.length;f++)this.M(a,b[f],c,d,e);else c=c||this.handleEvent,d=N(d)?!!d.capture:!!d,e=e||this.b||this,c=Wd(c),d=!!d,b=Id(a)?Pd(a.h,String(b),c,d,e):a?(a=Yd(a))?Pd(a,b,c,d,e):null:null,b&&(ce(b),delete this.a[b.key])};g.sc=function(a,b,c,d,e){b.M(a,c,d,e||this.b||this,this);return this};function ye(a){Ua(a.a,function(b,c){this.a.hasOwnProperty(c)&&ce(b)},a);a.a={}}g.A=function(){ue.w.A.call(this);ye(this)};
g.handleEvent=function(){throw Error("EventHandler.handleEvent not implemented");};function ze(a){var b=a(Ae,void 0,void 0);a=V(Pc().a,"DIV");if(N(b))if(b instanceof oc)if(b.O===nc)b=Cb(b.toString());else{if(b.O!==lc)throw Error("Sanitized content was not of kind TEXT or HTML.");b=Db(b.toString(),b.X||null)}else b=Cb("zSoyz");else b=Cb(String(b));Nb(a,b);1==a.childNodes.length&&(b=a.firstChild,1==b.nodeType&&(a=b));return a}var Ae={};function Be(){};function Ce(){}O(Ce,Be);Ce.prototype.ha=function(){var a=0;jc(this.H(!0),function(){a++});return a};Ce.prototype.ja=function(){var a=kc(this.H(!0)),b=this;P(a,function(c){b.remove(c)})};function De(a){this.a=a}O(De,Ce);g=De.prototype;g.Mb=function(){if(!this.a)return!1;try{return this.a.setItem("__sak","1"),this.a.removeItem("__sak"),!0}catch(a){return!1}};g.set=function(a,b){try{this.a.setItem(a,b)}catch(c){if(0==this.a.length)throw"Storage mechanism: Storage disabled";throw"Storage mechanism: Quota exceeded";}};g.get=function(a){a=this.a.getItem(a);if(!K(a)&&null!==a)throw"Storage mechanism: Invalid value was encountered";return a};g.remove=function(a){this.a.removeItem(a)};
g.ha=function(){return this.a.length};g.H=function(a){var b=0,c=this.a,d=new hc;d.next=function(){if(b>=c.length)throw gc;var e=c.key(b++);if(a)return e;e=c.getItem(e);if(!K(e))throw"Storage mechanism: Invalid value was encountered";return e};return d};g.ja=function(){this.a.clear()};g.key=function(a){return this.a.key(a)};function Ee(){var a=null;try{a=window.localStorage||null}catch(b){}this.a=a}O(Ee,De);function Fe(){yd.call(this);this.h=new Md(this);this.U=this;this.D=null}O(Fe,yd);Fe.prototype[Hd]=!0;g=Fe.prototype;g.T=function(a){this.D=a};g.xb=function(a,b,c,d){Ud(this,a,b,c,d)};g.removeEventListener=function(a,b,c,d){be(this,a,b,c,d)};
g.yb=function(a){var b,c=this.D;if(c)for(b=[];c;c=c.D)b.push(c);c=this.U;var d=a.type||a;if(K(a))a=new Ed(a,c);else if(a instanceof Ed)a.target=a.target||c;else{var e=a;a=new Ed(d,c);Za(a,e)}e=!0;if(b)for(var f=b.length-1;!a.c&&0<=f;f--){var h=a.b=b[f];e=Ge(h,d,!0,a)&&e}a.c||(h=a.b=c,e=Ge(h,d,!0,a)&&e,a.c||(e=Ge(h,d,!1,a)&&e));if(b)for(f=0;!a.c&&f<b.length;f++)h=a.b=b[f],e=Ge(h,d,!1,a)&&e;return e};
g.A=function(){Fe.w.A.call(this);if(this.h){var a=this.h,b=0,c;for(c in a.a){for(var d=a.a[c],e=0;e<d.length;e++)++b,Ld(d[e]);delete a.a[c];a.b--}}this.D=null};g.v=function(a,b,c,d){return this.h.add(String(a),b,!1,c,d)};g.M=function(a,b,c,d){this.h.remove(String(a),b,c,d)};function Ge(a,b,c,d){b=a.h.a[String(b)];if(!b)return!0;b=b.concat();for(var e=!0,f=0;f<b.length;++f){var h=b[f];if(h&&!h.F&&h.capture==c){var p=h.listener,D=h.L||h.src;h.J&&Od(a.h,h);e=!1!==p.call(D,d)&&e}}return e&&0!=d.ba}
g.zb=function(a,b){a=this.h.a[String(a).toString()];var c=[];if(a)for(var d=0;d<a.length;++d){var e=a[d];e.capture==b&&c.push(e)}return c};g.Ab=function(a,b){return Qd(this.h,J(a)?String(a):void 0,b)};g.qc=function(a){this.U=a};g.pa=function(){};function X(){}X.a=void 0;X.b=function(){return X.a?X.a:X.a=new X};X.prototype.b=0;X.prototype.a="";X.prototype.c=function(a){this.a=a};function Y(a){Fe.call(this);this.i=a||Pc();this.G=He;this.o=null;this.g=!1;this.a=null;this.j=void 0;this.f=this.b=this.c=this.I=null;this.V=this.N=!1}O(Y,Fe);Y.prototype.ea=X.b();var He=null;function Ie(a){var b;(b=a.o)||(b=a.ea,b=b.a+":"+(b.b++).toString(36),b=a.o=b);return b}g=Y.prototype;g.lc=function(a){if(this.c&&this.c.f){var b=this.c.f,c=this.o;c in b&&delete b[c];Wa(this.c.f,a,this)}this.o=a};g.s=function(){return this.a};g.Oa=function(){return this.a};
g.Fb=function(a){if(this.a){var b=this.a||this.i.a,c=b||document;a=c.querySelectorAll&&c.querySelector?c.querySelectorAll("."+a):Tc(document,"*",a,b)}else a=[];return a};g.Gb=function(a){return this.a?Rc(a,this.a||this.i.a):null};g.Ta=function(){this.j||(this.j=new ue(this));return this.j};
function Je(a,b){if(a==b)throw Error("Unable to set parent component");var c;if(c=b&&a.c&&a.o){c=a.c;var d=a.o;c=c.f&&d?Xa(c.f,d)||null:null}if(c&&a.c!=b)throw Error("Unable to set parent component");a.c=b;Y.w.T.call(a,b)}g.T=function(a){if(this.c&&this.c!=a)throw Error("Method not supported");Y.w.T.call(this,a)};g.P=function(){this.a=V(this.i.a,"DIV")};g.ec=function(a){Ke(this,a.parentNode,a)};
function Ke(a,b,c){if(a.g)throw Error("Component already rendered");a.a||a.P();b?b.insertBefore(a.a,c||null):a.i.a.body.appendChild(a.a);a.c&&!a.c.g||Le(a)}g.ua=function(a){if(this.g)throw Error("Component already rendered");if(a){this.N=!0;var b=U(a);this.i&&this.i.a==b||(this.i=Pc(a));this.a=a;Le(this)}else throw Error("Invalid element to decorate");};g.tc=function(){return this.N};function Le(a){a.g=!0;Me(a,function(b){!b.g&&b.s()&&Le(b)})}
function Ne(a){Me(a,function(b){b.g&&Ne(b)});a.j&&ye(a.j);a.g=!1}g.A=function(){this.g&&Ne(this);this.j&&(this.j.K(),delete this.j);Me(this,function(a){a.K()});!this.N&&this.a&&dd(this.a);this.c=this.I=this.a=this.f=this.b=null;Y.w.A.call(this)};function Oe(a,b){return Ie(a)+"."+b}g.$b=function(a){var b={},c;for(c in a)b[c]=Oe(this,a[c]);return b};g.Wa=function(){return this.I};g.mc=function(a){this.I=a};g.Qa=function(a){return a.substring(Ie(this).length+1)};
g.Ma=function(a){if(!this.g)throw Error("Operation not supported while component is not in document");return this.i.s(Oe(this,a))};
g.oa=function(a,b){var c=this.b?this.b.length:0;if(a.g&&(b||!this.g))throw Error("Component already rendered");if(0>c||c>(this.b?this.b.length:0))throw Error("Child component index out of bounds");this.f&&this.b||(this.f={},this.b=[]);if(a.c==this){var d=Ie(a);this.f[d]=a;Ca(this.b,a)}else Wa(this.f,Ie(a),a);Je(a,this);Fa(this.b,c,0,a);a.g&&this.g&&a.c==this?(b=this.a,c=b.childNodes[c]||null,c!=a.s()&&b.insertBefore(a.s(),c)):b?(this.a||this.P(),c=this.b?this.b[c+1]||null:null,Ke(a,this.a,c?c.a:null)):
this.g&&!a.g&&a.a&&a.a.parentNode&&1==a.a.parentNode.nodeType&&Le(a)};g.Ub=function(){if(null==this.G){var a=this.g?this.a:this.i.a.body;a:{var b=U(a);if(b.defaultView&&b.defaultView.getComputedStyle&&(b=b.defaultView.getComputedStyle(a,null))){b=b.direction||b.getPropertyValue("direction")||"";break a}b=""}this.G="rtl"==(b||(a.currentStyle?a.currentStyle.direction:null)||a.style&&a.style.direction)}return this.G};g.pc=function(a){if(this.g)throw Error("Component already rendered");this.G=a};
g.Ga=function(){var a=[];Me(this,function(b){a.push(Ie(b))});return a};function Me(a,b){a.b&&P(a.b,b,void 0)}g.Ib=function(a){return this.b&&a?za(this.b,a):-1};function Pe(a,b){var c=a.b?a.b[0]||null:null;if(c){var d=K(c)?c:Ie(c);c=a.f&&d?Xa(a.f,d)||null:null;if(d&&c){var e=a.f;d in e&&delete e[d];Ca(a.b,c);b&&(Ne(c),c.a&&dd(c.a));Je(c,null)}}if(!c)throw Error("Child is not in parent component");return c}g.Hb=function(a){for(var b=[];this.b&&0!=this.b.length;)b.push(Pe(this,a));return b};g.bc=function(){return this.V};
g.nc=function(a){if(this.g)throw Error("Component already rendered");this.V=a};function Qe(a){Y.call(this,a)}O(Qe,Y);Qe.prototype.P=function(){this.a=this.i.Z("FORM",{method:"POST",style:"display:none"})};function Re(a){var b=new Qe,c=b.s();c||(Ke(b,void 0),c=b.s());c.action="https://jsfiddle.net/api/post/library/pure/";c.target="_blank";Se(b,c,a);c.submit()}function Se(a,b,c){var d,e=[];for(d in c){var f=c[d];ra(f)?P(f,ua(function(h){e.push(Hb({type:"hidden",name:d,value:String(h)}))},a)):e.push(Hb({type:"hidden",name:d,value:String(f)}))}Ob(b,Ib(e))};var Te=["js","html","css"],Ue=!!document.queryCommandSupported("copy");function Z(){var a=Ac.call(this,["devsite-snackbar"])||this;a.a=new ue;a.b=new Ee;a.j=null;a.f=!1;a.c=null;return a}ia(Z,Ac);Z.prototype.connectedCallback=function(){this.b.get("pref_dark-code")&&this.setAttribute("dark-code","");this.f||(Ve(this),We(this),this.f=!0);Xe(this)};Z.prototype.disconnectedCallback=function(){this.removeChild(this.c);ye(this.a)};
function We(a){Array.from(a.querySelectorAll(".prettyprint")).forEach(function(b){b.classList.remove("prettyprint");var c=(c=b.className.match(/\blang(?:uage)?-([\w.]+)(?!\S)/))?c[1]:void 0;b.innerHTML=window.prettyPrintOne(b.innerHTML,c);b.querySelector("strong")&&b.classList.add("devsite-code-highlight")})}
function Ve(a){var b=a.querySelector("pre");b&&(b.classList.remove("devsite-click-to-copy"),b.classList.contains("devsite-disable-click-to-copy")||b.hasAttribute("no-copy"))&&(a.setAttribute("no-copy",""),b.classList.remove("devsite-disable-click-to-copy"),b.removeAttribute("no-copy"));var c=a.querySelector(".devsite-enable-open-in-jsfiddle");c&&(a.setAttribute("js-fiddle",""),c.classList.remove("devsite-enable-open-in-jsfiddle"));a.hasAttribute("js-fiddle")&&(c&&["scope","jsfiddle-title","jsfiddle-wrap"].forEach(function(d){c.hasAttribute("data-"+
d)&&(a.setAttribute(d,c.getAttribute("data-"+d)),c.removeAttribute("data-"+d))}),b=a.getAttribute("scope"),Array.from(document.querySelectorAll('.devsite-jsfiddle-code-sample[data-scope="'+b+'"]')).forEach(function(d){d.parentNode!==a&&a.appendChild(d)}))}
Z.prototype.attributeChangedCallback=function(a,b,c){"dark-code"===a&&b!==c&&(this.hasAttribute("dark-code")?(this.b.set("pref_dark-code","1"),window.requestAnimationFrame(function(){Array.from(document.querySelectorAll("devsite-code:not([dark-code])")).forEach(function(d){d.setAttribute("dark-code","")})})):(this.b.remove("pref_dark-code"),window.requestAnimationFrame(function(){Array.from(document.querySelectorAll("devsite-code[dark-code]")).forEach(function(d){d.removeAttribute("dark-code")})})))};
function Xe(a){var b=ze(uc);if(a.hasAttribute("scope")){var c=ze(yc);a.a.v(c,"click",function(){Ye(a)});a.hasAttribute("jsfiddle-title")&&c.setAttribute("data-label",a.getAttribute("jsfiddle-title"));b.appendChild(c)}c=ze(vc);a.a.v(c,"click",function(){a.setAttribute("dark-code","")});var d=ze(wc);a.a.v(d,"click",function(){a.removeAttribute("dark-code")});if(!a.hasAttribute("no-copy")&&Ue){var e=ze(xc);a.a.v(e,"click",function(){var f=Array.from(a.querySelectorAll("pre"));xd(f)});b.appendChild(e)}b.appendChild(c);
b.appendChild(d);a.appendChild(b);a.c=b;a.dispatchEvent(new CustomEvent("devsite-content-updated",{bubbles:!0}))}function Ye(a){var b={title:a.getAttribute("jsfiddle-title")||"Code sample",wrap:a.getAttribute("jsfiddle-wrap")||"b",description:""};Te.forEach(function(c){Array.from(a.querySelectorAll('[data-type="'+c+'"]')).forEach(function(d){d=ud(a,d);var e=vd(d);window.getSelection().removeAllRanges();dd(d);b[c]=b[c]?b[c]+("\n"+e):e})});Re(b)}
ja.Object.defineProperties(Z,{observedAttributes:{configurable:!0,enumerable:!0,get:function(){return["dark-code"]}}});Z.prototype.attributeChangedCallback=Z.prototype.attributeChangedCallback;Z.prototype.disconnectedCallback=Z.prototype.disconnectedCallback;Z.prototype.connectedCallback=Z.prototype.connectedCallback;try{window.customElements.define("devsite-code",Z)}catch(a){console.warn("devsite.app.customElement.DevsiteCode",a)};}).call(this);
